table 0_Days
	lineageTag: 1b9196fa-a55c-4cbb-a581-9be90a04572c

	measure 0_Collection_Day_Previous =
			
			
			MIN(CALCULATE(SUM(DW_Tenant_Receipts[PAID_AMOUNT]),
			    FILTER(DW_Tenant_Receipts,
			        DW_Tenant_Receipts[CHARGE_DATE].[Day]<=MAX('0_Days'[Day])
			        &&DATE(DW_Tenant_Receipts[CHARGE_DATE_BOM].[Year],DW_Tenant_Receipts[CHARGE_DATE_BOM].[MonthNo]+1,1) = FIRSTNONBLANK('0_Days'[Date],'0_Days'[Date])
			        &&OR( DW_Tenant_Receipts[RECEIVED_DATE].[Day]<=MAX('0_Days'[Day])&&
			        DATE(DW_Tenant_Receipts[RECEIVED_DATE_BOM].[Year],DW_Tenant_Receipts[RECEIVED_DATE_BOM].[MonthNo]+1,1) = FIRSTNONBLANK('0_Days'[Date],'0_Days'[Date]),DW_Tenant_Receipts[RECEIVED_DATE]<=DW_Tenant_Receipts[CHARGE_DATE]))) /
			
			CALCULATE(SUM(DW_Tenant_Charges[Charge_Amount]),
			    FILTER(DW_Tenant_Charges,DW_Tenant_Charges[Charge_Date].[Day]<=MAX('0_Days'[Day])
			        &&DATE(DW_Tenant_Charges[Charge_Date_BOM].[Year],DW_Tenant_Charges[Charge_Date_BOM].[MonthNo]+1,1) = FIRSTNONBLANK('0_Days'[Date],'0_Days'[Date]))),1)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 996e5a3d-e2bd-4263-a741-7f28a2d2418e

		changedProperty = FormatString

		changedProperty = IsHidden

	measure '0_Collection vs LM' = IF([0_Collection_Day_Net]<>BLANK()&&[0_Collection_Day_Previous]<>BLANK(),[0_Collection_Day_Net]-[0_Collection_Day_Previous],BLANK())
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 904b1c1d-6ba7-4acc-bfab-918198292bac

		changedProperty = FormatString

		changedProperty = IsHidden

	measure 0_Concessions_Day =
			
			IF(and(MAX('0_Days'[Day])>DAY(TODAY()),FIRSTNONBLANK('0_Days'[Month_No],'0_Days'[Month_No])=MONTH(TODAY())),
			    BLANK(),
			
			CALCULATE(SUM(DW_Tenant_Receipts[PAID_AMOUNT]),
			    FILTER(DW_Tenant_Receipts,
			         DW_Tenant_Receipts[CREDITTYPEID] = 1
			         &&DW_Tenant_Receipts[CHARGE_DATE].[Day]<=MAX('0_Days'[Day])
			         &&DW_Tenant_Receipts[CHARGE_DATE_BOM]=FIRSTNONBLANK('0_Days'[Date],'0_Days'[Date])
			        ))
			)
		lineageTag: e370e42d-9e1f-4fbe-b216-6ae6a43c0a71

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 0_Collection_Day_Net =
			
			IF(
			    AND(
			        MAX('0_Days'[Day]) > DAY(TODAY()),
			        FIRSTNONBLANK('0_Days'[Month_No], '0_Days'[Month_No]) = MONTH(TODAY())
			        && YEAR(FIRSTNONBLANK('0_Days'[Date], '0_Days'[Date])) = YEAR(TODAY())
			    ),
			    BLANK(),
			
			    MIN((CALCULATE(SUM(DW_Tenant_Receipts[PAID_AMOUNT]),
			        FILTER(DW_Tenant_Receipts,
			             DW_Tenant_Receipts[CHARGE_DATE].[Day] <= MAX('0_Days'[Day])
			             && DW_Tenant_Receipts[CHARGE_DATE_BOM] = FIRSTNONBLANK('0_Days'[Date],'0_Days'[Date])
			             && OR(DW_Tenant_Receipts[RECEIVED_DATE].[Day] <= MAX('0_Days'[Day])
			                   && DW_Tenant_Receipts[RECEIVED_DATE_BOM] = FIRSTNONBLANK('0_Days'[Date],'0_Days'[Date]),
			                   DW_Tenant_Receipts[RECEIVED_DATE] <= DW_Tenant_Receipts[CHARGE_DATE]))) - [0_Concessions_Day]) /
			
			    (CALCULATE(SUM(DW_Tenant_Charges[Charge_Amount]),
			        FILTER(DW_Tenant_Charges,
			            DW_Tenant_Charges[Charge_Date].[Day] <= MAX('0_Days'[Day])
			            && DW_Tenant_Charges[Charge_Date_BOM] = FIRSTNONBLANK('0_Days'[Date],'0_Days'[Date]))) - [0_Concessions_Day]), 1))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 77ae4afc-a8ea-4f72-a1f1-949fa2b6f0af

		changedProperty = FormatString

		changedProperty = IsHidden

	column Day
		dataType: double
		formatString: 0
		lineageTag: 275d08cc-4d35-43a7-b7c3-4bf203b93403
		summarizeBy: sum
		sourceColumn: Day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Month_No
		dataType: int64
		formatString: 0
		lineageTag: 35ffab43-a9e6-42f7-b8fd-5c1b591183a8
		summarizeBy: sum
		sourceColumn: Month_No

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Month Filter'
		dataType: string
		lineageTag: 6f942a30-1d83-4e87-94b2-cb822ba5109e
		summarizeBy: none
		sourceColumn: Month Filter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: c42fd0f3-9854-45e2-aff3-28795fda083e
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: a8bbed3c-d68f-42f5-abee-f78418400557
			defaultHierarchy: LocalDateTable_dfbc5ddc-921b-4888-977b-1c2fa118b9fb.'Date Hierarchy'

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Month-Year
		dataType: string
		lineageTag: e3f7d177-1505-4178-b98e-330d367c649d
		summarizeBy: none
		sourceColumn: Month-Year
		sortByColumn: SORT_BY

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SORT_BY
		dataType: double
		lineageTag: 2032f815-41a5-4c5a-a922-53cbc3c2809c
		summarizeBy: sum
		sourceColumn: SORT_BY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Is_Today = IF(DATE(YEAR('0_Days'[Date]),'0_Days'[Month_No],'0_Days'[Day]) = TODAY(),1,0)
		formatString: 0
		lineageTag: b78e9202-65c0-4ddc-ad8d-6af9ecf3c5e7
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Max Day' =
			
			IF(
			    DATE(YEAR('0_Days'[Date]), MONTH('0_Days'[Date]), 1) = DATE(YEAR(TODAY()), MONTH(TODAY()), 1),
			    '0_Days'[Is_Today],
			    IF('0_Days'[Day] = 31, 1, 0)
			)
		formatString: 0
		lineageTag: 90e2a40b-d07e-4445-87d3-3e4e3d887d64
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BOM
		dataType: dateTime
		formatString: Short Date
		lineageTag: 037bf140-cf5e-4ff2-ba75-fdc255c95bb2
		summarizeBy: none
		sourceColumn: BOM

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Month
		dataType: string
		lineageTag: d22aa9f7-e7ce-4b60-ad3a-906fe975a3a6
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	partition 0_Days-8b5abdc2-abea-46e8-b9ce-4444ace8b895 = m
		mode: import
		queryGroup: Calendar
		source =
				let
				    Source = Value.NativeQuery(Snowflake.Databases("ota12822.us-east-1.snowflakecomputing.com","DEVELOPER_WH",[Implementation="2.0"]){[Name="PROD_REPLICA"]}[Data], "WITH #(lf)#(lf)-- Generate one row per month from Jan 2024 through current month#(lf)Months AS (#(lf)    SELECT DATEADD('month', SEQ4(), DATE_FROM_PARTS(2024, 1, 1)) AS BOM#(lf)    FROM TABLE(GENERATOR(ROWCOUNT => 10000))#(lf)    WHERE BOM <= DATE_TRUNC('month', CURRENT_DATE())#(lf)),#(lf)#(lf)-- Cross join with days 1-31#(lf)Days AS (#(lf)    SELECT column1 AS Day#(lf)    FROM VALUES (1),(2),(3),(4),(5),(6),(7),(8),(9),(10),#(lf)                (11),(12),(13),(14),(15),(16),(17),(18),(19),(20),#(lf)                (21),(22),(23),(24),(25),(26),(27),(28),(29),(30),(31)#(lf)),#(lf)#(lf)DAYS_TEMP AS (#(lf)    SELECT#(lf)         d.Day                                                              AS ""Day""#(lf)        ,MONTH(m.BOM)                                                       AS ""Month_No""#(lf)        ,CASE MONTH(m.BOM)#(lf)            WHEN 1  THEN 'Jan' WHEN 2  THEN 'Feb' WHEN 3  THEN 'Mar'#(lf)            WHEN 4  THEN 'Apr' WHEN 5  THEN 'May' WHEN 6  THEN 'Jun'#(lf)            WHEN 7  THEN 'Jul' WHEN 8  THEN 'Aug' WHEN 9  THEN 'Sep'#(lf)            WHEN 10 THEN 'Oct' WHEN 11 THEN 'Nov' WHEN 12 THEN 'Dec'#(lf)         END                                                                AS ""Month""#(lf)        ,CASE MONTH(m.BOM)#(lf)            WHEN 1  THEN 'Jan' WHEN 2  THEN 'Feb' WHEN 3  THEN 'Mar'#(lf)            WHEN 4  THEN 'Apr' WHEN 5  THEN 'May' WHEN 6  THEN 'Jun'#(lf)            WHEN 7  THEN 'Jul' WHEN 8  THEN 'Aug' WHEN 9  THEN 'Sep'#(lf)            WHEN 10 THEN 'Oct' WHEN 11 THEN 'Nov' WHEN 12 THEN 'Dec'#(lf)         END || '-' || RIGHT(YEAR(m.BOM)::VARCHAR, 2)                      AS ""Month-Year""#(lf)        ,m.BOM                                                              AS ""Date""#(lf)        ,CASE#(lf)            WHEN m.BOM = DATE_TRUNC('month', CURRENT_DATE())               THEN 'Current Month'#(lf)            WHEN m.BOM = DATE_TRUNC('month', DATEADD('month', -1, CURRENT_DATE())) THEN 'Last Month'#(lf)            WHEN m.BOM = DATE_TRUNC('month', DATEADD('month', -2, CURRENT_DATE())) THEN 'T-2 Month'#(lf)            WHEN m.BOM = DATE_TRUNC('month', DATEADD('month', -3, CURRENT_DATE())) THEN 'T-3 Month'#(lf)            ELSE NULL#(lf)         END                                                                AS ""Month Filter""#(lf)    FROM Months m#(lf)    CROSS JOIN Days d#(lf))#(lf)#(lf)SELECT#(lf)     ""Day""#(lf)    ,""Month_No""#(lf)    ,""Month Filter""#(lf)    ,""Date""#(lf)    ,""Month-Year""#(lf)    ,RANK() OVER (ORDER BY ""Date"" DESC)  AS SORT_BY#(lf)    ,""Date""                              AS BOM#(lf)    ,""Month""#(lf)FROM DAYS_TEMP#(lf)ORDER BY ""Date"", ""Day""", null, [EnableFolding=true]),
				    #"Filtered Rows" = Table.SelectRows(Source, each true)
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

