// Working DBT-backed DW_Turns dataset (provided by the data team). One row per
// turn (O_Turn_ID) with turn cost (TKT_COST), completion (TURN_COMPLETED /
// TURN_COMPLETED_BOM), days-in-status, rent growth, and move-out receipts
// (MoveOutReceipts_Final). Net Turn Cost (Collected) = TKT_COST − receipts.
// Backs Summary "Net Turn Cost" and the Turnkey turn metrics. Kept verbatim.
// Heavy (HappyCo/Hubspot joins) — always call cached, never per-request hot.

export const DW_TURNS_SQL = `
WITH CollectionsNote AS (
		SELECT DISTINCT
	 	N.NOTEID AS LatestNoteID
	 	,N.NOTETEXT AS CollectionNote
	 	,N.CREATEDDATE  AS CollectionNoteCreated
	 	,DATEDIFF('Day',N.CREATEDDATE,GETDATE()) CollectionNote_Days
	    ,P.PropertyId
	    ,TI.UserID
	    ,U.FIRSTNAME || ' ' || U.LASTNAME AS CollectionNote_Added_By
	    ,RANK() OVER( PARTITION BY TI.UserID ORDER BY N.CREATEDDATE DESC) AS Recent_Rank
		FROM PROD_REPLICA.HBPM_DBO.NOTES N
		LEFT JOIN PROD_REPLICA.HBPM_DBO.NOTETYPES NT ON NT.Id = N.NoteTypeId
		LEFT JOIN PROD_REPLICA.HBPM_DBO.LOOKUPMASTERS LM ON LM.LookUpMasterId = N.ObjectTypeId
		LEFT JOIN PROD_REPLICA.HBPM_DBO.TENANTINFORMATIONS TI ON TI.UserID = N.ObjectId AND N.ObjectTypeId = 502 AND TI."_FIVETRAN_DELETED" = 'N'
		LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTYADDLINFOES PAI ON PAI.UnitId = TI.UnitId AND PAI."_FIVETRAN_DELETED" ='N'
		LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTIES P ON P.PropertyID = COALESCE(PAI.PropertyId, N.ObjectID) AND P."_FIVETRAN_DELETED" ='N'
		LEFT JOIN PROD_REPLICA.HBPM_DBO.USERS U ON U.USERID  = N.ADDEDBY
	 	WHERE N.NoteTypeId = 3
	 	QUALIFY Recent_Rank = 1)
,PICS AS (
 SELECT
  MAX(PHOTO_COUNT) AS Picture_Count
  ,TRY_TO_NUMERIC(UNIT_) AS PM_PropertyID
  FROM "PROD_REPLICA"."RENTLY"."_3_0_DATA"
  WHERE 1=1
  AND TRY_TO_NUMERIC(UNIT_) IS NOT NULL
  GROUP BY UNIT_
)
,CLEAN_ITEM AS (
SELECT
  ITEM._MODIFIED
 ,ITEM.ID AS ITEM_ID
 ,ITEM.SECTION AS  ITEM_Section
 ,ITEM.ITEM  AS ITEM_Item
 ,ITEM.RATINGS AS  ITEM_Ratings
 ,ITEM.NOTES  AS  ITEM_Notes
 ,ITEM.INSPECTION_ID
 ,RANK() OVER( PARTITION BY ITEM.INSPECTION_ID ORDER BY DATE_TRUNC('min',_FIVETRAN_SYNCED)  DESC) UPDATE_RANK
 ,RANK() OVER( PARTITION BY ITEM_SECTION, ITEM_ITEM, ITEM.INSPECTION_ID ORDER BY DATE_TRUNC('min',_MODIFIED)  DESC) RECENT_RANK
FROM PROD_REPLICA.HAPPYCO_NEW.ITEM_2025 ITEM
)
,CLEAN_UNIT_PRE AS (
 SELECT
   UNIT._MODIFIED
  ,UNIT.ID AS UNIT_ID
  ,UNIT.EXTERNAL_ID AS UNIT_EXTERNAL_ID
  ,UNIT.ADDRESS AS UNIT_ADDRESS
  ,UNIT.LINE_1 AS UNIT_LINE_1
  ,RANK() OVER( PARTITION BY ID ORDER BY DATE_TRUNC('min',_MODIFIED) DESC) RECENT_RANK
FROM PROD_REPLICA.HAPPY_CO.UNIT)
,CLEAN_UNIT AS (
 SELECT DISTINCT
  CLEAN_UNIT_PRE.*
  ,COALESCE (P1.PROPERTY_KEY,P2.PROPERTY_KEY,P3.PROPERTY_KEY,P4.PROPERTY_KEY ) AS PROPERTY_KEY
  ,P1.PROPERTY_KEY P1
  ,P2.PROPERTY_KEY P2
  ,P3.PROPERTY_KEY P3
  ,P4.PROPERTY_KEY  P4
 FROM CLEAN_UNIT_PRE
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P1 ON TO_CHAR(P1.HBAM_PROPERTY_ID) = CLEAN_UNIT_PRE.UNIT_EXTERNAL_ID AND P1.CURRENT_FLAG = 'Y' AND P1.PROPERTY_STATE = 'Active' AND P1.PROPERTY_STATUS <> 'Property Sold'
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P2 ON  P2.ENTITYID = CLEAN_UNIT_PRE.UNIT_EXTERNAL_ID  AND P2.CURRENT_FLAG = 'Y' AND P2.PROPERTY_STATE = 'Active' AND P2.PROPERTY_STATUS <> 'Property Sold'
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P3 ON  INITCAP(TRIM(P3.ADDRESS))  = INITCAP(TRIM(CLEAN_UNIT_PRE.UNIT_LINE_1))  AND P3.CURRENT_FLAG = 'Y' AND P3.PROPERTY_STATE = 'Active' AND P3.PROPERTY_STATUS <> 'Property Sold'
  LEFT JOIN (SELECT LEFT(INITCAP(TRIM(ADDRESS)),9) ADD_TRIM, MAX(PROPERTY_KEY) PROPERTY_KEY
             FROM PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY
             WHERE CURRENT_FLAG = 'Y' AND PROPERTY_STATE = 'Active' AND PROPERTY_STATUS <> 'Property Sold'
             GROUP BY LEFT(INITCAP(TRIM(ADDRESS)),9) ) P4
  	         ON  ADD_TRIM  = LEFT(INITCAP(TRIM(COALESCE(CLEAN_UNIT_PRE.UNIT_LINE_1,UNIT_ADDRESS))),9)
  WHERE CLEAN_UNIT_PRE.RECENT_RANK = 1)
,CLEAN_INPSECTION AS (
 SELECT
  INS._MODIFIED
  ,INS._LINE
 ,INS.INSPECTION_ID
 ,INS.INSPECTION_INSPECTOR_NAME
 ,INS.INSPECTION_COMPLETED_DATE
 ,INS.INSPECTION_STATUS
 ,CASE WHEN INS.INSPECTION_TEMPLATE = '(QC) Turn RRQC Inspection' THEN '(QC) Turn Inspection'
      ELSE  INS.INSPECTION_TEMPLATE END AS INSPECTION_TEMPLATE
 ,INS.INSPECTION_LINK
 ,INS.UNIT_ID
 ,RANK() OVER( PARTITION BY INS.INSPECTION_ID ORDER BY DATE_TRUNC('min',_MODIFIED) DESC) RECENT_RANK
FROM PROD_REPLICA.HAPPY_CO.INSPECTION INS
WHERE INSPECTION_ID NOT IN ('wAS8twd-A-rGt','Qqzpo2d-A-3c2')
)
,HAPPY_CO_DETAIL AS (
SELECT DISTINCT
 CLEAN_UNIT.PROPERTY_KEY
,CLEAN_UNIT.UNIT_ID
,CLEAN_UNIT.UNIT_EXTERNAL_ID
,CLEAN_UNIT.UNIT_Address
,CLEAN_UNIT.UNIT_LINE_1
,RANK() OVER(PARTITION BY CLEAN_UNIT.PROPERTY_KEY, CLEAN_INPSECTION.INSPECTION_TEMPLATE ORDER BY CLEAN_INPSECTION.INSPECTION_COMPLETED_DATE DESC, CLEAN_INPSECTION.INSPECTION_ID DESC) RECENT_INS_RANK
,CLEAN_INPSECTION.INSPECTION_ID
,CLEAN_INPSECTION.INSPECTION_INSPECTOR_NAME
,CLEAN_INPSECTION._LINE
,CLEAN_INPSECTION.INSPECTION_COMPLETED_DATE
,CLEAN_INPSECTION.INSPECTION_STATUS
,CLEAN_INPSECTION.INSPECTION_TEMPLATE
,CLEAN_INPSECTION.INSPECTION_LINK
,CLEAN_ITEM.ITEM_Section
,CLEAN_ITEM.ITEM_Item
,CLEAN_ITEM.ITEM_Ratings
,CLEAN_ITEM.ITEM_Notes
,CASE WHEN CLEAN_ITEM.ITEM_Section = 'Report Status' AND CLEAN_ITEM.ITEM_ITEM = 'Pass/Fail' THEN 1 ELSE 0 END AS Report_Status
,CASE WHEN CLEAN_ITEM.ITEM_ITEM = 'Deficiencies corrected from Scope' THEN 1 ELSE 0 END AS TURN_LINE
,CASE WHEN CLEAN_ITEM.ITEM_Section = 'Pre Leasing Status' THEN 1 ELSE 0 END AS PreLease_Status
FROM CLEAN_INPSECTION
LEFT JOIN CLEAN_ITEM ON CLEAN_ITEM.INSPECTION_ID = CLEAN_INPSECTION.INSPECTION_ID AND CLEAN_ITEM.RECENT_RANK = 1 AND CLEAN_ITEM.UPDATE_RANK = 1
LEFT JOIN CLEAN_UNIT ON CLEAN_UNIT.UNIT_ID = CLEAN_INPSECTION.UNIT_ID AND CLEAN_UNIT.RECENT_RANK = 1
WHERE 1=1
AND CLEAN_INPSECTION.RECENT_RANK = 1
AND CLEAN_INPSECTION.INSPECTION_STATUS = 'Complete'
AND CLEAN_ITEM.ITEM_SECTION IS NOT NULL
)
,RESIWALK_INS AS (
 SELECT
  HI.ID AS INSPECTION_ID
 ,P.PROPERTY_KEY
 ,COALESCE(HI.PROPERTY_LINK_MASTER, HI.PROPERTY_PDF_MASTER_URL) AS INSPECTION_LINK
 ,HI.PROPERTY_COMPLETED_AT::DATE AS INSPECTION_COMPLETED_DATE
 ,HI.PROPERTY_TEMPLATE_TYPE
 ,CASE LOWER(TRIM(GET(OBJECT_CONSTRUCT(HI.*), 'PROPERTY_INSPECTION_RESULT')::TEXT))
    WHEN 'pass' THEN 'Pass'
    WHEN 'fail' THEN 'Fail'
    ELSE NULL
  END AS INSPECTION_RESULT_STD
 FROM PROD_REPLICA.HUBSPOT_2.INSPECTION HI
 LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.ENTITYID = HI.PROPERTY_ENTITY_ID AND P.CURRENT_FLAG = 'Y'
 WHERE (HI._FIVETRAN_DELETED = FALSE OR HI._FIVETRAN_DELETED IS NULL)
 AND HI.PROPERTY_TEMPLATE_TYPE IN ('pm_scope_rate_card','pm_turn_reinspect_qc')
 AND LOWER(HI.PROPERTY_STATUS) = 'completed'
 AND P.PROPERTY_KEY IS NOT NULL
)
,RESIWALK_ANSWER_AGG AS (
 SELECT
  ATI.TO_ID AS INSPECTION_ID
 ,COUNT(CASE WHEN A.PROPERTY_ANSWER_TYPE = 'rate_card_line' THEN 1 END) AS RATE_CARD_LINE_COUNT
 FROM PROD_REPLICA.HUBSPOT_2.INSPECTION_ANSWER_TO_INSPECTION ATI
 JOIN PROD_REPLICA.HUBSPOT_2.INSPECTION_ANSWER A ON A.ID = ATI.FROM_ID
   AND (A._FIVETRAN_DELETED = FALSE OR A._FIVETRAN_DELETED IS NULL)
 GROUP BY ATI.TO_ID
)
,RESIWALK_SCOPE AS (
 SELECT
  R.PROPERTY_KEY
 ,R.INSPECTION_LINK AS HC_SCOPE_INSPECTION_LINK
 ,R.INSPECTION_COMPLETED_DATE AS HC_SCOPE_COMPLETED_DATE
 ,CAST(NULL AS TEXT) AS HC_SCOPE_REPORT_STATUS
 ,AGG.RATE_CARD_LINE_COUNT AS HC_SCOPE_ISSUE_COUNT
 ,RANK() OVER( PARTITION BY R.PROPERTY_KEY, R.INSPECTION_COMPLETED_DATE ORDER BY R.INSPECTION_LINK DESC) AS Recent_Rank
 FROM RESIWALK_INS R
 LEFT JOIN RESIWALK_ANSWER_AGG AGG ON AGG.INSPECTION_ID = R.INSPECTION_ID
 WHERE R.PROPERTY_TEMPLATE_TYPE = 'pm_scope_rate_card'
)
,RESIWALK_QC AS (
 SELECT
  R.PROPERTY_KEY
 ,R.INSPECTION_LINK AS HC_TURN_INSPECTION_LINK
 ,R.INSPECTION_COMPLETED_DATE AS HC_TURN_COMPLETED_DATE
 ,R.INSPECTION_RESULT_STD AS HC_TURN_REPORT_STATUS
 ,AGG.RATE_CARD_LINE_COUNT AS HC_TURN_ISSUE_COUNT
 ,RANK() OVER( PARTITION BY R.PROPERTY_KEY, R.INSPECTION_COMPLETED_DATE ORDER BY R.INSPECTION_LINK DESC) AS Recent_Rank
 FROM RESIWALK_INS R
 LEFT JOIN RESIWALK_ANSWER_AGG AGG ON AGG.INSPECTION_ID = R.INSPECTION_ID
 WHERE R.PROPERTY_TEMPLATE_TYPE = 'pm_turn_reinspect_qc'
)
,HAPPY_CO_SCOPE AS (
SELECT
 HCD.PROPERTY_KEY
,HCD.INSPECTION_LINK AS HC_SCOPE_INSPECTION_LINK
,HCD.INSPECTION_COMPLETED_DATE AS  HC_SCOPE_COMPLETED_DATE
,MAX(CASE WHEN Report_Status = 1 THEN ITEM_Ratings ELSE NULL END) AS HC_SCOPE_REPORT_STATUS
,SUM(CASE WHEN ITEM_Ratings = 'Issue' THEN 1 ELSE NULL END) AS HC_SCOPE_ISSUE_COUNT
,RANK() OVER( PARTITION BY HCD.PROPERTY_KEY, HCD.INSPECTION_COMPLETED_DATE ORDER BY HC_SCOPE_INSPECTION_LINK DESC) AS Recent_Rank
FROM HAPPY_CO_DETAIL HCD
WHERE 1=1
AND ITEM_SECTION <> 'Locks'
AND HCD.INSPECTION_TEMPLATE IN ('(QC) Scope Inspection','(PM) Scope Inspection','(PM) Scope Inspection (BI FIX ONLY)','(PM) Squatter Scope')
GROUP BY
 HCD.PROPERTY_KEY
,HCD.INSPECTION_LINK
,HCD.INSPECTION_COMPLETED_DATE
UNION ALL
SELECT
 PROPERTY_KEY
,HC_SCOPE_INSPECTION_LINK
,HC_SCOPE_COMPLETED_DATE
,HC_SCOPE_REPORT_STATUS
,HC_SCOPE_ISSUE_COUNT
,Recent_Rank
FROM RESIWALK_SCOPE
)
,HAPPY_CO_QC AS (
SELECT
 HCD.PROPERTY_KEY
,HCD.INSPECTION_LINK AS HC_TURN_INSPECTION_LINK
,HCD.INSPECTION_COMPLETED_DATE  AS  HC_TURN_COMPLETED_DATE
,MAX(CASE WHEN Report_Status = 1  THEN ITEM_Ratings ELSE NULL END) AS HC_TURN_REPORT_STATUS
,SUM(CASE WHEN CONTAINS(ITEM_Ratings,'No') AND TURN_LINE = 1 THEN 1 ELSE NULL END) AS HC_TURN_ISSUE_COUNT
,RANK() OVER( PARTITION BY HCD.PROPERTY_KEY, HCD.INSPECTION_COMPLETED_DATE ORDER BY HCD.INSPECTION_LINK DESC) AS Recent_Rank
FROM HAPPY_CO_DETAIL HCD
WHERE 1=1
AND ITEM_SECTION <> 'Locks'
AND (HCD.INSPECTION_TEMPLATE LIKE '(QC) Turn Inspection%'
    OR HCD.INSPECTION_TEMPLATE LIKE '(PM) Turn Inspection%')
GROUP BY
 HCD.PROPERTY_KEY
,HCD.INSPECTION_LINK
,HCD.INSPECTION_COMPLETED_DATE
UNION ALL
SELECT
 PROPERTY_KEY
,HC_TURN_INSPECTION_LINK
,HC_TURN_COMPLETED_DATE
,HC_TURN_REPORT_STATUS
,HC_TURN_ISSUE_COUNT
,Recent_Rank
FROM RESIWALK_QC
)
,UW_RENT_MAX AS (
	SELECT
	MAX(RENTLOGID) RENTLOGID
	, ENTITYID1
	FROM PROD_REPLICA.HBPM_DBO.RENTLOGS
	GROUP BY ENTITYID1)
,UW_RENT AS (
	SELECT
	 RentLogs.ENTITYID1 AS HBPM_UnitID
	,RentLogs.ORIGINALVALUE AS UW_Rent_Prior
	,RentLogs.UPDATEVALUE AS UW_Rent_Current
	,RentLogs.OCCUREDON  AS UW_Update_Date
	FROM UW_RENT_MAX
	LEFT JOIN PROD_REPLICA.HBPM_DBO.RENTLOGS RentLogs ON RentLogs.RENTLOGID = UW_RENT_MAX.RentLogID)
,HHI AS (
SELECT dd.DEAL_KEY
,CASE
	WHEN dl.TOTAL_YEARLY_INCOME <30000 THEN NULL
	WHEN dl.TOTAL_YEARLY_INCOME > 1000000 THEN NULL
	ELSE dl.TOTAL_YEARLY_INCOME
END AS HHI
FROM PROD_ANALYTICS.DBT_RESICAP.FCT_DEAL_STATUS_ACCUM f_deal
JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_DEAL dd
	ON f_deal.DEAL_KEY = dd.DEAL_KEY
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_LEAD dl
	ON f_deal.LEAD_KEY = dl.LEAD_KEY
)
,DEALS AS (SELECT
P.PROPERTY_KEY
,CASE
        WHEN P.ORGANIZATION_KEY IN (-1,18,26,28,48)                    THEN -1
        WHEN P.ORGANIZATION_KEY IN (27,50,51,52,54,45,55,53,56,57,66)  THEN 27
        WHEN P.ORGANIZATION_KEY IN (58,59)                             THEN 58
        WHEN P.ORGANIZATION_KEY IN (62,63,64,65,68,69)                 THEN 62
        WHEN P.ORGANIZATION_KEY IN (61,70,71)                          THEN 61
        WHEN P.ORGANIZATION_KEY IN (72,73,74,75)                       THEN 72
        WHEN P.ORGANIZATION_KEY IN (67)                                THEN 67
        ELSE P.ORGANIZATION_KEY
     END AS ORGANIZATION_KEY
,P.HBPM_PROPERTY_ID
,P.EntityID
,P.Address
,PUS.Under_written_rent
,REC.RECEIEVABLE_ID
,PO.PORTFOLIO_NAME
,R.REGION_NAME
,D.SECURITY_DEPOSIT_ID
,D.DEAL_KEY
,D.DEAL_ID
,COALESCE(D.CURRENT_DEAL_STATUS,HUB_DEAL.DEAL_STAGE) AS CURRENT_DEAL_STATUS
,HUB_DEAL.APP_STAGE AS APP_STAGE
,DSH.LEAD_KEY
,to_date(DSH.HOLDING_FEE_PAID_DATE_KEY::TEXT,'yyyymmdd') AS HOLDING_FEE_DATE_NEW
,to_date(DSH.LEASE_SIGNED_DATE_KEY::TEXT,'yyyymmdd') AS LEASE_SIGNED_DATE
,U.USER_KEY
,TLA.Tenant_key
,D.AVERAGE_CREDIT_SCORE
,D.COMBINED_INCOME * 12  AS COMBINED_INCOME
FROM PROD_ANALYTICS.DBT_RESICAP.DIM_DEAL D
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_DEAL_STATUS_ACCUM DSH ON DSH.DEAL_KEY  = D.Deal_Key
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_LEAD L ON L.LEAD_KEY = DSH.Lead_Key
LEFT JOIN (SELECT Deal_ID ,Value AS RECEIEVABLE_ID
			FROM PROD_REPLICA.HUBSPOT.DEAL_PROPERTY_HISTORY
			WHERE NAME = 'account_receivable' AND _FIVETRAN_ACTIVE = 'Y') REC ON REC.DEAL_ID = D.DEAL_ID
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_USER U ON U.USER_KEY = DSH.User_key
LEFT JOIN (SELECT TLA.*
		FROM PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_LEASING_ACCUM TLA
		LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_TENANT T ON T.Tenant_KEY = TLA.Tenant_key
		LEFT JOIN PROD_REPLICA.HBPM_DBO.TENANTINFORMATIONS TI ON TI.TENANTINFORMATIONID  = T.TENANT_INFORMATION_ID
		WHERE TI._FIVETRAN_DELETED <> 'Y' AND RENTDUEDAY IS NOT NULL AND T.TENANT_KEY NOT IN (70575) ) TLA ON TLA.USER_KEY = U.User_key
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON
P.PROPERTY_KEY = CASE WHEN DSH.PROPERTY_KEY <> -1 THEN DSH.PROPERTY_KEY ELSE TLA.PROPERTY_KEY END
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY  = P.PROPERTY_KEY
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY = PUS.PROPERTY_UNIT_KEY
LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTIES HBPM ON HBPM.PROPERTYID = P.HBPM_PROPERTY_ID
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY = PUS.PORTFOLIO_KEY
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_REGION R ON R.REGION_KEY = PUS.REGION_KEY
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_OWNER_ORGANIZATION O ON O.ORGANIZATION_KEY = PUS.ORGANIZATION_KEY
LEFT JOIN PROD_REPLICA.HBAM_DBO.PROPERTIES HBAM ON HBAM.HBID = P.HBAM_PROPERTY_ID
LEFT JOIN (
SELECT
  CAST(COALESCE(HD.DEAL_PIPELINE_STAGE_ID,APP.PROPERTY_HS_PIPELINE_STAGE) AS INT) AS DEAL_PIPELINE_STAGE_ID
 ,COALESCE(D.DEAL_KEY,APP.APP_ID) AS DEAL_KEY_JOIN
 ,DPS.Label AS DEAL_STAGE
 ,APP_ID
 ,CASE
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 59173506 THEN 'Aplication Started'
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 93217140 THEN 'Needs New Property'
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 59173507 THEN 'Under Review'
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 59187121 THEN 'Conditional Approval'
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 59187122 THEN 'Full Approval'
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 59187127 THEN 'Pending Denial'
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 59187123 THEN 'Pre-Lease Compliance'
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 59187124 THEN 'Lease Drafting'
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 59187125 THEN 'Lease Executed'
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 59187126 THEN 'Move-In Scheduled'
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 59187128 THEN 'Closed Lost'
  ELSE NULL END AS APP_STAGE
 ,rank () over ( partition by APP.APP_ID ORDER BY HD.PROPERTY_HS_LASTMODIFIEDDATE DESC) AS DEAL_RANK
FROM PROD_ANALYTICS.DBT_RESICAP.DIM_DEAL D
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_DEAL_STATUS_ACCUM DSH ON DSH.DEAL_KEY  = D.Deal_Key
  LEFT JOIN PROD_REPLICA.HUBSPOT_2.DEAL HD ON HD.DEAL_ID = D.DEAL_ID
  LEFT JOIN PROD_REPLICA.HUBSPOT_2.APPLICATION_TO_DEAL ATD ON ATD.TO_ID = D.DEAL_ID
  FULL JOIN (
    SELECT DISTINCT A.ID AS APP_ID, A.PROPERTY_UNIT_ID, A.PROPERTY_HS_PIPELINE_STAGE, A.PROPERTY_HOLDING_FEE_TRANSACTION_DATE, P.PROPERTY_KEY
    FROM PROD_REPLICA.HUBSPOT_2.APPLICATION A
    LEFT JOIN (select *, rank () over ( partition by FROM_ID ORDER BY _FIVETRAN_SYNCED DESC ) AS RECENT_RANK
              FROM PROD_REPLICA.HUBSPOT_2.APPLICATION_TO_PROPERTIES QUALIFY RECENT_RANK =1 ) ATP ON ATP.FROM_ID = A.ID
    LEFT JOIN PROD_REPLICA.HUBSPOT_2.PROPERTIES H_P ON H_P.ID = ATP.TO_ID
    LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.HBPM_PROPERTY_ID = H_P.PROPERTY_PROPERTY_ID
    WHERE IS_INTEGER(A.PROPERTY_HS_PIPELINE_STAGE) ='True'
    AND A.PROPERTY_UNIT_ID IS NOT NULL
    AND APP_ID NOT IN (8472470544,8657787708,8657665830)) APP ON APP.APP_ID = ATD.FROM_ID AND APP.PROPERTY_KEY = DSH.PROPERTY_KEY
  LEFT JOIN (SELECT * FROM PROD_REPLICA.HUBSPOT_2.DEAL_PIPELINE_STAGE WHERE _FIVETRAN_DELETED = 'N') DPS ON DPS.STAGE_ID = HD.DEAL_PIPELINE_STAGE_ID
  WHERE 1=1
  QUALIFY DEAL_RANK = 1 ) HUB_DEAL ON HUB_DEAL.DEAL_KEY_JOIN = D.DEAL_KEY
WHERE 1=1
AND P.Property_KEY IS NOT NULL
AND D.DEAL_PIPELINE <> 'Tour Pipeline'
AND D.CURRENT_flag = 'Y'
AND (L.CURRENT_Flag = 'Y' OR DSH.LEAD_KEY = -1)
AND DSH.LEAD_KEY  IS NOT NULL
AND (HBAM.PROPERTYSTATUSID >9 OR HBAM.PROPERTYSTATUSID IS NULL)
AND P.PROPERTY_STATE ='Active'
AND P.EntityID <> ''
AND (HBAM.PROPERTYSTATUSID NOT IN (53,75) OR HBAM.PROPERTYSTATUSID IS NULL)
AND PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54,169)
AND PUS.Organization_KEY not IN (16,17)
AND PO.IS_Active_AM = 'Y'
AND PO.Current_Flag = 'Y'
AND P.Current_Flag = 'Y'
AND PU.Current_Flag = 'Y'
AND PUS.Occupancy_Status NOT IN ('Not Managed')
AND (HBPM.PROPERTYSTATEID = 26 OR HBPM.PROPERTYSTATEID IS NULL)
)
,TENANT AS (
SELECT
 T.TENANT_KEY
,T.TENANT_INFORMATION_ID
,TS.USER_KEY
,T.LEASE_ID
,RANK() OVER (PARTITION BY TS.Property_KEY ORDER BY Lease_ID ASC) AS Lease_Rank
,PU.PROPERTY_UNIT_KEY
,TS.Property_KEY
,P.HBPM_PROPERTY_ID
,PO.Portfolio_Name
,CASE
        WHEN P.ORGANIZATION_KEY IN (-1,18,26,28,48)                    THEN -1
        WHEN P.ORGANIZATION_KEY IN (27,50,51,52,54,45,55,53,56,57,66)  THEN 27
        WHEN P.ORGANIZATION_KEY IN (58,59)                             THEN 58
        WHEN P.ORGANIZATION_KEY IN (62,63,64,65,68,69)                 THEN 62
        WHEN P.ORGANIZATION_KEY IN (61,70,71)                          THEN 61
        WHEN P.ORGANIZATION_KEY IN (72,73,74,75)                       THEN 72
        WHEN P.ORGANIZATION_KEY IN (67)                                THEN 67
        ELSE P.ORGANIZATION_KEY
     END AS ORGANIZATION_KEY
,CASE
        WHEN P.ORGANIZATION_KEY IN (-1,18,26,28,48)                    THEN 'RP SFR'
        WHEN P.ORGANIZATION_KEY IN (27,50,51,52,54,45,55,53,56,57,66)  THEN 'RB DRC'
        WHEN P.ORGANIZATION_KEY IN (58,59)                             THEN 'Hudson Oak'
        WHEN P.ORGANIZATION_KEY IN (62,63,64,65,68,69)                 THEN 'Rocklyn Homes'
        WHEN P.ORGANIZATION_KEY IN (61,70,71)                          THEN 'ROI Property Group'
        WHEN P.ORGANIZATION_KEY IN (72,73,74,75)                       THEN 'McKinley Homes'
        WHEN P.ORGANIZATION_KEY IN (67)                                THEN 'Newstar'
        ELSE O.ORGANIZATION_NAME
     END AS ORGANIZATION_NAME
,P.Address
,P.EntityID
,PUS.Occupancy_Status
,R.REGION_NAME
,U.FULL_NAME
,T.TENANT_STATUS
,T.CURRENT_RENT
,TLA.INITIAL_RENT_AMOUNT
,P.FloorPlan
,PU.SQUARE_FOOTAGE
,to_date(TLA.LEASE_FROM_DATE_KEY::TEXT,'yyyymmdd') AS LEASE_FROM_DATE
,to_date(TLA.LEASE_TO_DATE_KEY::TEXT,'yyyymmdd') AS LEASE_TO_DATE
,to_date(T.NOTICE_DATE_KEY::TEXT,'yyyymmdd') AS NOTICE_DATE
,TI.MoveIn
,TI.MoveOut
,TI.AnticipatedMoveOutDate
,CASE WHEN TI.MoveOut IS NULL THEN NULL WHEN TI.MoveOutComplte = 'Y' THEN 'Yes' ELSE 'No' END AS MoveOutComplete
,to_date(PU.Move_In_Ready::TEXT,'yyyymmdd') AS MOVE_IN_READY
,AM_PM.MoveInReady
,PM_AI.ReasonOffMarketId
,ROM.Description AS ReasonOffMarketName
,Offmarket.OffMarketDate
,'https://honeybadgerpm.com/ReportingModule/ViewReport?reportId=1807&UnitId='||TI.UnitID||'&UserId='||TI.UserID||'#/' AS URL_SODA
,UW_Rent.UW_Rent_Prior
,UW_Rent.UW_Rent_Current
,UW_Rent.UW_Update_Date
,PICS.PICTURE_COUNT
,AM_STRATEGY.STRATEGYNAME AS STRATEGY_NAME
,CN.CollectionNote
,CN.CollectionNoteCreated
,CN.CollectionNote_Days
,CN.CollectionNote_Added_By
,CASE WHEN T.PEts ='Y' THEN 'PET' ELSE NULL END AS PET_FLAG
,'Re-Lease' AS TYPE
FROM PROD_ANALYTICS.DBT_RESICAP.DIM_TENANT T
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_ACTIVITY TS ON TS.TENANT_KEY = T.TENANT_KEY
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_LEASING_ACCUM TLA ON TLA.TENANT_KEY = T.Tenant_Key
LEFT JOIN PROD_REPLICA.HBPM_DBO.TENANTINFORMATIONS TI ON TI.TenantInformationId = T.TENANT_INFORMATION_ID
LEFT JOIN PROD_REPLICA.HBPM_DBO.LOOKUPMASTERS DNR on DNR.LookUpMasterId = TI.ReasonForNotRenewingId
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_USER U ON U.USER_KEY = TS.USER_KEY
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY = TS.PROPERTY_KEY
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY  = P.PROPERTY_KEY
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY = PUS.PROPERTY_UNIT_KEY
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY = PUS.PORTFOLIO_KEY
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_OWNER_ORGANIZATION O ON O.ORGANIZATION_KEY = PUS.ORGANIZATION_KEY
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_REGION R ON R.REGION_KEY = PUS.REGION_KEY
LEFT JOIN PROD_REPLICA.HBAM_DBO.PROPERTIES HBAM ON HBAM.HBID = P.HBAM_PROPERTY_ID
LEFT JOIN PROD_REPLICA.HBAM_DBO.PROPERTYMANAGEMENTS AM_PM ON AM_PM.PROPERTYMANAGEMENTID = HBAM.PropertyManagement_PropertyManagementId AND AM_PM.HBID = HBAM.HBID
LEFT JOIN PROD_REPLICA.HBAM_DBO.BidAndAuctions AM_BA ON AM_BA.BIDID = HBAM.BidAndAuction_BidId AND AM_BA.HBID = HBAM.HBID AND AM_BA."_FIVETRAN_DELETED" <> 'Y'
LEFT JOIN PROD_REPLICA.HBAM_DBO.Strategies AM_STRATEGY ON AM_STRATEGY.STRATEGYID = AM_BA.BIDSTRATEGYSTATUS
LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTIES HBPM ON HBPM.PROPERTYID = P.HBPM_PROPERTY_ID
LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTYADDLINFOES PM_AI ON PM_AI.PROPERTYID  = HBPM.PROPERTYID AND PM_AI."_FIVETRAN_DELETED" = 'N'
LEFT JOIN PROD_REPLICA.HBPM_DBO.LOOKUPMASTERS ROM ON ROM.LookUpMasterId = PM_AI.ReasonOffMarketId
LEFT JOIN CollectionsNote CN ON CN.UserID = TI.UserID
LEFT JOIN (
			SELECT PROPERTY_KEY, MAX(to_date(CHANGED_DATE_KEY::TEXT,'yyyymmdd')) OffMarketDate
			FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROP_UNIT_STATUS_HIST
			WHERE NEW_OCCUPANCY_STATUS = 'Vacant - Off Market'
			GROUP BY PROPERTY_KEY ) OffMarket ON OffMarket.Property_key = P.Property_key
LEFT JOIN UW_RENT ON UW_Rent.HBPM_UnitID = PM_AI.UnitID
LEFT JOIN PICS ON PICS.PM_PropertyID = P.HBPM_PROPERTY_ID
WHERE 1=1
AND T.CURRENT_FLAG = 'Y'
AND T.PRIMARY_TENANT = 'Y'
AND P.PROPERTY_STATE ='Active'
AND P.EntityID <> ''
AND TI._FIVETRAN_DELETED <> 'Y'
AND TI.RENTDUEDAY IS NOT NULL
AND PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54,169)
AND P.Organization_KEY not IN (16,17)
AND PO.IS_Active_AM = 'Y'
AND PO.Current_Flag = 'Y'
AND P.Current_Flag = 'Y'
AND PU.Current_Flag = 'Y'
AND PUS.Occupancy_Status NOT IN ('Property SOLD','Not Managed'))
,HAPPY_CO_TURN AS (
SELECT
Tenant.Lease_ID
,Tenant.Property_Key
,Tenant.MoveOut
,MIN(HAPPY_CO_SCOPE.HC_SCOPE_COMPLETED_DATE) HC_SCOPE_COMPLETED_DATE
,MIN(HAPPY_CO_QC.HC_TURN_COMPLETED_DATE) HC_TURN_COMPLETED_DATE
FROM Tenant
LEFT JOIN HAPPY_CO_SCOPE ON HAPPY_CO_SCOPE.Property_Key = Tenant.Property_key
                            AND HAPPY_CO_SCOPE.HC_SCOPE_COMPLETED_DATE >= Tenant.MoveOut
                            AND HAPPY_CO_SCOPE.Recent_Rank = 1
LEFT JOIN HAPPY_CO_QC ON  HAPPY_CO_QC.Property_Key = Tenant.Property_key
                            AND HAPPY_CO_QC.HC_TURN_COMPLETED_DATE  >= Tenant.MoveOut
                            AND  HAPPY_CO_QC.Recent_Rank = 1
WHERE 1=1
GROUP BY Tenant.Lease_ID,Tenant.Property_Key,Tenant.MoveOut
)
,Turnkey AS (
 SELECT
 Tenant.Lease_ID AS O_TURN_ID
,Tenant.Lease_Rank AS  O_Lease_Rank
,Tenant.Tenant_KEY AS O_Tenant_KEY
,Tenant.TENANT_STATUS AS O_Tenant_Status
,Tenant.FULL_NAME AS O_Tenant_FULL_NAME
,Tenant.PROPERTY_UNIT_KEY
,Tenant.Property_KEY
,Tenant.HBPM_Property_Id
,Tenant.Portfolio_Name
,Tenant.Address
,Tenant.EntityID
,Tenant.Occupancy_Status
,Tenant.Region_Name
,Tenant.SQUARE_FOOTAGE
,Tenant.FloorPlan
,Tenant.TYPE
,Tenant.CURRENT_RENT AS O_Current_Rent
,Tenant.MoveIn AS O_MoveIn
,Tenant.LEASE_FROM_DATE AS O_LEASE_FROM_DATE
,Tenant.LEASE_TO_DATE AS O_LEASE_TO_DATE
,Tenant.NOTICE_DATE AS O_Notice_Date
,Tenant.AnticipatedMoveOutDate AS O_AnticipatedMoveOutDate
,Tenant.MoveOut AS O_Move_Out
,DATE_TRUNC('month',Tenant.MoveOut) AS O_Move_Out_BOM
,Tenant_New.Lease_ID AS N_TURN_ID
,Tenant_New.Lease_Rank AS  N_Lease_Rank
,COALESCE(Tenant_New.INITIAL_RENT_AMOUNT,Tenant_New.CURRENT_RENT) AS N_Initial_Rent
,Tenant_New.CURRENT_RENT AS N_Current_Rent
,Tenant_New.MoveIn AS N_MoveIn
,Tenant_New.LEASE_FROM_DATE AS N_LEASE_FROM_DATE
,Tenant_New.LEASE_TO_DATE AS N_LEASE_TO_DATE
,Tenant_New.MoveOut AS N_Move_Out
,CASE
        WHEN Tenant.ORGANIZATION_KEY IN (-1,18,26,28,48)                    THEN 'RP SFR'
        WHEN Tenant.ORGANIZATION_KEY IN (27,50,51,52,54,45,55,53,56,57,66)  THEN 'RB DRC'
        WHEN Tenant.ORGANIZATION_KEY IN (58,59)                             THEN 'Hudson Oak'
        WHEN Tenant.ORGANIZATION_KEY IN (62,63,64,65,68,69)                 THEN 'Rocklyn Homes'
        WHEN Tenant.ORGANIZATION_KEY IN (61,70,71)                          THEN 'ROI Property Group'
        WHEN Tenant.ORGANIZATION_KEY IN (72,73,74,75)                       THEN 'McKinley Homes'
        WHEN Tenant.ORGANIZATION_KEY IN (67)                                THEN 'Newstar'
        ELSE Tenant.ORGANIZATION_NAME
     END AS ORGANIZATION_NAME
,Tenant.MoveInReady
,Tenant.MoveOutComplete
,Tenant.MOVE_IN_READY AS Listing_MI_READY_DATE
,HAPPY_CO_SCOPE.HC_SCOPE_COMPLETED_DATE
,HAPPY_CO_QC.HC_TURN_COMPLETED_DATE
,HAPPY_CO_QC.HC_TURN_REPORT_STATUS
,HAPPY_CO_QC.HC_TURN_ISSUE_COUNT
,CASE WHEN HAPPY_CO_QC.HC_TURN_REPORT_STATUS = 'Pass' AND HAPPY_CO_QC.HC_TURN_ISSUE_COUNT > 0 THEN 'Pass (Minor Fail)'
      WHEN HAPPY_CO_QC.HC_TURN_REPORT_STATUS = 'Pass w/Minor Fails' THEN 'Pass (Minor Fail)'
      ELSE NULL END AS PASS_MINOR
,Tenant.STRATEGY_NAME
FROM Tenant
LEFT JOIN Tenant AS Tenant_New ON TENANT_NEW.Property_Key = TENANT.Property_Key AND (TENANT_NEW.Lease_Rank = TENANT.Lease_Rank +1)
LEFT JOIN HAPPY_CO_TURN HCT ON HCT.Lease_ID = Tenant.Lease_ID
LEFT JOIN HAPPY_CO_SCOPE ON HAPPY_CO_SCOPE.HC_SCOPE_COMPLETED_DATE = HCT.HC_SCOPE_COMPLETED_DATE AND HAPPY_CO_SCOPE.Property_key = HCT.Property_key AND HAPPY_CO_SCOPE.RECENT_RANK = 1
LEFT JOIN HAPPY_CO_QC ON HAPPY_CO_QC.HC_TURN_COMPLETED_DATE = HCT.HC_TURN_COMPLETED_DATE AND HAPPY_CO_QC.Property_key = HCT.Property_key AND HAPPY_CO_QC.RECENT_RANK = 1
WHERE 1=1
AND (Tenant.MoveOut IS NOT NULL OR Tenant.AnticipatedMoveOutDate <= DATEADD('day',60, GETDATE() ) )
)
,Turn_Listings AS (
SELECT
MIN(RENT_LIST_HIST_ID) RENT_LIST_HIST_KEY
,O_Turn_ID
,Turnkey.Property_key
FROM Turnkey
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROP_RENTAL_LISTING_HIST RLH ON RLH.PROPERTY_KEY  = Turnkey.Property_key
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_LISTING DL  ON DL.LISTING_KEY  = RLH.LISTING_KEY
WHERE 1=1
AND to_date(RLH.LISTING_DATE_KEY::TEXT,'yyyymmdd')  >= O_LEASE_FROM_DATE
AND to_date(RLH.LISTING_DATE_KEY::TEXT,'yyyymmdd') <= COALESCE(N_LEASE_FROM_DATE,'1/1/9999')
AND RLH.LISTING_STATUS <> 'Withdrawn'
AND ((RLH.LISTING_STATUS IN ('Active','Deposit Taken', 'Leased') AND DL.LISTING_STATE IS NOT NULL AND DL.IS_PUBLISHED <> 'N')
      OR RLH.LISTING_STATUS IN ('Deposit Taken', 'Leased'))
GROUP BY O_Turn_ID ,Turnkey.Property_key)
,MoveOutLineItems AS (
SELECT
  TI.LEASEID
 ,LT.Amount as Payments
 ,AR.Description as Description
 ,TI.USERID
FROM PROD_ANALYTICS.DBT_RESICAP.FCT_LEASING_TRANSACTION LT
LEFT JOIN PROD_REPLICA.HBPM_DBO.MoveOutSettleCharges MSC ON MSC.RECEIVABLESID = LT.RECEIVABLE_ID AND MSC._FIVETRAN_DELETED = 'N'
LEFT JOIN PROD_REPLICA.HBPM_DBO.AccountsReceivables AR ON  AR.ReceivableID = LT.RECEIVABLE_ID
LEFT JOIN PROD_REPLICA.HBPM_DBO.GLAccounts GL ON  GL.GLAccountID  = AR.GLACCOUNTID
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_TENANT TEN ON TEN.LEASE_ID = AR.LeaseID AND TEN.PRIMARY_TENANT = 'Y'  AND TEN.CURRENT_FLAG = 'Y'
LEFT JOIN PROD_REPLICA.HBPM_DBO.TENANTINFORMATIONS TI ON TI.TenantInformationId = TEN.TENANT_INFORMATION_ID
WHERE 1=1
AND AR.RECEIVABLESTATUSID = 901
AND AR."_FIVETRAN_DELETED"='N'
AND LT.TRANSACTION_TYPE = 'Charges'
AND LT.STATUS = 'Active'
AND LT.IS_CREDIT = 'N'
AND  GL.GLAccountID = 20
)
,MoveOutCharges AS (
SELECT LeaseID,SUM(Payments) MoveOutCharges
FROM MoveOutLineItems
WHERE LeaseID IS NOT NULL
AND Description NOT LIKE '%Early Term%'
AND Description NOT LIKE '%Insufficient Notice%'
AND Description NOT LIKE '%Prorated%'
GROUP BY LEASEID
)
,BadDebt AS (
Select
ARD.ReceiptId
,MAX(AR.CreditTypeID) CreditTYpeID
FROM PROD_REPLICA.HBPM_DBO.ACCOUNTSRECEIPTDETAILS ARD
LEFT JOIN PROD_REPLICA.HBPM_DBO.ACCOUNTSRECEIVABLES AR ON AR.ReceivableID = ARD.ReceivableId
WHERE AR.ReceivableStatusId = 901
GROUP BY ARD.ReceiptId )
,MoveOutLineItemsReceipts AS (
SELECT
  TI.LEASEID
 ,LT.Amount as Payments
 ,ARV.Description as Description
 ,BD.CreditTypeId
 ,TI.USERID
FROM PROD_ANALYTICS.DBT_RESICAP.FCT_LEASING_TRANSACTION LT
LEFT JOIN PROD_REPLICA.HBPM_DBO.ACCOUNTSRECEIPTDETAILS ARD ON  ARD.RECEIPTDETAILID = LT.RECEIPT_DETAIL_ID AND ARD."_FIVETRAN_DELETED"='N'
LEFT JOIN PROD_REPLICA.HBPM_DBO.ACCOUNTSRECEIPTS AR ON AR.RECEIPTID = ARD.RECEIPTID AND AR."_FIVETRAN_DELETED"='N'
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_GL_ACCOUNT GL ON GL.GL_ACCOUNT_KEY = LT.GL_ACCOUNT_KEY
LEFT JOIN BadDebt BD ON BD.ReceiptID = ARD.ReceiptID
LEFT JOIN PROD_REPLICA.HBPM_DBO.AccountsReceivables ARV ON  ARV.ReceivableID = LT.RECEIVABLE_ID
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_TENANT TEN ON TEN.LEASE_ID = AR.LeaseID AND TEN.PRIMARY_TENANT = 'Y'  AND TEN.CURRENT_FLAG = 'Y'
LEFT JOIN PROD_REPLICA.HBPM_DBO.TENANTINFORMATIONS TI ON TI.TenantInformationId = TEN.TENANT_INFORMATION_ID
WHERE 1=1
AND LT.TRANSACTION_TYPE = 'Payment'
AND LT.Tenant_Key IS NOT NULL
AND (AR.RECEIPTSTATUSID IN (901,904) OR AR.RECEIPTSTATUSID Is null)
AND ARD."_FIVETRAN_DELETED"='N'
AND AR."_FIVETRAN_DELETED"='N'
AND LT.STATUS = 'Active'
AND LT.IS_CREDIT = 'N'
AND  LT.CHARGE_GL_ACCOUNT_NUMBER = '4016'
)
,MoveOutReceipts AS (
SELECT
	LeaseID
	,SUM(CASE WHEN CreditTypeId IS NULL THEN Payments ELSE 0 END) MoveOutReceipts_PAID
  	,SUM(CASE WHEN CreditTypeId = 1 THEN Payments ELSE 0 END ) MoveOutReceipts_CONCESSION
  	,SUM(CASE WHEN CreditTypeId = 2 THEN Payments ELSE 0 END) MoveOutReceipts_BAD_DEBT
  	,SUM(Payments) MoveOutReceipts_TOTAL
FROM MoveOutLineItemsReceipts
WHERE LeaseID IS NOT NULL
AND Description NOT LIKE '%Early Term%'
AND Description NOT LIKE '%Insufficient Notice%'
AND Description NOT LIKE '%Prorated%'
GROUP BY LEASEID
)
,WO_DETAIL AS (
SELECT
TI.TICKET_KEY
,WO.WORKORDER_KEY
,TI.TICKET_TYPE
,TI.TICKET_STATUS
,WO.WORKORDER_STATUS
,P.Property_Key
,C.CATEGORYNAME
,to_date(TI.CREATED_DATE_KEY::TEXT,'YYYYMMDD') AS TICKET_CREATED_DATE
,to_date(WO.CREATED_DATE_KEY::TEXT,'YYYYMMDD') AS WO_CREATED_DATE
,to_date(WOST.WO_CLOSED_DATE_KEY::TEXT,'YYYYMMDD') AS WO_CLOSED_DATE
,to_date(WO_END_DATE_KEY::TEXT,'YYYYMMDD') AS WO_END_DATE
,to_date(WOST.WO_REQUESTED_DATE_KEY::TEXT,'YYYYMMDD') AS WO_REQUESTED_DATE
,to_date(DBT_WOI.CLIENT_INVOICE_DATE_KEY::TEXT,'YYYYMMDD') AS CLIENT_INVOICE_DATE
,COALESCE (to_date(DBT_WOI.VENDOR_INVOICE_DATE_KEY::TEXT,'YYYYMMDD'), to_date(WOST.WO_CLOSED_DATE_KEY::TEXT,'YYYYMMDD') )  AS VENDOR_INVOICE_DATE
,CASE WHEN WO.WORKORDER_STATUS ='Closed' THEN ZEROIFNULL(DBT_WOI.CLIENT_INVOICE_AMOUNT) ELSE DBT_WOI.CLIENT_INVOICE_AMOUNT END AS CLIENT_INVOICE_AMOUNT
,EST.CLIENT_ESTIMATE
,NULL::TEXT                    AS WO_NOTE_TEXT
,NULL::DATE                    AS WO_NOTE_CREATED_DATE
,NULL::TEXT                    AS WO_NOTE_ADDED_BY
FROM PROD_ANALYTICS.DBT_RESICAP.DIM_TICKET TI
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TICKET_STATUS_ACCUM TSA ON TSA.TICKET_KEY  = TI.TICKET_KEY
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_WO_STATUS_ACCUM WOST ON WOST.TICKET_KEY  = TI.TICKET_KEY
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_WORKORDER WO ON WO.WORKORDER_KEY = WOST.WORKORDER_KEY AND WO.CURRENT_FLAG = 'Y'
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_WO_INVOICE DBT_WOI ON DBT_WOI.WORKORDER_KEY  = WO.WorkORder_key
LEFT JOIN (SELECT WORKORDER_KEY AS DBT_WO_KEY, SUM (MARKUP_AMOUNT) AS CLIENT_ESTIMATE
			FROM PROD_ANALYTICS.DBT_RESICAP.FCT_WO_ESTIMATED_MATERIAL
			GROUP BY WORKORDER_KEY ) EST ON EST.DBT_WO_KEY = WOST.WORKORDER_KEY
LEFT JOIN (SELECT Min(MaintenanceCategoryDetailId) AS MaintenanceCategoryDetailID
				,MaintenanceIDKey
                FROM PROD_REPLICA.HBMM_DBO.MAINTENANCECATEGORYDETAILS
				GROUP BY MaintenanceIDKey) MCD on MCD.MaintenanceIdkey = WO.MAINT_ID
LEFT JOIN PROD_REPLICA.HBMM_DBO.MaintenanceCategoryDetails on MaintenanceCategoryDetails.MaintenanceCategoryDetailId = MCD.MaintenanceCategoryDetailID
LEFT JOIN PROD_REPLICA.HBMM_DBO.MaintenanceCategories C on C.CategoryId = MaintenanceCategoryDetails.CategoryId
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY = TSA.PROPERTY_KEY AND P.CURRENT_FLAG ='Y'
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY = P.PROPERTY_KEY
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY = PUS.PROPERTY_UNIT_KEY
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY = PUS.PORTFOLIO_KEY
WHERE 1=1
AND (WO.WORKORDER_STATUS <> 'Cancelled' OR WO.WORKORDER_STATUS IS NULL)
AND TI.TICKET_STATUS <> 'Cancelled'
AND ((TI.TICKET_STATUS = 'Closed' AND WO.WORKORDER_KEY IS NOT NULL)
	OR (TI.TICKET_STATUS = 'Open' AND WO.WORKORDER_KEY IS NOT NULL )
	OR (TI.TICKET_STATUS <> 'Closed' AND TI.TICKET_STATUS <> 'Open') )
AND TI.CREATED_DATE_KEY > '20210101'
AND P.PROPERTY_STATE ='Active'
AND P.EntityID <> ''
AND P.Organization_KEY not IN (16,17)
AND PO.IS_Active_AM = 'Y'
AND PO.Current_Flag = 'Y'
AND P.Current_Flag = 'Y'
AND PU.Current_Flag = 'Y'
AND PUS.Occupancy_Status NOT IN ('Property SOLD','Not Managed')
)
,WO_TURN AS (
SELECT
WO_DETAIL.TICKET_KEY
,WO_DETAIL.WORKORDER_KEY
,MIN(Turnkey.O_TURN_ID) O_Turn_ID
FROM WO_DETAIL
LEFT JOIN Turnkey ON Turnkey.Property_key = WO_DETAIL.Property_key
WHERE 1=1
AND (TICKET_TYPE = 'Turnkey' OR CategoryName = 'Unit Turns (Paint/Clean/Minor Repairs)')
AND TICKET_TYPE <> 'Trespassers/Vandalism'
AND TICKET_CREATED_DATE >=  to_date(LEAST(Turnkey.O_MOVE_OUT,O_Notice_Date)::TEXT,'AUTO')
AND (TICKET_CREATED_DATE <= Turnkey.N_LEASE_FROM_DATE OR N_LEASE_FROM_DATE IS NULL)
GROUP BY WO_DETAIL.TICKET_KEY,WO_DETAIL.WORKORDER_KEY)
,TURN_WO_SUMMARY AS (
SELECT
WO_TURN.O_TURN_ID
,MIN(TICKET_CREATED_DATE) AS TKT_Created_Min
,MAX(TICKET_CREATED_DATE) AS TKT_Created_Max
,MAX(WO_END_DATE) AS WO_END_DATE
,MAX(WO_REQUESTED_DATE) AS WO_REQUESTED_DATE
,MIN(WORKORDER_STATUS) AS WO_STATUS
,MAX(COALESCE(CLIENT_INVOICE_DATE,WO_CLOSED_DATE,VENDOR_INVOICE_DATE)) AS TKT_Closed_Max
,SUM(CASE WHEN (TICKET_STATUS = 'Open' AND WORKORDER_STATUS NOT IN ('Closed','Unbilled','Completed Awaiting Approval'))
			OR (TICKET_STATUS = 'New' AND WO_DETAIL.WORKORDER_KEY IS NULL) THEN 1 ELSE NULL END) AS TKT_WOS_OPEN
,SUM(CASE WHEN WORKORDER_STATUS IN ('Closed','Unbilled','Completed Awaiting Approval') THEN 1 ELSE NULL END) AS TKT_WOS_CLOSED
,SUM(GREATEST(COALESCE(CLIENT_INVOICE_AMOUNT,CLIENT_ESTIMATE),COALESCE(CLIENT_ESTIMATE,CLIENT_INVOICE_AMOUNT))) AS TKT_COST
FROM WO_DETAIL
JOIN WO_TURN ON WO_TURN.TICKET_KEY = WO_DETAIL.TICKET_KEY
			AND (CASE WHEN WO_DETAIL.WORKORDER_KEY IS NULL THEN 1=1 ELSE WO_TURN.WORKORDER_KEY = WO_DETAIL.WORKORDER_KEY END)
LEFT JOIN Turnkey ON Turnkey.O_Turn_ID  =  WO_TURN.O_Turn_ID
GROUP BY WO_TURN.O_TURN_ID
)
SELECT
Turnkey.O_TURN_ID
,Turnkey.Property_key
,Turnkey.EntityID
,Turnkey.Address
,Turnkey.Region_Name
,Turnkey.ORGANIZATION_NAME
,Turnkey.Occupancy_Status
,Turnkey.SQUARE_FOOTAGE
,Turnkey.FloorPlan
,Turnkey.STRATEGY_NAME
,Turnkey.O_Current_Rent
,Turnkey.N_Initial_Rent
,Turnkey.N_Current_Rent
,Turnkey.O_Move_Out
,Turnkey.O_AnticipatedMoveOutDate
,Turnkey.N_MoveIn
,Turnkey.HC_TURN_REPORT_STATUS
,Turnkey.PASS_MINOR
,d_listing.LISTING_DATE AS N_Listing_Date
,f_listing.CURRENT_LIST_PRICE AS N_Listing_Price
,d_listing.listing_status AS N_Listing_Status
,TKT_CREATED_MIN
,TKT_CREATED_MAX
,TKT_Closed_Max
,TKT_WOS_OPEN
,TKT_WOS_CLOSED
,WO_STATUS
,CASE WHEN (TKT_WOS_OPEN IS NULL OR HC_TURN_REPORT_STATUS ='Pass') AND PASS_MINOR IS NULL
	THEN COALESCE(TKT_COST,0) ELSE TKT_COST END AS TKT_COST
,CASE WHEN (TKT_WOS_OPEN IS NULL OR HC_TURN_REPORT_STATUS ='Pass') AND (HC_TURN_COMPLETED_DATE IS NOT NULL OR N_LEASE_FROM_DATE IS NOT NULL OR TKT_Closed_Max IS NOT NULL)
      THEN LEAST(COALESCE(HC_TURN_COMPLETED_DATE, '12/31/9999'::date),COALESCE(N_LEASE_FROM_DATE, '12/31/9999'::date),COALESCE(TKT_Closed_Max, '12/31/9999'::date))
      ELSE NULL END AS TURN_COMPLETED
,CASE WHEN (TKT_WOS_OPEN IS NULL OR HC_TURN_REPORT_STATUS ='Pass') AND (HC_TURN_COMPLETED_DATE IS NOT NULL OR N_LEASE_FROM_DATE IS NOT NULL OR TKT_Closed_Max IS NOT NULL)
      THEN DATE_TRUNC('month',LEAST(COALESCE(HC_TURN_COMPLETED_DATE, '12/31/9999'::date),COALESCE(N_LEASE_FROM_DATE, '12/31/9999'::date),COALESCE(TKT_Closed_Max, '12/31/9999'::date)))::date
      ELSE NULL END AS TURN_COMPLETED_BOM
,CASE WHEN Turnkey.O_CURRENT_RENT > 0 AND COALESCE(Turnkey.N_INITIAL_RENT,Turnkey.N_CURRENT_RENT) >0
      THEN DIV0NULL(COALESCE(Turnkey.N_INITIAL_RENT,Turnkey.N_CURRENT_RENT), Turnkey.O_CURRENT_RENT) - 1
	  ELSE NULL END AS RENT_GROWTH
,CASE WHEN TKT_CREATED_MIN IS NOT NULL AND TKT_Closed_Max IS NOT NULL THEN DATEDIFF(DAY, TKT_CREATED_MIN, TKT_Closed_Max) ELSE NULL END AS "Days_TKT_Created_TKT_Closed"
,CASE WHEN Turnkey.O_Move_Out IS NOT NULL AND COALESCE(TKT_Closed_Max, HC_TURN_COMPLETED_DATE) IS NOT NULL THEN DATEDIFF(DAY, Turnkey.O_Move_Out, COALESCE(TKT_Closed_Max, HC_TURN_COMPLETED_DATE)) ELSE NULL END AS "Days_MO_TKT_Closed"
,CASE WHEN Turnkey.O_Move_Out IS NOT NULL AND N_MoveIn IS NOT NULL THEN DATEDIFF(DAY, Turnkey.O_Move_Out, N_MoveIn) ELSE NULL END AS "Days_MoveOut_MoveIn"
,CASE WHEN N_MoveIn IS NULL THEN COALESCE (DATEDIFF(DAY, COALESCE(Turnkey.O_Move_Out,O_AnticipatedMoveOutDate), GETDATE()) , 0) ELSE NULL END  AS "Days_ActiveInTurn"
,CASE WHEN N_MoveIn IS NULL AND d_listing.LISTING_DATE IS NOT NULL THEN 1 ELSE NULL END AS ON_MARKET_FLAG
,RANK () OVER( PARTITION BY Turnkey.Property_key ORDER BY f_listing.RENT_LIST_HIST_ID DESC) AS RECENT_TURN_RANK
,CASE WHEN Turnkey.MOVEOUTCOMPLETE = 'Yes' THEN COALESCE(MoveOutReceipts_PAID,0.001) + COALESCE(MoveOutReceipts_CONCESSION,0.001) ELSE NULL END AS MoveOutReceipts_Final
FROM Turnkey
LEFT JOIN Turn_Listings TL ON TL.O_Turn_ID = Turnkey.O_Turn_ID AND TL.Property_Key = Turnkey.Property_key
left join PROD_ANALYTICS.DBT_RESICAP.FCT_PROP_RENTAL_LISTING_HIST f_listing on TL.rent_list_hist_key = f_listing.RENT_LIST_HIST_ID
left join PROD_ANALYTICS.DBT_RESICAP.DIM_LISTING d_listing on f_listing.LISTING_KEY = d_listing.LISTING_KEY and d_listing.CURRENT_FLAG = 'Y'
LEFT JOIN TURN_WO_SUMMARY TWS ON TWS.O_Turn_ID = Turnkey.O_Turn_ID
LEFT JOIN MoveOutCharges MOC ON MOC.LeaseID = Turnkey.O_Turn_ID
LEFT JOIN MoveOutReceipts MOR ON MOR.LeaseID = Turnkey.O_Turn_ID
WHERE 1=1
`;
