// Working DBT-backed equivalents of the Power BI model's PM_BOM and
// PM_Listings_BOM datasets (provided by the data team). These reproduce the
// BOM occupancy snapshot and the BOM active-listings snapshot that back the
// Summary "Portfolio Metrics" BOM Vacant / BOM Listings measures. Kept verbatim
// (logic unchanged) so the numbers tie out to the report. Consumed as a
// subquery: `SELECT ... FROM (${PM_BOM_SQL}) WHERE BEG_OF_MONTH = '<bom>'`.

export const PM_BOM_SQL = `
WITH Calendar AS (
    SELECT DATEADD('month', SEQ4(), DATE_FROM_PARTS(2024, 1, 1)) AS BEG_OF_MONTH
    FROM TABLE(GENERATOR(ROWCOUNT => 10000))
    WHERE BEG_OF_MONTH <= DATE_TRUNC('month', CURRENT_DATE())
)
,Prop_Calendar AS (
  Select
   P.HBPM_PROPERTY_ID AS PropertyId
   ,P.PROPERTY_KEY AS PROP_KEY
   ,P.ENTITYID
   ,BEG_OF_MONTH
  FROM PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY  = P.PROPERTY_KEY
  LEFT JOIN PROD_REPLICA.HBAM_DBO.PROPERTIES HBAM ON HBAM.HBID = P.HBAM_PROPERTY_ID
  LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTIES HBPM ON HBPM.PROPERTYID = P.HBPM_PROPERTY_ID
  LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTYADDLINFOES PM_AI ON PM_AI.PROPERTYID  = HBPM.PROPERTYID AND PM_AI."_FIVETRAN_DELETED" = 'N'
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_OWNER_ORGANIZATION O ON O.ORGANIZATION_KEY = PUS.ORGANIZATION_KEY
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY = PUS.PROPERTY_UNIT_KEY
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY = PUS.PORTFOLIO_KEY
  CROSS JOIN Calendar
  WHERE 1=1
	AND (HBAM.PROPERTYSTATUSID >9 OR HBAM.PROPERTYSTATUSID IS NULL)
	AND P.PROPERTY_STATE ='Active'
	AND P.EntityID <> ''
	AND (HBAM.PROPERTYSTATUSID NOT IN (53,75) OR HBAM.PROPERTYSTATUSID IS NULL)
	AND PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54)
	AND PUS.Organization_KEY not IN (16,17)
	AND PO.IS_Active_AM = 'Y'
	AND PO.Current_Flag = 'Y'
	AND P.Current_Flag = 'Y'
	AND PU.Current_Flag = 'Y'
	AND PUS.Occupancy_Status NOT IN ('Not Managed')
	AND (HBPM.PROPERTYSTATEID = 26 OR HBPM.PROPERTYSTATEID IS NULL)
	AND P.HBMM_Property_ID IS NOT NULL )
,Prop_Hist AS (
  SELECT
   P.HBPM_PROPERTY_ID AS PropertyId
   ,P.PROPERTY_KEY  AS PROP_KEY
  ,FCT_PROP_UNIT_STATUS_HIST_KEY AS AuditLogId
  ,LM.LOOKUPMASTERID AS AfterValue
  ,NEW_OCCUPANCY_STATUS AS Occupancy_Status
  ,to_date(CHANGED_DATE_KEY::TEXT,'yyyymmdd') AS LogDateTime
  FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROP_UNIT_STATUS_HIST PSH
  LEFT JOIN PROD_REPLICA.HBPM_DBO.LOOKUPMASTERS LM ON LM.DESCRIPTION = PSH.NEW_OCCUPANCY_STATUS
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY = PSH.PROPERTY_KEY
  WHERE 1=1
    AND P.PROPERTY_STATE ='Active'
    AND P.EntityID <> ''
    AND P.Current_Flag = 'Y'
    AND P.HBMM_Property_ID IS NOT NULL
UNION ALL
Select
   P.HBPM_PROPERTY_ID AS PropertyId
   ,P.Property_key AS PROP_KEY
  ,1 As AuditLogId
  ,LM.LOOKUPMASTERID AS OccupancyStatusId
  ,PUS.OCCUPANCY_STATUS
  ,P.Created_Date AS LogDateTime
  FROM PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY  = P.PROPERTY_KEY
  LEFT JOIN PROD_REPLICA.HBAM_DBO.PROPERTIES HBAM ON HBAM.HBID = P.HBAM_PROPERTY_ID
  LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTIES HBPM ON HBPM.PROPERTYID = P.HBPM_PROPERTY_ID
  LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTYADDLINFOES PM_AI ON PM_AI.PROPERTYID  = HBPM.PROPERTYID AND PM_AI."_FIVETRAN_DELETED" = 'N'
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_OWNER_ORGANIZATION O ON O.ORGANIZATION_KEY = PUS.ORGANIZATION_KEY
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY = PUS.PROPERTY_UNIT_KEY
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY = PUS.PORTFOLIO_KEY
  LEFT JOIN PROD_REPLICA.HBPM_DBO.LOOKUPMASTERS LM ON LM.DESCRIPTION = PUS.OCCUPANCY_STATUS
  LEFT JOIN (Select DISTINCT Property_Key FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROP_UNIT_STATUS_HIST PSH) AL  ON AL.Property_key = P.Property_Key
  WHERE 1=1
	AND (HBAM.PROPERTYSTATUSID >9 OR HBAM.PROPERTYSTATUSID IS NULL)
	AND P.PROPERTY_STATE ='Active'
	AND P.EntityID <> ''
	AND (HBAM.PROPERTYSTATUSID NOT IN (53,75) OR HBAM.PROPERTYSTATUSID IS NULL)
	AND PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54)
	AND PUS.Organization_KEY not IN (16,17)
	AND PO.IS_Active_AM = 'Y'
	AND PO.Current_Flag = 'Y'
	AND P.Current_Flag = 'Y'
	AND PU.Current_Flag = 'Y'
	AND PUS.Occupancy_Status NOT IN ('Not Managed')
	AND (HBPM.PROPERTYSTATEID = 26 OR HBPM.PROPERTYSTATEID IS NULL)
	AND P.HBMM_Property_ID IS NOT NULL
    AND AL.Property_Key is not null )
,BOM_Status AS (
   Select
   MAX(Prop_Hist.AuditLogID) AuditLogID
   ,MAX(Prop_Hist_2.AuditLogID) AuditLogID_2
   ,Prop_Calendar.PropertyId
   ,Prop_Calendar.PROP_KEY
   ,Prop_Calendar.EntityId
   ,Prop_Calendar.BEG_OF_MONTH
   From Prop_Calendar
   LEFT JOIN Prop_Hist ON Prop_Hist.PropertyId = Prop_Calendar.PropertyId
   				     AND Prop_Hist.LogDateTime < DATEADD(day,1,Last_day(BEG_OF_MONTH))
   LEFT JOIN Prop_Hist AS Prop_Hist_2 ON Prop_Hist_2.PropertyId = Prop_Calendar.PropertyId
   				     AND Prop_Hist_2.LogDateTime < BEG_OF_MONTH
   GROUP BY
   Prop_Calendar.PropertyId
  ,Prop_Calendar.PROP_KEY
  ,Prop_Calendar.EntityId
   ,Prop_Calendar.BEG_OF_MONTH)
 Select
   BOM_Status.PropertyId AS HBPM_PropertyID
   ,BOM_Status.PROP_KEY
   ,BOM_Status.EntityId
   ,BOM_Status.BEG_OF_MONTH
   ,Prop_Hist.AfterValue
   ,Prop_Hist.Occupancy_Status
   ,Prop_Hist_2.AfterValue AS BEG_MONTH_VALUE
   ,Prop_Hist_2.Occupancy_Status AS BEG_MONTH_OCC_STATUS
   from BOM_Status
   LEFT JOIN Prop_Hist ON Prop_Hist.PropertyId = BOM_Status.PropertyId AND Prop_Hist.AuditLogId = BOM_Status.AuditLogID
   LEFT JOIN Prop_Hist Prop_Hist_2 ON Prop_Hist_2.PropertyId = BOM_Status.PropertyId AND Prop_Hist_2.AuditLogId = BOM_Status.AuditLogID_2
`;

export const PM_LISTINGS_BOM_SQL = `
WITH CALENDAR AS (
SELECT
CALENDAR_DATE
,DATE_TRUNC('month',CALENDAR_DATE) AS CALENDAR_DATE_BOM
,DAY_IN_MONTH
FROM PROD_ANALYTICS.DBT_RESICAP.DIM_CALENDAR
WHERE 1=1
AND CALENDAR_DATE >= '2024-01-01'
AND CALENDAR_DATE <= DATE_TRUNC('month',DATEADD('month',1,GETDATE()))
)
,Prop_Calendar AS (
  Select   P.PROPERTY_KEY
   ,P.HBPM_PROPERTY_ID AS PropertyId
   ,P.ENTITYID
   ,Calendar.CALENDAR_DATE
   ,Calendar.CALENDAR_DATE_BOM
   ,Calendar.DAY_IN_MONTH
  FROM PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY  = P.PROPERTY_KEY
  LEFT JOIN PROD_REPLICA.HBAM_DBO.PROPERTIES HBAM ON HBAM.HBID = P.HBAM_PROPERTY_ID
  LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTIES HBPM ON HBPM.PROPERTYID = P.HBPM_PROPERTY_ID
  LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTYADDLINFOES PM_AI ON PM_AI.PROPERTYID  = HBPM.PROPERTYID AND PM_AI."_FIVETRAN_DELETED" = 'N'
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_OWNER_ORGANIZATION O ON O.ORGANIZATION_KEY = PUS.ORGANIZATION_KEY
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY = PUS.PROPERTY_UNIT_KEY
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY = PUS.PORTFOLIO_KEY
  CROSS JOIN Calendar
WHERE 1=1
AND (HBAM.PROPERTYSTATUSID >9 OR HBAM.PROPERTYSTATUSID IS NULL)
AND P.PROPERTY_STATE ='Active'
AND P.EntityID <> ''
AND (HBAM.PROPERTYSTATUSID NOT IN (53,75) OR HBAM.PROPERTYSTATUSID IS NULL)
AND PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54)
AND PUS.Organization_KEY not IN (16,17)
AND PO.IS_Active_AM = 'Y'
AND PO.Current_Flag = 'Y'
AND P.Current_Flag = 'Y'
AND PU.Current_Flag = 'Y'
AND PUS.Occupancy_Status NOT IN ('Not Managed')
AND (HBPM.PROPERTYSTATEID = 26 OR HBPM.PROPERTYSTATEID IS NULL)
AND P.HBMM_Property_ID IS NOT NULL
AND P.Property_Key NOT IN (166418,57201,23237,166851)
)
,LIST_TEMP_PRE AS (
   Select
   MAX(CHANGED_DATE_TIME) LH_CHANGED_KEY
   ,LH.PROPERTY_LISTING_ID AS RENT_LIST_HIST_KEY
   ,RANK() OVER(PARTITION BY PC.PROPERTY_KEY, PC.CALENDAR_DATE ORDER BY LH.PROPERTY_LISTING_ID DESC) AS LIST_RANK
   ,PC.PROPERTY_KEY
   ,PC.PropertyId
   ,PC.ENTITYID
   ,PC.CALENDAR_DATE
   ,PC.CALENDAR_DATE_BOM
   ,PC.DAY_IN_MONTH
   From Prop_Calendar PC
   LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROP_LIST_STATUS_PRICE_HIST LH
   		ON LH.PROPERTY_KEY = PC.Property_Key
   		AND LH.CHANGED_DATE_TIME < CALENDAR_DATE
   		AND LH.INDEX_CHANGE_TYPE IN ('Status','New')
   GROUP BY
   PC.PROPERTY_KEY
   ,LH.PROPERTY_LISTING_ID
   ,PC.PropertyId
   ,PC.ENTITYID
   ,PC.CALENDAR_DATE
   ,PC.CALENDAR_DATE_BOM
   ,PC.DAY_IN_MONTH
   QUALIFY LIST_RANK =1
   )
,LIST_TEMP AS (
  Select
  LTP.*
  ,LH.FCT_PROP_LIST_STATUS_PRICE_HIST_KEY AS LH_KEY
  From LIST_TEMP_PRE LTP
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROP_LIST_STATUS_PRICE_HIST LH
        ON LH.PROPERTY_KEY = LTP.Property_Key
   		AND LH.CHANGED_DATE_TIME = LTP.LH_CHANGED_KEY
   		AND LH.INDEX_CHANGE_TYPE IN ('Status','New')
  )
,LISTINGS_BY_DAY AS (
   Select
    LIST_TEMP.PROPERTY_KEY
   ,LIST_TEMP.PropertyId
   ,LIST_TEMP.ENTITYID
   ,LIST_TEMP.CALENDAR_DATE
   ,LIST_TEMP.CALENDAR_DATE_BOM
   ,LIST_TEMP.DAY_IN_MONTH
   ,LH.PROPERTY_LISTING_ID
   ,LH.LISTING_STATUS
   ,CASE WHEN LH.LISTING_STATUS ='Active' AND LH.LISTING_STATE ='Active' AND LH.IS_PUBLISHED = 'Y'  THEN 1 ELSE NULL END AS ACTIVE_LISTING
   ,RLH.LEASING_AGENT
   from LIST_TEMP
   LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROP_LIST_STATUS_PRICE_HIST LH
   	ON LH.FCT_PROP_LIST_STATUS_PRICE_HIST_KEY = LIST_TEMP.LH_KEY
   LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROP_RENTAL_LISTING_HIST RLH ON RLH.RENT_LIST_HIST_ID = LH.PROPERTY_LISTING_ID
)
   Select *
   from LISTINGS_BY_DAY
  WHERE 1=1
  AND ACTIVE_LISTING = 1
  AND DAY_IN_MONTH  = 1
`;
