/* =============================================================================
   TURNS DATASET
   -----------------------------------------------------------------------------
   Grain:   One row per turn (anchored on Turnkey.O_Turn_ID), combining tenant
            move-out/move-in pairing, HappyCo scope & QC inspections, turn work
            orders, listings, and move-out charge/receipt reconciliation.
   Anchor:  Turnkey CTE (built from TENANT self-join old->new lease).
   Large CTE chain: CollectionsNote, PICS, CLEAN_ITEM/UNIT/INSPECTION,
            HAPPY_CO_DETAIL/SCOPE/QC, RESIWALK_INS/ANSWER_AGG/SCOPE/QC, UW_RENT,
            HHI, DEALS, TENANT, HAPPY_CO_TURN, Turnkey, Turn_Listings, MoveOut*,
            BadDebt, WO_DETAIL, WO_TURN, TURN_WO_SUMMARY -> final SELECT.

   CLEANUP NOTES:
     [SYNC]  ORGANIZATION_KEY / ORGANIZATION_NAME CASE blocks in DEALS, TENANT,
             Turnkey, and WO_DETAIL updated from the prior two-group form
             (-1.. -> 'RP SFR', 27.. -> 'RB DRC') to the full six-group roll-up
             that mirrors the master PROPERTY script (source of truth).
             DELIBERATE OUTPUT CHANGE limited to the organization columns.
     No CTEs or joins dropped: every CTE feeds the final result (directly or via
     Turnkey / WO_TURN / TURN_WO_SUMMARY). The commented-out legacy HHI HubSpot
     block and the commented-out RESI_TSUM join are preserved exactly as found.

   [RESIWALK ADD] HAPPY_CO_SCOPE and HAPPY_CO_QC now UNION ALL in ResiWalk
     (HubSpot-native) inspections so Turn data uses BOTH sources:
        - RESIWALK_SCOPE: template pm_scope_rate_card -> '(PM) Scope Inspection'
        - RESIWALK_QC:    template pm_turn_reinspect_qc -> '(PM) Turn Inspection'
     Property link: INSPECTION.PROPERTY_ENTITY_ID -> DIM_PROPERTY.ENTITYID (1:1).
     Status filter: ResiWalk native lowercase 'completed'.
     ISSUE_COUNT mapped from rate_card_line answer count (each scoped line = an
     identified deficiency), mirroring HappyCo's HC_*_ISSUE_COUNT.
     HC_SCOPE_REPORT_STATUS has no ResiWalk analog -> NULL.
     HC_TURN_REPORT_STATUS read from the inspection-object result field
     (inspection_result) and standardized to the HappyCo vocabulary:
        'pass' -> 'Pass', 'fail' -> 'Fail', anything else/blank -> NULL.
     The result column is referenced dynamically via GET(OBJECT_CONSTRUCT(HI.*),..)
     so the query COMPILES before Fivetran adds the column to the replica (no
     completed Turn/QC inspections have populated it yet); it resolves to NULL
     today and maps live Pass/Fail values automatically once the field syncs.
     As of build: 12 completed Scope inspections (live), 0 completed Turn/QC
     inspections (QC leg is forward-compatible plumbing, 0 rows today).
   ============================================================================= */

WITH CollectionsNote AS (
		SELECT DISTINCT 
	 	N.NOTEID AS LatestNoteID
	 	,N.NOTETEXT AS CollectionNote
	 	,N.CREATEDDATE  AS CollectionNoteCreated
	 	,DATEDIFF('Day',N.CREATEDDATE,GETDATE()) CollectionNote_Days
	    ,P.PropertyId
	    ,TI.UserID
	    ,U.FIRSTNAME || ' ' || U.LASTNAME AS CollectionNote_Added_By
	    ,RANK() OVER( PARTITION BY TI.UserID ORDER BY N.CREATEDDATE DESC) AS Recent_Rank
	
		FROM PROD_REPLICA.HBPM_DBO.NOTES N 
		LEFT JOIN PROD_REPLICA.HBPM_DBO.NOTETYPES NT ON NT.Id = N.NoteTypeId
		LEFT JOIN PROD_REPLICA.HBPM_DBO.LOOKUPMASTERS LM ON LM.LookUpMasterId = N.ObjectTypeId
		LEFT JOIN PROD_REPLICA.HBPM_DBO.TENANTINFORMATIONS TI ON TI.UserID = N.ObjectId AND N.ObjectTypeId = 502 AND TI."_FIVETRAN_DELETED" = 'N'
		LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTYADDLINFOES PAI ON PAI.UnitId = TI.UnitId AND PAI."_FIVETRAN_DELETED" ='N'
		LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTIES P ON P.PropertyID = COALESCE(PAI.PropertyId, N.ObjectID) AND P."_FIVETRAN_DELETED" ='N'
		LEFT JOIN PROD_REPLICA.HBPM_DBO.USERS U ON U.USERID  = N.ADDEDBY 
	 	WHERE N.NoteTypeId = 3
	 --	AND PAI.PROPERTYID = 36301
	 	QUALIFY Recent_Rank = 1)

--****************************************************************************
,PICS AS (
 SELECT
  MAX(PHOTO_COUNT) AS Picture_Count
  ,TRY_TO_NUMERIC(UNIT_) AS PM_PropertyID
  FROM "PROD_REPLICA"."RENTLY"."_3_0_DATA"
  WHERE 1=1
  AND TRY_TO_NUMERIC(UNIT_) IS NOT NULL
  GROUP BY UNIT_
)

--****************************************************************************

,CLEAN_ITEM AS (

SELECT 
  ITEM._MODIFIED
 ,ITEM.ID AS ITEM_ID
 ,ITEM.SECTION AS  ITEM_Section
 ,ITEM.ITEM  AS ITEM_Item
 ,ITEM.RATINGS AS  ITEM_Ratings
 ,ITEM.NOTES  AS  ITEM_Notes
 ,ITEM.INSPECTION_ID
 ,RANK() OVER( PARTITION BY ITEM.INSPECTION_ID ORDER BY DATE_TRUNC('min',_FIVETRAN_SYNCED)  DESC) UPDATE_RANK
 ,RANK() OVER( PARTITION BY ITEM_SECTION, ITEM_ITEM, ITEM.INSPECTION_ID ORDER BY DATE_TRUNC('min',_MODIFIED)  DESC) RECENT_RANK
FROM PROD_REPLICA.HAPPYCO_NEW.ITEM_2025 ITEM
)
--AND ITEM_SECTION = 'Report Status' )


,CLEAN_UNIT_PRE AS (
 SELECT 
   UNIT._MODIFIED
  ,UNIT.ID AS UNIT_ID
  ,UNIT.EXTERNAL_ID AS UNIT_EXTERNAL_ID 
  ,UNIT.ADDRESS AS UNIT_ADDRESS
  ,UNIT.LINE_1 AS UNIT_LINE_1
  ,RANK() OVER( PARTITION BY ID ORDER BY DATE_TRUNC('min',_MODIFIED) DESC) RECENT_RANK
FROM PROD_REPLICA.HAPPY_CO.UNIT)

,CLEAN_UNIT AS (
 SELECT DISTINCT
  CLEAN_UNIT_PRE.*
  ,COALESCE (P1.PROPERTY_KEY,P2.PROPERTY_KEY,P3.PROPERTY_KEY,P4.PROPERTY_KEY ) AS PROPERTY_KEY
  ,P1.PROPERTY_KEY P1
  ,P2.PROPERTY_KEY P2
  ,P3.PROPERTY_KEY P3
  ,P4.PROPERTY_KEY  P4
 FROM CLEAN_UNIT_PRE
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P1 ON TO_CHAR(P1.HBAM_PROPERTY_ID) = CLEAN_UNIT_PRE.UNIT_EXTERNAL_ID AND P1.CURRENT_FLAG = 'Y' AND P1.PROPERTY_STATE = 'Active' AND P1.PROPERTY_STATUS <> 'Property Sold'
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P2 ON  P2.ENTITYID = CLEAN_UNIT_PRE.UNIT_EXTERNAL_ID  AND P2.CURRENT_FLAG = 'Y' AND P2.PROPERTY_STATE = 'Active' AND P2.PROPERTY_STATUS <> 'Property Sold'
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P3 ON  INITCAP(TRIM(P3.ADDRESS))  = INITCAP(TRIM(CLEAN_UNIT_PRE.UNIT_LINE_1))  AND P3.CURRENT_FLAG = 'Y' AND P3.PROPERTY_STATE = 'Active' AND P3.PROPERTY_STATUS <> 'Property Sold'
  LEFT JOIN (SELECT LEFT(INITCAP(TRIM(ADDRESS)),9) ADD_TRIM, MAX(PROPERTY_KEY) PROPERTY_KEY
             FROM PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY
             WHERE CURRENT_FLAG = 'Y' AND PROPERTY_STATE = 'Active' AND PROPERTY_STATUS <> 'Property Sold'
             GROUP BY LEFT(INITCAP(TRIM(ADDRESS)),9) ) P4
  	         ON  ADD_TRIM  = LEFT(INITCAP(TRIM(COALESCE(CLEAN_UNIT_PRE.UNIT_LINE_1,UNIT_ADDRESS))),9) 

  WHERE CLEAN_UNIT_PRE.RECENT_RANK = 1)
 
 
,CLEAN_INPSECTION AS (
 SELECT
  INS._MODIFIED
  ,INS._LINE
 ,INS.INSPECTION_ID
 ,INS.INSPECTION_INSPECTOR_NAME
 ,INS.INSPECTION_COMPLETED_DATE
 ,INS.INSPECTION_STATUS
 ,CASE WHEN INS.INSPECTION_TEMPLATE = '(QC) Turn RRQC Inspection' THEN '(QC) Turn Inspection'
      ELSE  INS.INSPECTION_TEMPLATE END AS INSPECTION_TEMPLATE
 ,INS.INSPECTION_LINK
 ,INS.UNIT_ID
 ,RANK() OVER( PARTITION BY INS.INSPECTION_ID ORDER BY DATE_TRUNC('min',_MODIFIED) DESC) RECENT_RANK
FROM PROD_REPLICA.HAPPY_CO.INSPECTION INS
WHERE INSPECTION_ID NOT IN ('wAS8twd-A-rGt','Qqzpo2d-A-3c2')
)
------------------------------------------------

,HAPPY_CO_DETAIL AS (
SELECT DISTINCT 

 CLEAN_UNIT.PROPERTY_KEY
,CLEAN_UNIT.UNIT_ID
,CLEAN_UNIT.UNIT_EXTERNAL_ID
,CLEAN_UNIT.UNIT_Address
,CLEAN_UNIT.UNIT_LINE_1
,RANK() OVER(PARTITION BY CLEAN_UNIT.PROPERTY_KEY, CLEAN_INPSECTION.INSPECTION_TEMPLATE ORDER BY CLEAN_INPSECTION.INSPECTION_COMPLETED_DATE DESC, CLEAN_INPSECTION.INSPECTION_ID DESC) RECENT_INS_RANK
,CLEAN_INPSECTION.INSPECTION_ID
,CLEAN_INPSECTION.INSPECTION_INSPECTOR_NAME
,CLEAN_INPSECTION._LINE
,CLEAN_INPSECTION.INSPECTION_COMPLETED_DATE
,CLEAN_INPSECTION.INSPECTION_STATUS
,CLEAN_INPSECTION.INSPECTION_TEMPLATE
,CLEAN_INPSECTION.INSPECTION_LINK
,CLEAN_ITEM.ITEM_Section
,CLEAN_ITEM.ITEM_Item
,CLEAN_ITEM.ITEM_Ratings
,CLEAN_ITEM.ITEM_Notes
,CASE WHEN CLEAN_ITEM.ITEM_Section = 'Report Status' AND CLEAN_ITEM.ITEM_ITEM = 'Pass/Fail' THEN 1 ELSE 0 END AS Report_Status
,CASE WHEN CLEAN_ITEM.ITEM_ITEM = 'Deficiencies corrected from Scope' THEN 1 ELSE 0 END AS TURN_LINE
,CASE WHEN CLEAN_ITEM.ITEM_Section = 'Pre Leasing Status' THEN 1 ELSE 0 END AS PreLease_Status

FROM CLEAN_INPSECTION 
LEFT JOIN CLEAN_ITEM ON CLEAN_ITEM.INSPECTION_ID = CLEAN_INPSECTION.INSPECTION_ID AND CLEAN_ITEM.RECENT_RANK = 1 AND CLEAN_ITEM.UPDATE_RANK = 1 
LEFT JOIN CLEAN_UNIT ON CLEAN_UNIT.UNIT_ID = CLEAN_INPSECTION.UNIT_ID AND CLEAN_UNIT.RECENT_RANK = 1

WHERE 1=1
AND CLEAN_INPSECTION.RECENT_RANK = 1 
AND CLEAN_INPSECTION.INSPECTION_STATUS = 'Complete'
--AND CLEAN_INPSECTION.INSPECTION_TEMPLATE LIKE '%(QC)%'
--AND CLEAN_INPSECTION.INSPECTION_TEMPLATE NOT LIKE '%(PM)%') OR CLEAN_INPSECTION.INSPECTION_TEMPLATE = '(PM) Pre Move-Out')
--AND CLEAN_INPSECTION.INSPECTION_TEMPLATE LIKE '%(PM) (QC) - Vacancy & Security Check%'
AND CLEAN_ITEM.ITEM_SECTION IS NOT NULL
)

--SELECT * FROM HAPPY_CO_DETAIL
--WHERE Property_key = 46390

-----------------------------------------------------------------------------------------------
-- [RESIWALK ADD] ResiWalk (HubSpot-native) inspection rows, header-level.
-- PROPERTY_ENTITY_ID -> DIM_PROPERTY.ENTITYID (clean 1:1). inspection_result
-- read dynamically (column not yet in replica) and standardized to HappyCo
-- Pass/Fail vocabulary.
,RESIWALK_INS AS (
 SELECT
  HI.ID AS INSPECTION_ID
 ,P.PROPERTY_KEY
 ,COALESCE(HI.PROPERTY_LINK_MASTER, HI.PROPERTY_PDF_MASTER_URL) AS INSPECTION_LINK
 ,HI.PROPERTY_COMPLETED_AT::DATE AS INSPECTION_COMPLETED_DATE
 ,HI.PROPERTY_TEMPLATE_TYPE
 -- Standardize ResiWalk inspection_result ('pass'/'fail') to the HappyCo
 -- HC_TURN_REPORT_STATUS vocabulary ('Pass'/'Fail'), which drives the downstream
 -- PASS_MINOR + TKT_*_Fail logic. Dynamic GET() reference so the query compiles
 -- before Fivetran adds the column to the replica (no completed Turn/QC inspections
 -- have populated it yet); resolves to NULL today, maps live values once it syncs.
 ,CASE LOWER(TRIM(GET(OBJECT_CONSTRUCT(HI.*), 'PROPERTY_INSPECTION_RESULT')::TEXT))
    WHEN 'pass' THEN 'Pass'
    WHEN 'fail' THEN 'Fail'
    ELSE NULL
  END AS INSPECTION_RESULT_STD
 FROM PROD_REPLICA.HUBSPOT_2.INSPECTION HI
 LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.ENTITYID = HI.PROPERTY_ENTITY_ID AND P.CURRENT_FLAG = 'Y'
 WHERE (HI._FIVETRAN_DELETED = FALSE OR HI._FIVETRAN_DELETED IS NULL)
 AND HI.PROPERTY_TEMPLATE_TYPE IN ('pm_scope_rate_card','pm_turn_reinspect_qc')
 AND LOWER(HI.PROPERTY_STATUS) = 'completed'
 AND P.PROPERTY_KEY IS NOT NULL
)

,RESIWALK_ANSWER_AGG AS (
 SELECT
  ATI.TO_ID AS INSPECTION_ID
 ,COUNT(CASE WHEN A.PROPERTY_ANSWER_TYPE = 'rate_card_line' THEN 1 END) AS RATE_CARD_LINE_COUNT
 FROM PROD_REPLICA.HUBSPOT_2.INSPECTION_ANSWER_TO_INSPECTION ATI
 JOIN PROD_REPLICA.HUBSPOT_2.INSPECTION_ANSWER A ON A.ID = ATI.FROM_ID
   AND (A._FIVETRAN_DELETED = FALSE OR A._FIVETRAN_DELETED IS NULL)
 GROUP BY ATI.TO_ID
)

-- Mirrors HAPPY_CO_SCOPE output columns exactly (for UNION ALL below).
,RESIWALK_SCOPE AS (
 SELECT
  R.PROPERTY_KEY
 ,R.INSPECTION_LINK AS HC_SCOPE_INSPECTION_LINK
 ,R.INSPECTION_COMPLETED_DATE AS HC_SCOPE_COMPLETED_DATE
 ,CAST(NULL AS TEXT) AS HC_SCOPE_REPORT_STATUS
 ,AGG.RATE_CARD_LINE_COUNT AS HC_SCOPE_ISSUE_COUNT
 ,RANK() OVER( PARTITION BY R.PROPERTY_KEY, R.INSPECTION_COMPLETED_DATE ORDER BY R.INSPECTION_LINK DESC) AS Recent_Rank
 FROM RESIWALK_INS R
 LEFT JOIN RESIWALK_ANSWER_AGG AGG ON AGG.INSPECTION_ID = R.INSPECTION_ID
 WHERE R.PROPERTY_TEMPLATE_TYPE = 'pm_scope_rate_card'
)

-- Mirrors HAPPY_CO_QC output columns exactly (for UNION ALL below).
,RESIWALK_QC AS (
 SELECT
  R.PROPERTY_KEY
 ,R.INSPECTION_LINK AS HC_TURN_INSPECTION_LINK
 ,R.INSPECTION_COMPLETED_DATE AS HC_TURN_COMPLETED_DATE
 ,R.INSPECTION_RESULT_STD AS HC_TURN_REPORT_STATUS
 ,AGG.RATE_CARD_LINE_COUNT AS HC_TURN_ISSUE_COUNT
 ,RANK() OVER( PARTITION BY R.PROPERTY_KEY, R.INSPECTION_COMPLETED_DATE ORDER BY R.INSPECTION_LINK DESC) AS Recent_Rank
 FROM RESIWALK_INS R
 LEFT JOIN RESIWALK_ANSWER_AGG AGG ON AGG.INSPECTION_ID = R.INSPECTION_ID
 WHERE R.PROPERTY_TEMPLATE_TYPE = 'pm_turn_reinspect_qc'
)

-----------------------------------------------------------------------------------------------
,HAPPY_CO_SCOPE AS (

SELECT 
 HCD.PROPERTY_KEY
,HCD.INSPECTION_LINK AS HC_SCOPE_INSPECTION_LINK
,HCD.INSPECTION_COMPLETED_DATE AS  HC_SCOPE_COMPLETED_DATE
,MAX(CASE WHEN Report_Status = 1 THEN ITEM_Ratings ELSE NULL END) AS HC_SCOPE_REPORT_STATUS
,SUM(CASE WHEN ITEM_Ratings = 'Issue' THEN 1 ELSE NULL END) AS HC_SCOPE_ISSUE_COUNT
,RANK() OVER( PARTITION BY HCD.PROPERTY_KEY, HCD.INSPECTION_COMPLETED_DATE ORDER BY HC_SCOPE_INSPECTION_LINK DESC) AS Recent_Rank

FROM HAPPY_CO_DETAIL HCD
WHERE 1=1
--AND HCD.RECENT_INS_RANK = 1
AND ITEM_SECTION <> 'Locks'
--AND HCD.INSPECTION_TEMPLATE IN ('(QC) Scope Inspection','(PM) Scope Inspection','(PM) Squatter Scope')
AND HCD.INSPECTION_TEMPLATE IN ('(QC) Scope Inspection','(PM) Scope Inspection','(PM) Scope Inspection (BI FIX ONLY)','(PM) Squatter Scope')
--AND HCD.Property_key =234243

GROUP BY
 HCD.PROPERTY_KEY
,HCD.INSPECTION_LINK
,HCD.INSPECTION_COMPLETED_DATE
--QUALIFY Recent_Rank = 1

UNION ALL

SELECT
 PROPERTY_KEY
,HC_SCOPE_INSPECTION_LINK
,HC_SCOPE_COMPLETED_DATE
,HC_SCOPE_REPORT_STATUS
,HC_SCOPE_ISSUE_COUNT
,Recent_Rank
FROM RESIWALK_SCOPE

)
-----------------------------------------------------------------------------------------------
,HAPPY_CO_QC AS (

SELECT 
 HCD.PROPERTY_KEY
,HCD.INSPECTION_LINK AS HC_TURN_INSPECTION_LINK
,HCD.INSPECTION_COMPLETED_DATE  AS  HC_TURN_COMPLETED_DATE
,MAX(CASE WHEN Report_Status = 1  THEN ITEM_Ratings ELSE NULL END) AS HC_TURN_REPORT_STATUS
,SUM(CASE WHEN CONTAINS(ITEM_Ratings,'No') AND TURN_LINE = 1 THEN 1 ELSE NULL END) AS HC_TURN_ISSUE_COUNT
,RANK() OVER( PARTITION BY HCD.PROPERTY_KEY, HCD.INSPECTION_COMPLETED_DATE ORDER BY HCD.INSPECTION_LINK DESC) AS Recent_Rank

FROM HAPPY_CO_DETAIL HCD
WHERE 1=1
--AND HCD.RECENT_INS_RANK = 1
AND ITEM_SECTION <> 'Locks'
AND (HCD.INSPECTION_TEMPLATE LIKE '(QC) Turn Inspection%'
    OR HCD.INSPECTION_TEMPLATE LIKE '(PM) Turn Inspection%')
--AND HCD.Property_key =251448
    
GROUP BY
 HCD.PROPERTY_KEY
,HCD.INSPECTION_LINK
,HCD.INSPECTION_COMPLETED_DATE
--QUALIFY Recent_Rank = 1

UNION ALL

SELECT
 PROPERTY_KEY
,HC_TURN_INSPECTION_LINK
,HC_TURN_COMPLETED_DATE
,HC_TURN_REPORT_STATUS
,HC_TURN_ISSUE_COUNT
,Recent_Rank
FROM RESIWALK_QC

)


-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
,UW_RENT_MAX AS (
	SELECT 
	MAX(RENTLOGID) RENTLOGID 
	, ENTITYID1
	FROM PROD_REPLICA.HBPM_DBO.RENTLOGS
	GROUP BY ENTITYID1) 
	
,UW_RENT AS (
	SELECT 
	 RentLogs.ENTITYID1 AS HBPM_UnitID
	,RentLogs.ORIGINALVALUE AS UW_Rent_Prior
	,RentLogs.UPDATEVALUE AS UW_Rent_Current
	,RentLogs.OCCUREDON  AS UW_Update_Date
	FROM UW_RENT_MAX
	LEFT JOIN PROD_REPLICA.HBPM_DBO.RENTLOGS RentLogs ON RentLogs.RENTLOGID = UW_RENT_MAX.RentLogID)

-----------------------------------------------------------------------------------------------
,HHI AS (
/*Select 

D.Deal_ID 
,CASE WHEN sum(C_INC.Annual_Income) <30000 THEN NULL 
	  WHEN  sum(C_INC.Annual_Income) > 1000000 THEN NULL 
	  ELSE  sum(C_INC.Annual_Income) END AS HHI

FROM PROD_REPLICA.HUBSPOT.DEAL D
LEFT JOIN PROD_REPLICA.HUBSPOT.DEAL_CONTACT DC ON DC.DEAL_ID = D.DEAL_ID
LEFT JOIN (SELECT
				CONTACT_ID
				,COALESCE (
					SUM(CASE WHEN NAME = 'total_yearly_income' THEN value ELSE null END),
					SUM(CASE WHEN NAME = 'annual_salary' THEN value ELSE null END)) AS Annual_Income
				FROM PROD_REPLICA.HUBSPOT.COntact_PROPERTY_HISTORY
				
				WHERE 1=1 
				AND NAME IN ('annual_salary','total_yearly_income')
				GROUP BY CONTACT_ID ) C_INC ON C_INC.Contact_ID = DC.Contact_ID
				
WHERE 1=1 
GROUP BY D.DEAL_ID*/

SELECT dd.DEAL_KEY 
,CASE 
	WHEN dl.TOTAL_YEARLY_INCOME <30000 THEN NULL  
	WHEN dl.TOTAL_YEARLY_INCOME > 1000000 THEN NULL 
	ELSE dl.TOTAL_YEARLY_INCOME
END AS HHI
FROM PROD_ANALYTICS.DBT_RESICAP.FCT_DEAL_STATUS_ACCUM f_deal
JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_DEAL dd 
	ON f_deal.DEAL_KEY = dd.DEAL_KEY 
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_LEAD dl 
	ON f_deal.LEAD_KEY = dl.LEAD_KEY 
)

---***********************************************************************************************************************
,DEALS AS (SELECT 

P.PROPERTY_KEY
,CASE
        WHEN P.ORGANIZATION_KEY IN (-1,18,26,28,48)                   THEN -1
        WHEN P.ORGANIZATION_KEY IN (27,50,51,52,54,45,55,53,56,57,66) THEN 27
        WHEN P.ORGANIZATION_KEY IN (58,59)                            THEN 58
        WHEN P.ORGANIZATION_KEY IN (62,63,64,65,68,69)                THEN 62
        WHEN P.ORGANIZATION_KEY IN (61,70)                            THEN 61
        WHEN P.ORGANIZATION_KEY IN (67)                               THEN 67
        ELSE P.ORGANIZATION_KEY
     END AS ORGANIZATION_KEY
,CASE
        WHEN P.ORGANIZATION_KEY IN (-1,18,26,28,48)                   THEN 'RP SFR'
        WHEN P.ORGANIZATION_KEY IN (27,50,51,52,54,45,55,53,56,57,66) THEN 'RB DRC'
        WHEN P.ORGANIZATION_KEY IN (58,59)                            THEN 'Hudson Oak'
        WHEN P.ORGANIZATION_KEY IN (62,63,64,65,68,69)                THEN 'Rocklyn Homes'
        WHEN P.ORGANIZATION_KEY IN (61,70)                            THEN 'ROI Property Group'
        WHEN P.ORGANIZATION_KEY IN (67)                               THEN 'Newstar'
        ELSE O.ORGANIZATION_NAME
     END AS ORGANIZATION_NAME
,P.HBPM_PROPERTY_ID 
,P.EntityID
,P.Address
,PUS.Under_written_rent

,REC.RECEIEVABLE_ID
,PO.PORTFOLIO_NAME
,R.REGION_NAME

,D.SECURITY_DEPOSIT_ID
,D.DEAL_KEY
,D.DEAL_ID
,COALESCE(D.CURRENT_DEAL_STATUS,HUB_DEAL.DEAL_STAGE) AS CURRENT_DEAL_STATUS
,HUB_DEAL.APP_ID
,HUB_DEAL.APP_STAGE AS APP_STAGE

,D.COMBINED_INCOME * 12  AS COMBINED_INCOME
,DSH.LEAD_KEY
,D.APPLICATION_SUBMITTED_DATE::date AS Application_Submit_Date
,date_trunc('month',D.APPLICATION_SUBMITTED_DATE::date) as "App Submit (BOM)"
,CONVERT_TIMEZONE('EST', APPLICATION_STARTED_DATE::date) AS Application_Started_Date
,date_trunc('month',CONVERT_TIMEZONE('EST', APPLICATION_STARTED_DATE )::date) as App_Started_BOM

,DATEDIFF(DAY, COALESCE(D.APPLICATION_SUBMITTED_DATE ,to_date(L.Application_SUBMIT_Date_KEY::TEXT,'yyyymmdd'),to_date(DSH.DEAL_CREATE_DATE_KEY::TEXT,'yyyymmdd')),GETDATE())  AS DAYS_SINCE_APP_SUBMIT

,L.First_Name ||  ' '  || L.Last_Name AS Lead_Name
,L.PRIMARY_LEAD_ID
,D.EMail
,L.PHONE
,to_date(L.CREATED_DATE_KEY::TEXT,'yyyymmdd') AS Lead_Created_Date
,DATE_TRUNC('month', to_date(L.CREATED_DATE_KEY::TEXT,'yyyymmdd') ) AS "1_Lead (BOM)"

,to_date(DSH.DEAL_CREATE_DATE_KEY::TEXT,'yyyymmdd') AS DEAL_CREATE_DATE
,to_date(DSH.APPLICATION_APPROVED_DATE_KEY::TEXT,'yyyymmdd') AS APPLICATION_APPROVED_DATE
,to_date(DSH.DEAL_WON_DATE_KEY::TEXT,'yyyymmdd') AS DEAL_WON_DATE
,COALESCE(HUB_DEAL.PROPERTY_HOLDING_FEE_TRANSACTION_DATE,to_date(PAY.HOLDING_FEE_DATE_NEW::TEXT,'yyyymmdd'),to_date(DSH.HOLDING_FEE_PAID_DATE_KEY::TEXT,'yyyymmdd')) AS HOLDING_FEE_DATE_NEW
,to_date(DSH.LEASE_SIGNED_DATE_KEY::TEXT,'yyyymmdd') AS LEASE_SIGNED_DATE
,to_date(DSH.CONVERT_TO_RESIDENT_DATE_KEY::TEXT,'yyyymmdd') AS CONVERT_TO_RESIDENT_DATE
,to_date(DSH.EXPECTED_MOVE_IN_DATE_KEY::TEXT,'yyyymmdd') AS EXPECTED_MOVE_IN_DATE
,COALESCE(to_date(DSH.LEASE_START_DATE_KEY::TEXT,'yyyymmdd'),
		  to_date(DSH.EXPECTED_MOVE_IN_DATE_KEY::TEXT,'yyyymmdd') ) AS LEASE_START_DATE
,to_date(DSH.LEASE_END_DATE_KEY::TEXT,'yyyymmdd') AS LEASE_END_DATE
,U.USER_KEY
,TLA.Tenant_key
,COALESCE(to_date(TLA.INITIAL_LEASE_FROM_DATE_KEY::TEXT,'yyyymmdd'),
		  to_date(TLA.LEASE_FROM_DATE_KEY::TEXT,'yyyymmdd') ) AS TENANT_MOVE_IN

,D.DEAL_OWNER AS DEAL_OWNER
,L.CONTACT_OWNER
,D.AVERAGE_CREDIT_SCORE

,L.SOURCE
,'https://app.hubspot.com/contacts/22536354/contact/' || L.LEAD_ID AS URL_HUBSPOT
,CASE WHEN DSH.CONVERT_TO_RESIDENT_DATE_KEY IS NOT NULL THEN 'Net HF' ELSE COALESCE(PAY.REFUNDED_FLAG, 'Net HF') END AS REFUNDED_FLAG 

,PM_AI.MOVEINREADY AS PM_MIR
,AM_CONS.PROJECTEDCOMPLETIONDATE	
,DATEADD(DAY,7,AM_CONS.PROJECTEDCOMPLETIONDATE) PCD_PLUS_SEVEN		
,DSH.LISTING_KEY

 ,HUB_DEAL.PROPERTY_LEASE_DRAFTING_STATUS AS LEASE_DRAFTING_STATUS
 ,HUB_DEAL.PROPERTY_MOVE_IN_FEE_PAYMENT_LINK AS MOVE_IN_FEE_PAYMENT_LINK
 ,HUB_DEAL.PROPERTY_MOVE_IN_CHARGES_PAID AS MOVE_IN_CHARGES_PAID
 ,HUB_DEAL.PROPERTY_DF_REFERENCE_NUMBER AS MOVE_IN_CHARGES_REFERENCE_ID

FROM PROD_ANALYTICS.DBT_RESICAP.DIM_DEAL D
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_DEAL_STATUS_ACCUM DSH ON DSH.DEAL_KEY  = D.Deal_Key
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_LEAD L ON L.LEAD_KEY = DSH.Lead_Key

LEFT JOIN (SELECT
				Deal_ID 
				,Value AS RECEIEVABLE_ID
				FROM PROD_REPLICA.HUBSPOT.DEAL_PROPERTY_HISTORY
				
				WHERE 1=1
				--AND DEAL_ID =8496423848
				AND NAME = 'account_receivable'
				AND _FIVETRAN_ACTIVE = 'Y') REC ON REC.DEAL_ID = D.DEAL_ID	
				
LEFT JOIN (SELECT Charge_DATE_KEY, Property_Key, Receivable_ID, Amount 
			FROM PROD_ANALYTICS.DBT_RESICAP.FCT_LEASING_TRANSACTION
			WHERE 
			TRANSACTION_TYPE = 'Charges' 
			--AND IS_REVERSED = 'N' 
			AND Amount >= 500 
			AND GL_ACCOUNT_KEY IN (18)
			) CHG ON CHG.Receivable_ID = TRY_CAST(REC.RECEIEVABLE_ID AS INTEGER)

LEFT JOIN (SELECT

			LT.PROPERTY_KEY
			,MIN(LT.RECEIVED_ON_DATE_KEY) AS HOLDING_FEE_DATE_NEW
			,REFUND.REFUNDED_FLAG
			,MIN(LT.PAID_BY_USER_KEY) AS PAID_BY_USER_KEY 
		    ,LT.RECEIVABLE_ID
		    ,LT.TENANT_KEY
			,LT.AMOUNT
			FROM PROD_ANALYTICS.DBT_RESICAP.FCT_LEASING_TRANSACTION LT
			LEFT JOIN 	
				(SELECT
				 'Refunded' AS REFUNDED_FLAG 
				,PROPERTY_KEY
				,PAID_BY_USER_KEY
				,AMOUNT FROM PROD_ANALYTICS.DBT_RESICAP.FCT_LEASING_TRANSACTION
					WHERE 1=1 
					AND TRANSACTION_TYPE = 'Payment' ) REFUND ON REFUND.PROPERTY_KEY = LT.PROPERTY_KEY 
																AND REFUND.PAID_BY_USER_KEY = LT.PAID_BY_USER_KEY
																AND REFUND.AMOUNT = (LT.AMOUNT*-1)
			WHERE 1=1
			AND LT.TRANSACTION_TYPE = 'Payment' 
			AND LT.Amount >= 500
			AND LT.GL_ACCOUNT_KEY IN (18,-1) -- SD
			AND LT.RECEIVABLE_ID =1739849
		--	AND LT.PAID_BY_USER_KEY = 1663341
			GROUP BY
			 LT.PROPERTY_KEY
			,LT.RECEIVABLE_ID
			,LT.TENANT_KEY	
			,LT.AMOUNT
            ,REFUND.REFUNDED_FLAG
            ) PAY ON PAY.Receivable_ID = TRY_CAST(REC.RECEIEVABLE_ID AS INTEGER) AND PAY.Amount = CHG.Amount


LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_USER U ON U.USER_KEY = CASE WHEN DSH.User_key <> -1 THEN DSH.User_key
																	 ELSE Pay.PAID_BY_USER_KEY END
																			 
LEFT JOIN (SELECT TLA.* 
		FROM PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_LEASING_ACCUM TLA
		LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_TENANT T ON T.Tenant_KEY = TLA.Tenant_key
		LEFT JOIN PROD_REPLICA.HBPM_DBO.TENANTINFORMATIONS TI ON TI.TENANTINFORMATIONID  = T.TENANT_INFORMATION_ID
		WHERE TI._FIVETRAN_DELETED <> 'Y'
		AND RENTDUEDAY IS NOT NULL
		AND T.TENANT_KEY NOT IN (70575) ) TLA ON TLA.USER_KEY = U.User_key

LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON 

P.PROPERTY_KEY = COALESCE ( PAY.Property_Key,
									CASE WHEN DSH.PROPERTY_KEY <> -1 THEN DSH.PROPERTY_KEY
									ELSE TLA.PROPERTY_KEY END)
								
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY  = P.PROPERTY_KEY 
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY = PUS.PROPERTY_UNIT_KEY
LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTIES HBPM ON HBPM.PROPERTYID = P.HBPM_PROPERTY_ID --*REPLCA DB*
LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTYADDLINFOES PM_AI ON PM_AI.PROPERTYID  = HBPM.PROPERTYID AND PM_AI."_FIVETRAN_DELETED" = 'N' 
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY = PUS.PORTFOLIO_KEY 
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_REGION R ON R.REGION_KEY = PUS.REGION_KEY 
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_OWNER_ORGANIZATION O ON O.ORGANIZATION_KEY = PUS.ORGANIZATION_KEY 
LEFT JOIN PROD_REPLICA.HBAM_DBO.PROPERTIES HBAM ON HBAM.HBID = P.HBAM_PROPERTY_ID --*REPLCA DB*
LEFT JOIN PROD_REPLICA.HBAM_DBO.CONSTRUCTIONS AM_CONS ON AM_CONS.CONSTRUCTIONID = HBAM.CONSTRUCTION_CONSTRUCTIONID AND AM_CONS.HBID = HBAM.HBID AND AM_CONS."_FIVETRAN_DELETED" <> 'Y'

--REPLICA Section Start

LEFT JOIN (

SELECT 
  APP.PROPERTY_HOLDING_FEE_TRANSACTION_DATE
 ,CAST(COALESCE(HD.DEAL_PIPELINE_STAGE_ID,APP.PROPERTY_HS_PIPELINE_STAGE) AS INT) AS DEAL_PIPELINE_STAGE_ID
 ,COALESCE(D.DEAL_KEY,APP.APP_ID) AS DEAL_KEY_JOIN
 ,DPS.Label AS DEAL_STAGE
 ,APP_ID
  ,CASE 
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 59173506 THEN 'Aplication Started'
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 93217140 THEN 'Needs New Property'        
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 59173507 THEN 'Under Review'
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 59187121 THEN 'Conditional Approval'
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 59187122 THEN 'Full Approval'
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 59187127 THEN 'Pending Denial'
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 59187123 THEN 'Pre-Lease Compliance'
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 59187124 THEN 'Lease Drafting'
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 59187125 THEN 'Lease Executed'
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 59187126 THEN 'Move-In Scheduled'
  WHEN APP.PROPERTY_HS_PIPELINE_STAGE = 59187128 THEN 'Closed Lost'
  ELSE NULL
  END AS APP_STAGE
 ,rank () over ( partition by APP.APP_ID ORDER BY HD.PROPERTY_HS_LASTMODIFIEDDATE DESC) AS DEAL_RANK 
 ,HD.PROPERTY_LEASE_DRAFTING_STATUS
 ,HD.PROPERTY_LEASE_SIGNED_DATE
 ,HD.PROPERTY_MOVE_IN_FEE_PAYMENT_LINK
 ,HD.PROPERTY_MOVE_IN_CHARGES_PAID
 ,HD.PROPERTY_DF_REFERENCE_NUMBER

 
 FROM PROD_ANALYTICS.DBT_RESICAP.DIM_DEAL D
  LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_DEAL_STATUS_ACCUM DSH ON DSH.DEAL_KEY  = D.Deal_Key
  LEFT JOIN PROD_REPLICA.HUBSPOT_2.DEAL HD ON HD.DEAL_ID = D.DEAL_ID

  LEFT JOIN PROD_REPLICA.HUBSPOT_2.APPLICATION_TO_DEAL ATD ON ATD.TO_ID = D.DEAL_ID
   FULL JOIN (
  
    SELECT DISTINCT A.ID AS APP_ID, A.PROPERTY_UNIT_ID, A.PROPERTY_HS_PIPELINE_STAGE, A.PROPERTY_HOLDING_FEE_TRANSACTION_DATE, P.PROPERTY_KEY
    FROM PROD_REPLICA.HUBSPOT_2.APPLICATION A
    LEFT JOIN (select *,
              rank () over ( partition by FROM_ID ORDER BY _FIVETRAN_SYNCED DESC ) AS RECENT_RANK
              FROM PROD_REPLICA.HUBSPOT_2.APPLICATION_TO_PROPERTIES
              Qualify RECENT_RANK =1 ) ATP ON ATP.FROM_ID = A.ID
              LEFT JOIN PROD_REPLICA.HUBSPOT_2.PROPERTIES H_P ON H_P.ID = ATP.TO_ID
              LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.HBPM_PROPERTY_ID = H_P.PROPERTY_PROPERTY_ID
    WHERE IS_INTEGER(A.PROPERTY_HS_PIPELINE_STAGE)  ='True'
    AND A.PROPERTY_UNIT_ID IS NOT NULL
    AND APP_ID NOT IN (8472470544,8657787708,8657665830)) --merged bad data        
              APP ON APP.APP_ID = ATD.FROM_ID AND APP.PROPERTY_KEY = DSH.PROPERTY_KEY
  
   LEFT JOIN 
      (SELECT * FROM PROD_REPLICA.HUBSPOT_2.DEAL_PIPELINE_STAGE 
                  WHERE _FIVETRAN_DELETED = 'N') DPS
       ON DPS.STAGE_ID = HD.DEAL_PIPELINE_STAGE_ID
   
  WHERE 1=1
  --AND DEAL_KEY_JOIN = 116812
  QUALIFY DEAL_RANK = 1 ) HUB_DEAL ON HUB_DEAL.DEAL_KEY_JOIN = D.DEAL_KEY
--Replica Section End       

WHERE 1=1

--AND HD.IS_DELETED <>'Y'
--AND COALESCE(D.CURRENT_DEAL_STATUS,HUB_DEAL.DEAL_STAGE) IS NOT NULL
AND P.Property_KEY IS NOT NULL
AND D.DEAL_PIPELINE <> 'Tour Pipeline'
AND D.CURRENT_flag = 'Y'
AND (L.CURRENT_Flag = 'Y' OR DSH.LEAD_KEY = -1)
AND DSH.LEAD_KEY  IS NOT NULL
----AND L.Application_SUBMIT_Date_KEY IS NOT null
AND (TLA.TENANT_INFORMATION_ID <> 36986 OR TLA.TENANT_INFORMATION_ID IS NULL)
	

AND (HBAM.PROPERTYSTATUSID >9 OR HBAM.PROPERTYSTATUSID IS NULL) --out of bid
AND P.PROPERTY_STATE ='Active'
AND P.EntityID <> ''
AND (HBAM.PROPERTYSTATUSID NOT IN (53,75) OR HBAM.PROPERTYSTATUSID IS NULL)
AND PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54,169)
AND PUS.Organization_KEY not IN (16,17)
AND PO.IS_Active_AM = 'Y'
AND PO.Current_Flag = 'Y'
AND P.Current_Flag = 'Y'
AND PU.Current_Flag = 'Y'
AND PUS.Occupancy_Status NOT IN ('Not Managed')
AND (HBPM.PROPERTYSTATEID = 26 OR HBPM.PROPERTYSTATEID IS NULL) 

--AND DSH.HOLDING_FEE_PAID_DATE_KEY >= 20220201
--AND TLA.Tenant_Key = 4099
--AND D.deal_KEY = 105610
)
--****************************************************************************************************************
            	
,TENANT AS (
 
SELECT

 T.TENANT_KEY
,T.TENANT_INFORMATION_ID
,TS.USER_KEY
,T.LEASE_ID
,RANK() OVER (PARTITION BY TS.Property_KEY ORDER BY Lease_ID ASC) AS Lease_Rank
,PU.PROPERTY_UNIT_KEY
,TS.Property_KEY
,P.HBPM_PROPERTY_ID
,PO.Portfolio_Name
      
,CASE
        WHEN P.ORGANIZATION_KEY IN (-1,18,26,28,48)                   THEN -1
        WHEN P.ORGANIZATION_KEY IN (27,50,51,52,54,45,55,53,56,57,66) THEN 27
        WHEN P.ORGANIZATION_KEY IN (58,59)                            THEN 58
        WHEN P.ORGANIZATION_KEY IN (62,63,64,65,68,69)                THEN 62
        WHEN P.ORGANIZATION_KEY IN (61,70)                            THEN 61
        WHEN P.ORGANIZATION_KEY IN (67)                               THEN 67
        ELSE P.ORGANIZATION_KEY
     END AS ORGANIZATION_KEY
,CASE
        WHEN P.ORGANIZATION_KEY IN (-1,18,26,28,48)                   THEN 'RP SFR'
        WHEN P.ORGANIZATION_KEY IN (27,50,51,52,54,45,55,53,56,57,66) THEN 'RB DRC'
        WHEN P.ORGANIZATION_KEY IN (58,59)                            THEN 'Hudson Oak'
        WHEN P.ORGANIZATION_KEY IN (62,63,64,65,68,69)                THEN 'Rocklyn Homes'
        WHEN P.ORGANIZATION_KEY IN (61,70)                            THEN 'ROI Property Group'
        WHEN P.ORGANIZATION_KEY IN (67)                               THEN 'Newstar'
        ELSE O.ORGANIZATION_NAME
     END AS ORGANIZATION_NAME
      
,P.Address
,P.EntityID
,PUS.Occupancy_Status
,R.REGION_NAME

,U.FULL_NAME
,U.USER_STATUS
,U.EMAIL_ADDRESS
,U.PHONE_NUMBER
,T.TENANT_STATUS
,T.TENANT_TYPE
,T.PRIMARY_TENANT
,T.EVICTION_STATUS
,T.VEHICLES
,T.PETS
,T.MONTH_TO_MONTH
,T.LEASE_TERM
,to_date(T.NOTICE_DATE_KEY::TEXT,'yyyymmdd') AS NOTICE_DATE
,TLA.INITIAL_RENT_AMOUNT
,T.CURRENT_RENT
,Deals.HOLDING_FEE_DATE_NEW AS "HOLDING_FEE_DATE_NEW"
,to_date(TLA.CURRENT_LEASE_EXPIRATION_DATE_KEY ::TEXT,'yyyymmdd') AS CURRENT_LEASE_EXPIRATION_DATE
,to_date(TLA.LEASE_SIGNED_DATE_KEY::TEXT,'yyyymmdd') AS LEASE_SIGNED_DATE
,to_date(TLA.LEASE_FROM_DATE_KEY::TEXT,'yyyymmdd') AS LEASE_FROM_DATE
,to_date(TLA.LEASE_TO_DATE_KEY::TEXT,'yyyymmdd') AS LEASE_TO_DATE

,to_date(T.DOB_DATE_KEY::TEXT,'yyyymmdd') AS DOB
,CASE WHEN  DEALS.AVERAGE_CREDIT_SCORE > 850 THEN NULL ELSE DEALS.AVERAGE_CREDIT_SCORE  END AS AVERAGE_CREDIT_SCORE
,DEALS.COMBINED_INCOME COMBINEDINCOME
,L.NUMBER_OF_CHILDREN
,COALESCE(L.OCCUPANTS,1) OCCUPANTS
,DATEDIFF('year',to_date(T.DOB_DATE_KEY::TEXT,'yyyymmdd'),GETDATE()) TENANT_AGE
,L.MONTHLY_INCOME
,L.IS_RETIRED
,(CASE WHEN T.NOTICE_DATE IS NOT NULL THEN 'Y' ELSE 'N' END) AS IS_NOTICE
,(CASE WHEN T.EVICTION_STATUS IS NOT NULL THEN 'Y' ELSE 'N' END) AS IS_UNDER_EVICTION
,CASE WHEN T.PETS ='Y' THEN COALESCE(L.number_of_pets,1) ELSE COALESCE(L.number_of_pets,0) END AS "PETS_AMOUNT"

,TI.MoveIn
,TI.MoveOut
,TI.PurchaseLetterPostedDate
,TI.DateNotified
,TI.FiledWithCountyDate
,TI.ResidentServedDate
,TI.CourtDateSetDate
,TI.JudgementDate
,TI.LockoutScheduledDate
,TI.VacateDate
,TI.AnticipatedMoveOutDate
,TI.IsSection8
,TI.IsMonthtoMonthLease
,TI.TenantDecidedMonthtoMonth
,TI.DoNotRenew
,TI.ReasonForNotRenewingId
,DNR.DESCRIPTION AS REASONFORNOTRENEWINGNAME
,PUS.Under_written_rent
,AM_PM.MoveInReady
,'https://honeybadgerpm.com/ReportingModule/ViewReport?reportId=1807&UnitId='||TI.UnitID||'&UserId='||TI.UserID||'#/' AS URL_SODA
,CASE WHEN TI.MoveOut IS NULL THEN NULL WHEN TI.MoveOutComplte = 'Y' THEN 'Yes' ELSE 'No' END AS MoveOutComplete
,PM_AI.ReasonOffMarketId --*
,ROM.Description AS ReasonOffMarketName
,Offmarket.OffMarketDate
,to_date(PU.Move_In_Ready::TEXT,'yyyymmdd') AS MOVE_IN_READY

,UW_Rent.UW_Rent_Prior   
,UW_Rent.UW_Rent_Current   
,UW_Rent.UW_Update_Date 

,PICS.PICTURE_COUNT
,AM_STRATEGY.STRATEGYNAME AS STRATEGY_NAME

,CN.CollectionNote
,CN.CollectionNoteCreated
,CN.CollectionNote_Days
,CN.CollectionNote_Added_By
,CASE WHEN HUB_PETS.PETS > 0 OR T.PEts ='Y' THEN 'PET' ELSE NULL END AS PET_FLAG
,PU.SQUARE_FOOTAGE
,P.FloorPlan
,'Re-Lease' AS TYPE

FROM PROD_ANALYTICS.DBT_RESICAP.DIM_TENANT T
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_ACTIVITY TS ON TS.TENANT_KEY = T.TENANT_KEY 
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_LEASING_ACCUM TLA ON TLA.TENANT_KEY = T.Tenant_Key
LEFT JOIN PROD_REPLICA.HBPM_DBO.TENANTINFORMATIONS TI ON TI.TenantInformationId = T.TENANT_INFORMATION_ID
LEFT JOIN PROD_REPLICA.HBPM_DBO.LOOKUPMASTERS DNR on DNR.LookUpMasterId = TI.ReasonForNotRenewingId
--LEFT JOIN PROD_REPLICA.HBPM_DBO.DEALS PM_D ON PM_D.LEADUSERID = TI.USERID AND PM_D.UNITID =TI.UNITID AND PM_D.SECURITYDEPOSITID IS NOT null
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_USER U ON U.USER_KEY = TS.USER_KEY
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY = TS.PROPERTY_KEY
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY  = P.PROPERTY_KEY 
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY = PUS.PROPERTY_UNIT_KEY
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY = PUS.PORTFOLIO_KEY 
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_OWNER_ORGANIZATION O ON O.ORGANIZATION_KEY = PUS.ORGANIZATION_KEY
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_REGION R ON R.REGION_KEY = PUS.REGION_KEY 
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_LEAD L ON L.lead_key = TS.LEAD_KEY 
LEFT JOIN PROD_REPLICA.HBAM_DBO.PROPERTIES HBAM ON HBAM.HBID = P.HBAM_PROPERTY_ID --*REPLCA DB*
LEFT JOIN PROD_REPLICA.HBAM_DBO.PROPERTYMANAGEMENTS AM_PM ON AM_PM.PROPERTYMANAGEMENTID = HBAM.PropertyManagement_PropertyManagementId AND AM_PM.HBID = HBAM.HBID
	LEFT JOIN PROD_REPLICA.HBAM_DBO.BidAndAuctions AM_BA ON AM_BA.BIDID = HBAM.BidAndAuction_BidId AND AM_BA.HBID = HBAM.HBID AND AM_BA."_FIVETRAN_DELETED" <> 'Y'
	LEFT JOIN PROD_REPLICA.HBAM_DBO.Strategies AM_STRATEGY ON AM_STRATEGY.STRATEGYID = AM_BA.BIDSTRATEGYSTATUS 

LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTIES HBPM ON HBPM.PROPERTYID = P.HBPM_PROPERTY_ID --*REPLCA DB*
LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTYADDLINFOES PM_AI ON PM_AI.PROPERTYID  = HBPM.PROPERTYID AND PM_AI."_FIVETRAN_DELETED" = 'N' 
LEFT JOIN PROD_REPLICA.HBPM_DBO.LOOKUPMASTERS ROM ON ROM.LookUpMasterId = PM_AI.ReasonOffMarketId
LEFT JOIN CollectionsNote CN ON CN.UserID = TI.UserID

LEFT JOIN DEALS ON Deals.DEAL_KEY = TS.DEAL_KEY
 AND Deals.Current_Deal_Status NOT IN ('Deal Lost', 'Rejected','Closed Lost','Property Listed')
 AND Deals.APP_STAGE NOT IN ('Pending Denial','Closed Lost','Needs New Property')
 AND Deals.APP_STAGE IS NOT NULL
			
LEFT JOIN (SELECT C.ID, COUNT(PET.ID) PETS
			FROM PROD_REPLICA.HUBSPOT.PET 
			LEFT JOIN PROD_REPLICA.HUBSPOT.PET_TO_CONTACT PTC ON PTC.FROM_ID = PET.ID
			LEFT JOIN PROD_REPLICA.HUBSPOT.CONTACT C ON C.ID = PTC.TO_ID 
			GROUP BY C.ID) HUB_PETS ON HUB_PETS.ID = L.LEAD_ID
	
/*LEFT JOIN (SELECT 
			FCT_TENANT_SUMMARY_KEY 
			,TENANT_INFORMATION_ID 
			,AVERAGE_CREDIT_SCORE
			,R_TS.COMBINED_INCOME
			,NUMBER_OF_CHILDREN
			,OCCUPANTS
			,TENANT_AGE
			,MONTHLY_INCOME
			,IS_RETIRED
			,IS_NOTICE
			,IS_UNDER_EVICTION
			FROM PROD_ANALYTICS.RESICAP.FCT_TENANT_SUMMARY R_TS
			LEFT JOIN PROD_ANALYTICS.RESICAP.DIM_TENANT R_T ON R_T.TENANT_KEY = R_TS.TENANT_KEY ) RESI_TSUM ON RESI_TSUM.TENANT_INFORMATION_ID = T.TENANT_INFORMATION_ID*/

LEFT JOIN (
			SELECT 
			PROPERTY_KEY  
			,MAX(to_date(CHANGED_DATE_KEY::TEXT,'yyyymmdd')) OffMarketDate
			FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROP_UNIT_STATUS_HIST
			
			WHERE 1=1
			AND NEW_OCCUPANCY_STATUS = 'Vacant - Off Market'
			GROUP BY PROPERTY_KEY ) OffMarket ON OffMarket.Property_key = P.Property_key			

LEFT JOIN UW_RENT ON UW_Rent.HBPM_UnitID = PM_AI.UnitID				
LEFT JOIN PICS ON PICS.PM_PropertyID = P.HBPM_PROPERTY_ID	

WHERE 1=1
AND T.CURRENT_FLAG = 'Y'
AND T.PRIMARY_TENANT = 'Y'

AND P.PROPERTY_STATE ='Active'
AND P.EntityID <> ''
AND TI._FIVETRAN_DELETED <> 'Y'
AND TI.RENTDUEDAY IS NOT NULL
--AND (PS.PROPERTY_STATUS_ID NOT IN (53,75) OR PS.PROPERTY_STATUS_ID IS NULL)
AND PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54,169)
AND P.Organization_KEY not IN (16,17)
AND PO.IS_Active_AM = 'Y'
AND PO.Current_Flag = 'Y'
AND P.Current_Flag = 'Y'
AND PU.Current_Flag = 'Y'
AND PUS.Occupancy_Status NOT IN ('Property SOLD','Not Managed'))
-- T.TENANT_KEY NOT IN (70575))
--SELECT * FROM Tenant
--**************************************************************************************        
,HAPPY_CO_TURN AS (
SELECT
Tenant.Lease_ID
,Tenant.Property_Key
,Tenant.MoveOut
,MIN(HAPPY_CO_SCOPE.HC_SCOPE_COMPLETED_DATE) HC_SCOPE_COMPLETED_DATE
,MIN(HAPPY_CO_QC.HC_TURN_COMPLETED_DATE) HC_TURN_COMPLETED_DATE
FROM Tenant
LEFT JOIN HAPPY_CO_SCOPE ON HAPPY_CO_SCOPE.Property_Key = Tenant.Property_key
                            AND HAPPY_CO_SCOPE.HC_SCOPE_COMPLETED_DATE >= Tenant.MoveOut
                            AND HAPPY_CO_SCOPE.Recent_Rank = 1
                            
LEFT JOIN HAPPY_CO_QC ON  HAPPY_CO_QC.Property_Key = Tenant.Property_key
                            AND HAPPY_CO_QC.HC_TURN_COMPLETED_DATE  >= Tenant.MoveOut
                            AND  HAPPY_CO_QC.Recent_Rank = 1
WHERE 1=1
--AND  Tenant.Property_Key = 251448
--AND HAPPY_CO_SCOPE.Recent_Rank = 1
--AND HAPPY_CO_QC.Recent_Rank = 1
--AND Tenant.Lease_ID = 234243
GROUP BY
 Tenant.Lease_ID
,Tenant.Property_Key
,Tenant.MoveOut
)
--**************************************************************************************    
,Turnkey AS (
 SELECT 
 --DISTINCT 
 Tenant.Lease_ID AS O_TURN_ID
,Tenant.Lease_Rank AS  O_Lease_Rank
,Tenant.Tenant_KEY AS O_Tenant_KEY
,Tenant.TENANT_STATUS AS O_Tenant_Status
,Tenant.FULL_NAME AS O_Tenant_FULL_NAME
,Tenant.EMAIL_ADDRESS AS O_Tenant_EMAIL_ADDRESS

,Tenant.PROPERTY_UNIT_KEY
,Tenant.Property_KEY
,Tenant.HBPM_Property_Id
,Tenant.Portfolio_Name
,Tenant.Address
,Tenant.EntityID
,Tenant.Occupancy_Status
,Tenant.Region_Name
,Tenant.SQUARE_FOOTAGE
,Tenant.FloorPlan
,Tenant.TYPE

,Tenant.CURRENT_RENT AS O_Current_Rent
,Tenant.HOLDING_FEE_DATE_NEW AS O_HOLDING_FEE_DATE
,Tenant.MoveIn AS O_MoveIn
,Tenant.LEASE_FROM_DATE AS O_LEASE_FROM_DATE
,Tenant.LEASE_TO_DATE AS O_LEASE_TO_DATE
,Tenant.NOTICE_DATE AS O_Notice_Date
,Tenant.AnticipatedMoveOutDate AS O_AnticipatedMoveOutDate
,Tenant.MoveOut AS O_Move_Out
,DATE_TRUNC('month',Tenant.MoveOut) AS O_Move_Out_BOM

,Tenant_New.Lease_ID AS N_TURN_ID
,Tenant_New.Lease_Rank AS  N_Lease_Rank
,COALESCE(Tenant_New.INITIAL_RENT_AMOUNT,Tenant_New.CURRENT_RENT) AS N_Initial_Rent
,Tenant_New.CURRENT_RENT AS N_Current_Rent
,Tenant_New.HOLDING_FEE_DATE_NEW AS N_HOLDING_FEE_DATE
,Tenant_New.MoveIn AS N_MoveIn
,Tenant_New.LEASE_FROM_DATE AS N_LEASE_FROM_DATE
,Tenant_New.LEASE_TO_DATE AS N_LEASE_TO_DATE
,Tenant_New.MoveOut AS N_Move_Out

,CASE
        WHEN Tenant.ORGANIZATION_KEY IN (-1,18,26,28,48)                   THEN -1
        WHEN Tenant.ORGANIZATION_KEY IN (27,50,51,52,54,45,55,53,56,57,66) THEN 27
        WHEN Tenant.ORGANIZATION_KEY IN (58,59)                            THEN 58
        WHEN Tenant.ORGANIZATION_KEY IN (62,63,64,65,68,69)                THEN 62
        WHEN Tenant.ORGANIZATION_KEY IN (61,70)                            THEN 61
        WHEN Tenant.ORGANIZATION_KEY IN (67)                               THEN 67
        ELSE Tenant.ORGANIZATION_KEY
     END AS ORGANIZATION_KEY
,CASE
        WHEN Tenant.ORGANIZATION_KEY IN (-1,18,26,28,48)                   THEN 'RP SFR'
        WHEN Tenant.ORGANIZATION_KEY IN (27,50,51,52,54,45,55,53,56,57,66) THEN 'RB DRC'
        WHEN Tenant.ORGANIZATION_KEY IN (58,59)                            THEN 'Hudson Oak'
        WHEN Tenant.ORGANIZATION_KEY IN (62,63,64,65,68,69)                THEN 'Rocklyn Homes'
        WHEN Tenant.ORGANIZATION_KEY IN (61,70)                            THEN 'ROI Property Group'
        WHEN Tenant.ORGANIZATION_KEY IN (67)                               THEN 'Newstar'
        ELSE Tenant.ORGANIZATION_NAME
     END AS ORGANIZATION_NAME

,Tenant.MoveInReady
,Tenant.URL_SODA
,Tenant.MoveOutComplete
,Tenant.Move_In_Ready AS Listing_MI_READY_DATE

,HAPPY_CO_SCOPE.HC_SCOPE_INSPECTION_LINK
,HAPPY_CO_SCOPE.HC_SCOPE_COMPLETED_DATE
,HAPPY_CO_SCOPE.HC_SCOPE_REPORT_STATUS
,HAPPY_CO_SCOPE.HC_SCOPE_ISSUE_COUNT

,HAPPY_CO_QC.HC_TURN_INSPECTION_LINK
,HAPPY_CO_QC.HC_TURN_COMPLETED_DATE
,HAPPY_CO_QC.HC_TURN_REPORT_STATUS
,HAPPY_CO_QC.HC_TURN_ISSUE_COUNT

,CASE WHEN HAPPY_CO_QC.HC_TURN_REPORT_STATUS = 'Pass' AND HAPPY_CO_QC.HC_TURN_ISSUE_COUNT > 0 THEN 'Pass (Minor Fail)'
      WHEN HAPPY_CO_QC.HC_TURN_REPORT_STATUS = 'Pass w/Minor Fails' THEN 'Pass (Minor Fail)'
      ELSE NULL END AS PASS_MINOR
,Tenant.ReasonOffMarketName
,Tenant.OffMarketDate

,Tenant.UW_Rent_Prior   
,Tenant.UW_Rent_Current   
,Tenant.UW_Update_Date

,Tenant.PICTURE_COUNT
,Tenant.STRATEGY_NAME
,Tenant.REASONFORNOTRENEWINGNAME

,Tenant.CollectionNote
,Tenant.CollectionNoteCreated
,Tenant.CollectionNote_Days
,Tenant.CollectionNote_Added_By
,Tenant.PET_FLAG

FROM Tenant
LEFT JOIN Tenant AS Tenant_New ON TENANT_NEW.Property_Key = TENANT.Property_Key AND (TENANT_NEW.Lease_Rank = TENANT .Lease_Rank +1)
LEFT JOIN HAPPY_CO_TURN HCT ON HCT.Lease_ID = Tenant.Lease_ID 
LEFT JOIN HAPPY_CO_SCOPE ON HAPPY_CO_SCOPE.HC_SCOPE_COMPLETED_DATE = HCT.HC_SCOPE_COMPLETED_DATE AND HAPPY_CO_SCOPE.Property_key = HCT.Property_key AND HAPPY_CO_SCOPE.RECENT_RANK = 1
LEFT JOIN HAPPY_CO_QC ON HAPPY_CO_QC.HC_TURN_COMPLETED_DATE = HCT.HC_TURN_COMPLETED_DATE AND HAPPY_CO_QC.Property_key = HCT.Property_key AND HAPPY_CO_QC.RECENT_RANK = 1

WHERE 1=1
AND (Tenant.MoveOut IS NOT NULL OR Tenant.AnticipatedMoveOutDate <= DATEADD('day',60, GETDATE() ) )
--AND Tenant.Occupancy_Status <> 'Dispositions'
--AND  Tenant.Property_Key = 251448
)

--SELECT * FROM Turnkey
--WHERE Property_key= 226644
--**************************************************************************************
,Turn_Listings AS (

SELECT 
MIN(RENT_LIST_HIST_ID) RENT_LIST_HIST_KEY
,O_Turn_ID 
,Turnkey.Property_key
FROM Turnkey

LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROP_RENTAL_LISTING_HIST RLH ON RLH.PROPERTY_KEY  = Turnkey.Property_key
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_LISTING DL  ON DL.LISTING_KEY  = RLH.LISTING_KEY 

WHERE 1=1

AND to_date(RLH.LISTING_DATE_KEY::TEXT,'yyyymmdd')  >= O_LEASE_FROM_DATE
AND to_date(RLH.LISTING_DATE_KEY::TEXT,'yyyymmdd') <= COALESCE(N_LEASE_FROM_DATE,'1/1/9999')
--AND ((RLH.LISTING_STATUS <> 'Leased' AND N_LEASE_FROM_DATE IS NULL) OR N_LEASE_FROM_DATE IS NOT NULL ) 
AND RLH.LISTING_STATUS <> 'Withdrawn'
AND ((RLH.LISTING_STATUS IN ('Active','Deposit Taken', 'Leased') AND DL.LISTING_STATE IS NOT NULL AND DL.IS_PUBLISHED <> 'N')
      OR RLH.LISTING_STATUS IN ('Deposit Taken', 'Leased'))

--AND Turnkey.Property_key =242795
GROUP BY
O_Turn_ID 
,Turnkey.Property_key ) 


--SELECT * FROM Turn_Listings
--WHERE Property_KEy = 245796
--**************************************************************************************
,MoveOutLineItems AS ( 
	 
SELECT 
  TI.LEASEID
 ,LT.Amount as Payments
 ,GL.Description as GlAccountDesc 
 ,AR.Description as Description
 ,TI.USERID 
FROM PROD_ANALYTICS.DBT_RESICAP.FCT_LEASING_TRANSACTION LT
LEFT JOIN PROD_REPLICA.HBPM_DBO.MoveOutSettleCharges MSC ON MSC.RECEIVABLESID = LT.RECEIVABLE_ID AND MSC._FIVETRAN_DELETED = 'N'
LEFT JOIN PROD_REPLICA.HBPM_DBO.AccountsReceivables AR ON  AR.ReceivableID = LT.RECEIVABLE_ID 
LEFT JOIN PROD_REPLICA.HBPM_DBO.GLAccounts GL ON  GL.GLAccountID  = AR.GLACCOUNTID 

LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_TENANT TEN ON TEN.LEASE_ID = AR.LeaseID AND TEN.PRIMARY_TENANT = 'Y'  AND TEN.CURRENT_FLAG = 'Y'
LEFT JOIN PROD_REPLICA.HBPM_DBO.TENANTINFORMATIONS TI ON TI.TenantInformationId = TEN.TENANT_INFORMATION_ID
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_LEASING_ACCUM TS ON TS.TENANT_KEY = TEN.TENANT_KEY 
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_USER U ON U.USER_KEY = TS.USER_KEY

WHERE 1=1
--AND TI.LeaseId = 20019
AND AR.RECEIVABLESTATUSID = 901 --Active
AND AR."_FIVETRAN_DELETED"='N'
AND LT.TRANSACTION_TYPE = 'Charges'
AND LT.STATUS = 'Active'
AND LT.IS_CREDIT = 'N'
AND  GL.GLAccountID = 20

--AND MS.TenantInformationId = 35868
)
	
--SELECT * FROM MoveOutLineItems
--WHERE USerID =1074545
--*****************************************************************************************
,MoveOutCharges AS (
SELECT 
	LeaseID
	,SUM(Payments) MoveOutCharges
FROM MoveOutLineItems
WHERE LeaseID IS NOT NULL
AND Description NOT LIKE '%Early Term%'
AND Description NOT LIKE '%Insufficient Notice%'
AND Description NOT LIKE '%Prorated%'
GROUP BY LEASEID
)
--*****************************************************************************************
,BadDebt AS (
Select 
ARD.ReceiptId
,MAX(AR.CreditTypeID) CreditTYpeID
FROM PROD_REPLICA.HBPM_DBO.ACCOUNTSRECEIPTDETAILS ARD
LEFT JOIN PROD_REPLICA.HBPM_DBO.ACCOUNTSRECEIVABLES AR ON AR.ReceivableID = ARD.ReceivableId
WHERE AR.ReceivableStatusId = 901
GROUP BY ARD.ReceiptId )
--*****************************************************************************************
,MoveOutLineItemsReceipts AS (
  
SELECT 
  TI.LEASEID
 ,LT.Amount as Payments
 ,LT.CHARGE_GL_ACCOUNT_NAME as GlAccountDesc 
 ,ARV.Description as Description
 ,LT.IS_CREDIT
 ,BD.CreditTypeId
 ,CASE WHEN BD.CreditTypeId = 1 THEN 'Concession'
     WHEN BD.CreditTypeId = 2 THEN 'Bad Debt' END AS Credit_Type_Name
 ,TI.USERID 

FROM PROD_ANALYTICS.DBT_RESICAP.FCT_LEASING_TRANSACTION LT
LEFT JOIN PROD_REPLICA.HBPM_DBO.ACCOUNTSRECEIPTDETAILS ARD ON  ARD.RECEIPTDETAILID = LT.RECEIPT_DETAIL_ID AND ARD."_FIVETRAN_DELETED"='N'
LEFT JOIN PROD_REPLICA.HBPM_DBO.ACCOUNTSRECEIPTS AR ON AR.RECEIPTID = ARD.RECEIPTID AND AR."_FIVETRAN_DELETED"='N'
LEFT join PROD_REPLICA.HBPM_DBO.LOOKUPMASTERS RS ON RS.LOOKUPMASTERID = AR.RECEIPTSTATUSID 
LEFT join PROD_REPLICA.HBPM_DBO.LOOKUPMASTERS PT ON PT.LOOKUPMASTERID = AR.PAIDBYTYPEID 
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_GL_ACCOUNT GL ON GL.GL_ACCOUNT_KEY = LT.GL_ACCOUNT_KEY 
LEFT JOIN BadDebt BD ON BD.ReceiptID = ARD.ReceiptID
LEFT JOIN PROD_REPLICA.HBPM_DBO.AccountsReceivables ARV ON  ARV.ReceivableID = LT.RECEIVABLE_ID 

LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_TENANT TEN ON TEN.LEASE_ID = AR.LeaseID AND TEN.PRIMARY_TENANT = 'Y'  AND TEN.CURRENT_FLAG = 'Y'
LEFT JOIN PROD_REPLICA.HBPM_DBO.TENANTINFORMATIONS TI ON TI.TenantInformationId = TEN.TENANT_INFORMATION_ID
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_LEASING_ACCUM TS ON TS.TENANT_KEY = TEN.TENANT_KEY 
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_USER U ON U.USER_KEY = TS.USER_KEY

WHERE 1=1
AND LT.TRANSACTION_TYPE = 'Payment'
AND LT.Tenant_Key IS NOT NULL	
AND (AR.RECEIPTSTATUSID IN (901,904) OR AR.RECEIPTSTATUSID Is null) --Active/Pending
AND ARD."_FIVETRAN_DELETED"='N'
AND AR."_FIVETRAN_DELETED"='N'
AND LT.STATUS = 'Active'
AND LT.IS_CREDIT = 'N'
AND  LT.CHARGE_GL_ACCOUNT_NUMBER = '4016'
  
--ORDER BY LEASEID DESC
)
--*****************************************************************************************
,MoveOutReceipts AS (
SELECT 
	LeaseID
	,SUM(CASE WHEN CreditTypeId IS NULL THEN Payments ELSE 0 END) MoveOutReceipts_PAID
  	,SUM(CASE WHEN CreditTypeId = 1 THEN Payments ELSE 0 END ) MoveOutReceipts_CONCESSION
  	,SUM(CASE WHEN CreditTypeId = 2 THEN Payments ELSE 0 END) MoveOutReceipts_BAD_DEBT
  	,SUM(Payments) MoveOutReceipts_TOTAL
  
  
FROM MoveOutLineItemsReceipts
WHERE LeaseID IS NOT NULL
AND Description NOT LIKE '%Early Term%'
AND Description NOT LIKE '%Insufficient Notice%'
AND Description NOT LIKE '%Prorated%'
GROUP BY LEASEID
)

--*****************************************************************************************

,WO_DETAIL AS (
SELECT 
 
TI.TICKET_KEY
,WO.WORKORDER_KEY
,TI.TICKET_TYPE
,COALESCE(TI.TICKET_TYPE, 'Maintenance') AS TICKET_TYPE_CLOSED
,TI.TICKET_STATUS
,WO.WORKORDER_ID
,WO.MAINT_ID
,WO.HBH_ID_KEY
,WO.WORKORDER_STATUS
,WO.PRIORITY
,WO.BILL_TO

,P.Property_Key

,CASE
        WHEN P.ORGANIZATION_KEY IN (-1,18,26,28,48)                   THEN -1
        WHEN P.ORGANIZATION_KEY IN (27,50,51,52,54,45,55,53,56,57,66) THEN 27
        WHEN P.ORGANIZATION_KEY IN (58,59)                            THEN 58
        WHEN P.ORGANIZATION_KEY IN (62,63,64,65,68,69)                THEN 62
        WHEN P.ORGANIZATION_KEY IN (61,70)                            THEN 61
        WHEN P.ORGANIZATION_KEY IN (67)                               THEN 67
        ELSE P.ORGANIZATION_KEY
     END AS ORGANIZATION_KEY
,CASE
        WHEN P.ORGANIZATION_KEY IN (-1,18,26,28,48)                   THEN 'RP SFR'
        WHEN P.ORGANIZATION_KEY IN (27,50,51,52,54,45,55,53,56,57,66) THEN 'RB DRC'
        WHEN P.ORGANIZATION_KEY IN (58,59)                            THEN 'Hudson Oak'
        WHEN P.ORGANIZATION_KEY IN (62,63,64,65,68,69)                THEN 'Rocklyn Homes'
        WHEN P.ORGANIZATION_KEY IN (61,70)                            THEN 'ROI Property Group'
        WHEN P.ORGANIZATION_KEY IN (67)                               THEN 'Newstar'
        ELSE O.ORGANIZATION_NAME
     END AS ORGANIZATION_NAME

,PO.Portfolio_Name
,P.EntityId
,P.Address
,R.Region_ID
,R.Region_Name

--,WOST.TENANT_USER_KEY
,WOST.VENDOR_KEY
,V.VENDOR_ID
,V.COMPANY_NAME
,CASE WHEN V.CURRENT_VENDOR_STAGE = 'Compliant' THEN 'Active' ELSE V.CURRENT_VENDOR_STAGE END AS "CURRENT_VENDOR_STAGE"
,V.VENDOR_STANDING
,WO.MAINT_APPROVED
,WO.MANAGED_BY

,WO.APPROVED_BY_OWNER
,WO.IS_WARRANTY_WRK

,WO.SENT_FOR_OWNER_APPROVAL
,WO.EST_APPROVED_BY_OWNER
,WO.CHANGE_RQST_NEEDED
,WO.CR_SENT_FOR_OWNER_APPROVAL
,WO.CR_APPROVED_BY_OWNER
,WO.ONSITE_APPROVAL
,WO.NOTE_IS_OWNER
,to_date(WO.NOTE_CREATED_DATE_KEY::TEXT,'YYYYMMDD') AS NOTE_CREATED_DATE
,WO.NOTE_TEXT
,WO.APPROVAL_STATUS
,to_date(WO.APPROVAL_DATE_KEY::TEXT,'YYYYMMDD') AS APPROVAL_DATE
,WO.APPROVER_MESSAGE
,WO.APPROVER

,to_date(TI.CREATED_DATE_KEY::TEXT,'YYYYMMDD') AS TICKET_CREATED_DATE
,to_date(WO.CREATED_DATE_KEY::TEXT,'YYYYMMDD') AS WO_CREATED_DATE
,to_date(WO.MODIFIED_DATE_KEY::TEXT,'YYYYMMDD') AS WO_MODIFIED_DATE
,to_date(WOST.WO_REQUESTED_DATE_KEY::TEXT,'YYYYMMDD') AS WO_REQUESTED_DATE
,to_date(WOST.WO_ACCEPTED_DATE_KEY::TEXT,'YYYYMMDD') AS WO_ACCEPTED_DATE
,to_date(WOST.WO_ESTIMATED_DATE_KEY::TEXT,'YYYYMMDD') AS WO_ESTIMATED_DATE
,to_date(WOST.WO_RE_ESTIMATED_DATE_KEY::TEXT,'YYYYMMDD') AS WO_RE_ESTIMATED_DATE
,to_date(WOST.WO_AWAITING_OWNER_APPROVAL_DATE_KEY::TEXT,'YYYYMMDD') AS WO_AWAITING_OWNER_APPROVAL_DATE
,to_date(WO.SENT_FOR_OWNER_APVL_DATE_KEY::TEXT,'YYYYMMDD') AS SENT_FOR_OWNER_APVL_DATE
,to_date(WOST.WO_OWNER_APPROVAL_DATE_KEY::TEXT,'YYYYMMDD') AS WO_OWNER_APPROVAL_DATE
,to_date(WOST.WO_PENDING_COMPLETION_DATE_KEY::TEXT,'YYYYMMDD') AS WO_PENDING_COMPLETION_DATE
,to_date(DBT_WOI.CLIENT_INVOICE_DATE_KEY::TEXT,'YYYYMMDD') AS CLIENT_INVOICE_DATE
,COALESCE (to_date(DBT_WOI.VENDOR_INVOICE_DATE_KEY::TEXT,'YYYYMMDD'), to_date(WOST.WO_CLOSED_DATE_KEY::TEXT,'YYYYMMDD') )  AS VENDOR_INVOICE_DATE
,to_date(WOST.WO_COMPLETED_AWAITING_APPROVAL_DATE_KEY::TEXT,'YYYYMMDD') AS WO_COMPLETED_AWAITING_APPROVAL_DATE
,to_date(WOST.WO_UNBILLED_DATE_KEY::TEXT,'YYYYMMDD') AS WO_UNBILLED_DATE
,to_date(WOST.WO_CLOSED_DATE_KEY::TEXT,'YYYYMMDD') AS WO_CLOSED_DATE
,to_date(WOST.WO_CANCELLED_DATE_KEY::TEXT,'YYYYMMDD') AS WO_CANCELLED_DATE
,to_date(WO_START_DATE_KEY::TEXT,'YYYYMMDD') AS WO_START_DATE
,to_date(WO_END_DATE_KEY::TEXT,'YYYYMMDD') AS WO_END_DATE

,DBT_WOI.CLIENT_INVOICE_NO
,DBT_WOI.CLIENT_MATERIAL_CHARGE
,DBT_WOI.CLIENT_HOURLY_LABOR_CHARGE
,DBT_WOI.CLIENT_FLAT_LABOR_CHARGE
,CASE WHEN WO.WORKORDER_STATUS ='Closed' THEN ZEROIFNULL(DBT_WOI.CLIENT_INVOICE_AMOUNT) ELSE DBT_WOI.CLIENT_INVOICE_AMOUNT END AS CLIENT_INVOICE_AMOUNT
,EST.CLIENT_ESTIMATE 
,DBT_WOI.VENDOR_MATERIAL_CHARGE
,DBT_WOI.VENDOR_HOURLY_LABOR_CHARGE
,DBT_WOI.VENDOR_FLAT_LABOR_CHARGE
,DBT_WOI.VENDOR_INVOICE_AMOUNT
,DBT_WOI.VENDOR_INVOICE_NO
,DBT_WOI.CLIENT_INVOICE_AMOUNT - DBT_WOI.VENDOR_INVOICE_AMOUNT AS "Invoice_Profit"

,C.CategoryID
,C.CATEGORYNAME
,MCD.WO_PROBLEM
,MCD.WO_Solution
,'https://honeybadgermm.com/Maintenance#/CreateWorkOrder/' || WO.Maint_ID AS HBMM_URL

,DATE_TRUNC('month',COALESCE (to_date(DBT_WOI.CLIENT_INVOICE_DATE_KEY::TEXT,'YYYYMMDD'), to_date(WOST.WO_CLOSED_DATE_KEY::TEXT,'YYYYMMDD'))) AS "1_Invoice (BOM)"

,CASE WHEN COALESCE (to_date(DBT_WOI.VENDOR_INVOICE_DATE_KEY::TEXT,'YYYYMMDD'), to_date(WOST.WO_CLOSED_DATE_KEY::TEXT,'YYYYMMDD')) IS NOT NULL THEN DATEDIFF(DAY,to_date(TI.CREATED_DATE_KEY::TEXT,'YYYYMMDD'),COALESCE (to_date(DBT_WOI.VENDOR_INVOICE_DATE_KEY::TEXT,'YYYYMMDD'), to_date(WOST.WO_CLOSED_DATE_KEY::TEXT,'YYYYMMDD')))
      WHEN WO.WORKORDER_STATUS = 'Closed' AND COALESCE (to_date(DBT_WOI.VENDOR_INVOICE_DATE_KEY::TEXT,'YYYYMMDD'), to_date(WOST.WO_CLOSED_DATE_KEY::TEXT,'YYYYMMDD')) IS NULL THEN NULL 
	  ELSE DATEDIFF(DAY,to_date(TI.CREATED_DATE_KEY::TEXT,'YYYYMMDD'),GETDATE())
      END AS "1_DIQ/CycleTime"

 ,CASE WHEN V.VENDOR_KEY IN (33018,33014,32987,33019,196,32555,906,1274,1929) THEN 'Warranty Vendor' ELSE 'External Vendor' END AS Warranty
 ,CASE WHEN V.VENDOR_KEY IN (33018,33014,32987,33019,196,32555,906,1274,1929) THEN V.Company_Name ELSE NULL END AS Warranty_Vendor_Name

,MM_MASTER."NoteText" AS WO_NOTE_TEXT
,MM_MASTER."Note Created Date" AS WO_NOTE_CREATED_DATE
,MM_MASTER."NoteAddedBy" AS WO_NOTE_ADDED_BY
 
FROM PROD_ANALYTICS.DBT_RESICAP.DIM_TICKET TI
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TICKET_STATUS_ACCUM TSA ON TSA.TICKET_KEY  = TI.TICKET_KEY 
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_WO_STATUS_ACCUM WOST ON WOST.TICKET_KEY  = TI.TICKET_KEY 
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_WORKORDER WO ON WO.WORKORDER_KEY = WOST.WORKORDER_KEY AND WO.CURRENT_FLAG = 'Y'
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_VENDOR V ON V.VENDOR_KEY = WOST.VENDOR_KEY

LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_WO_INVOICE DBT_WOI ON DBT_WOI.WORKORDER_KEY  = WO.WorkORder_key
LEFT JOIN (SELECT 
				WORKORDER_KEY AS DBT_WO_KEY
				,SUM (MARKUP_AMOUNT) AS CLIENT_ESTIMATE
				FROM PROD_ANALYTICS.DBT_RESICAP.FCT_WO_ESTIMATED_MATERIAL
				GROUP BY WORKORDER_KEY ) EST ON EST.DBT_WO_KEY = WOST.WORKORDER_KEY
				

LEFT JOIN (SELECT 
				Min(MaintenanceCategoryDetailId) AS MaintenanceCategoryDetailID
				,MIN(CategoryDescription) AS WO_Problem
				,MIN(VENDORNOTES) AS WO_Solution
				,MaintenanceIDKey
                FROM PROD_REPLICA.HBMM_DBO.MAINTENANCECATEGORYDETAILS 
                --WHERE MaintenanceIDKey = 668614
				GROUP BY MaintenanceIDKey) MCD on MCD.MaintenanceIdkey = WO.MAINT_ID 

LEFT JOIN PROD_REPLICA.HBMM_DBO.MaintenanceCategoryDetails on MaintenanceCategoryDetails.MaintenanceCategoryDetailId = MCD.MaintenanceCategoryDetailID
LEFT JOIN PROD_REPLICA.HBMM_DBO.MaintenanceCategories C on C.CategoryId = MaintenanceCategoryDetails.CategoryId
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY = TSA.PROPERTY_KEY AND P.CURRENT_FLAG ='Y'
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY = P.PROPERTY_KEY
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY = PUS.PROPERTY_UNIT_KEY 
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_REGION R ON R.REGION_KEY = PUS.REGION_KEY 
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY = PUS.PORTFOLIO_KEY 
LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_OWNER_ORGANIZATION O ON O.ORGANIZATION_KEY = PUS.ORGANIZATION_KEY 
LEFT JOIN PROD_ANALYTICS.BI_MASTER_DATASETS.MASTER_MM_WORKORDER MM_MASTER ON MM_MASTER."IDKey" = COALESCE(WO.MAINT_ID,TI.ID_KEY)

WHERE 1=1 
AND (WO.WORKORDER_STATUS <> 'Cancelled' OR WO.WORKORDER_STATUS IS NULL)
AND TI.TICKET_STATUS <> 'Cancelled'
AND ((TI.TICKET_STATUS = 'Closed' AND WO.WORKORDER_KEY IS NOT NULL)
	OR (TI.TICKET_STATUS = 'Open' AND WO.WORKORDER_KEY IS NOT NULL )
	OR (TI.TICKET_STATUS <> 'Closed' AND TI.TICKET_STATUS <> 'Open') )
		
AND TI.CREATED_DATE_KEY > '20210101'

AND P.PROPERTY_STATE ='Active'
AND P.EntityID <> ''
--AND (PS.PROPERTY_STATUS_ID NOT IN (53,75) OR PS.PROPERTY_STATUS_ID IS NULL)
AND PO.Portfolio_KEY NOT IN (1845, 2210, 2207, 2218, 1952,1867, 1916,1852,1771,1919,1873)
AND P.Organization_KEY not IN (16,17)
AND PO.IS_Active_AM = 'Y'
AND PO.Current_Flag = 'Y'
AND P.Current_Flag = 'Y'
AND PU.Current_Flag = 'Y'
AND PUS.Occupancy_Status NOT IN ('Property SOLD','Not Managed')
--AND P.Property_key= 223502
)


--**************************************************************************************
,WO_TURN AS (
SELECT 
WO_DETAIL.TICKET_KEY
,WO_DETAIL.WORKORDER_KEY
,MIN(Turnkey.O_TURN_ID) O_Turn_ID

FROM WO_DETAIL
LEFT JOIN Turnkey ON Turnkey.Property_key = WO_DETAIL.Property_key

WHERE 1=1
AND (TICKET_TYPE = 'Turnkey' OR CategoryName = 'Unit Turns (Paint/Clean/Minor Repairs)')
AND TICKET_TYPE <> 'Trespassers/Vandalism'
AND TICKET_CREATED_DATE >=  to_date(LEAST(Turnkey.O_MOVE_OUT,O_Notice_Date)::TEXT,'AUTO')
AND (TICKET_CREATED_DATE <= Turnkey.N_LEASE_FROM_DATE OR N_LEASE_FROM_DATE IS NULL)
--AND Turnkey.Property_key= 223502

GROUP BY 
WO_DETAIL.TICKET_KEY
,WO_DETAIL.WORKORDER_KEY)

--SELECT * FROM WO_TURN 

--**************************************************************************************
,TURN_WO_SUMMARY AS (
SELECT 

WO_TURN.O_TURN_ID
,MIN(TICKET_CREATED_DATE) AS TKT_Created_Min
,MAX(TICKET_CREATED_DATE) AS TKT_Created_Max
,MAX(WO_NOTE_TEXT) AS WO_NOTE_TEXT
,MAX(WO_END_DATE) AS WO_END_DATE
,MAX(WO_REQUESTED_DATE) AS WO_REQUESTED_DATE
,MIN(WORKORDER_STATUS) AS WO_STATUS
,MAX(WO_NOTE_CREATED_DATE) AS WO_NOTE_CREATED_DATE
,MAX(WO_NOTE_ADDED_BY) AS WO_NOTE_ADDED_BY

,MAX(COALESCE(CLIENT_INVOICE_DATE,WO_CLOSED_DATE,VENDOR_INVOICE_DATE)) AS TKT_Closed_Max

,SUM(CASE WHEN (TICKET_STATUS = 'Open' AND WORKORDER_STATUS NOT IN ('Closed','Unbilled','Completed Awaiting Approval'))
			OR (TICKET_STATUS = 'New' AND WO_DETAIL.WORKORDER_KEY IS NULL) THEN 1 ELSE NULL END) AS TKT_WOS_OPEN
			
,SUM(CASE WHEN WORKORDER_STATUS IN ('Closed','Unbilled','Completed Awaiting Approval') THEN 1 ELSE NULL END) AS TKT_WOS_CLOSED

,MIN(CASE WHEN HC_TURN_REPORT_STATUS = 'Fail' AND TICKET_CREATED_DATE >= HC_TURN_COMPLETED_DATE
		THEN TICKET_CREATED_DATE ELSE NULL END ) AS TKT_Created_HARD_Fail
		
,MAX(CASE WHEN HC_TURN_REPORT_STATUS ='Fail' AND TICKET_CREATED_DATE >= HC_TURN_COMPLETED_DATE
		THEN COALESCE(CLIENT_INVOICE_DATE,WO_CLOSED_DATE,VENDOR_INVOICE_DATE) ELSE NULL END ) AS TKT_Closed_HARD_Fail
		
,MIN(CASE WHEN Turnkey.PASS_MINOR = 'Pass (Minor Fail)' AND TICKET_CREATED_DATE >= HC_TURN_COMPLETED_DATE
		THEN TICKET_CREATED_DATE ELSE NULL END ) AS TKT_Created_MINOR_Fail
		
,MAX(CASE WHEN Turnkey.PASS_MINOR = 'Pass (Minor Fail)' AND TICKET_CREATED_DATE >= HC_TURN_COMPLETED_DATE
		THEN COALESCE(CLIENT_INVOICE_DATE,WO_CLOSED_DATE,VENDOR_INVOICE_DATE) ELSE NULL END ) AS TKT_Closed_MINOR_Fail
		
,SUM(GREATEST(COALESCE(CLIENT_INVOICE_AMOUNT,CLIENT_ESTIMATE),COALESCE(CLIENT_ESTIMATE,CLIENT_INVOICE_AMOUNT))) AS TKT_COST

FROM WO_DETAIL
JOIN WO_TURN 
				ON WO_TURN.TICKET_KEY = WO_DETAIL.TICKET_KEY
				AND (CASE WHEN WO_DETAIL.WORKORDER_KEY IS NULL THEN 1=1
				ELSE WO_TURN.WORKORDER_KEY = WO_DETAIL.WORKORDER_KEY END)
								
LEFT JOIN Turnkey ON Turnkey.O_Turn_ID  =  WO_TURN.O_Turn_ID
				
GROUP BY
WO_TURN.O_TURN_ID
)
--SELECT * FROM TURN_WO_SUMMARY 
--WHERE O_TURN_ID =  23369
--**************************************************************************************

 
 SELECT
Turnkey.*
,f_listing.RENT_LIST_HIST_ID AS RENT_LIST_HIST_KEY
,d_listing.LISTING_DATE AS N_Listing_Date
,f_listing.CURRENT_LIST_PRICE AS N_Listing_Price
,d_listing.listing_status AS N_Listing_Status
,TKT_CREATED_MIN
,TKT_CREATED_MAX
,TKT_Closed_Max
,TKT_WOS_OPEN
,TKT_WOS_CLOSED
,TKT_CREATED_HARD_FAIL
,TKT_CLOSED_HARD_FAIL
,TKT_CREATED_MINOR_FAIL
,TKT_CLOSED_MINOR_FAIL
,WO_STATUS
,WO_END_DATE
,WO_REQUESTED_DATE
,WO_NOTE_TEXT
,WO_NOTE_CREATED_DATE
,WO_NOTE_ADDED_BY

,CASE WHEN (TKT_WOS_OPEN IS NULL OR HC_TURN_REPORT_STATUS ='Pass') AND PASS_MINOR IS NULL
	THEN COALESCE(TKT_COST,0)
	ELSE TKT_COST 
	END AS TKT_COST

,CASE WHEN (TKT_WOS_OPEN IS NULL OR HC_TURN_REPORT_STATUS ='Pass') AND (HC_TURN_COMPLETED_DATE IS NOT NULL OR N_LEASE_FROM_DATE IS NOT NULL OR TKT_Closed_Max IS NOT NULL)
      THEN LEAST(
                 COALESCE(HC_TURN_COMPLETED_DATE, '12/31/9999'::date),
                 COALESCE(N_LEASE_FROM_DATE, '12/31/9999'::date),
                 COALESCE(TKT_Closed_Max, '12/31/9999'::date))
      ELSE NULL
      END AS TURN_COMPLETED
      
,CASE WHEN (TKT_WOS_OPEN IS NULL OR HC_TURN_REPORT_STATUS ='Pass') AND (HC_TURN_COMPLETED_DATE IS NOT NULL OR N_LEASE_FROM_DATE IS NOT NULL OR TKT_Closed_Max IS NOT NULL)
      THEN DATE_TRUNC('month',
      			 LEAST(  
      			 COALESCE(HC_TURN_COMPLETED_DATE, '12/31/9999'::date),
                 COALESCE(N_LEASE_FROM_DATE, '12/31/9999'::date),
                 COALESCE(TKT_Closed_Max, '12/31/9999'::date)))::date
      ELSE NULL
      END AS TURN_COMPLETED_BOM
      
,CASE WHEN Turnkey.O_CURRENT_RENT > 0 AND COALESCE(Turnkey.N_INITIAL_RENT,Turnkey.N_CURRENT_RENT) >0  
      THEN DIV0NULL(COALESCE(Turnkey.N_INITIAL_RENT,Turnkey.N_CURRENT_RENT), Turnkey.O_CURRENT_RENT) - 1
	  ELSE NULL END AS RENT_GROWTH
	  
,CASE WHEN Turnkey.O_CURRENT_RENT > 0 AND f_listing.CURRENT_LIST_PRICE >0  
      THEN  DIV0NULL(COALESCE( f_listing.CURRENT_LIST_PRICE,Turnkey.N_CURRENT_RENT), Turnkey.O_CURRENT_RENT) - 1
	  ELSE NULL END AS RENT_GROWTH_LIST


,CASE WHEN Turnkey.O_Move_Out IS NOT NULL AND HC_SCOPE_COMPLETED_DATE IS NOT NULL THEN DATEDIFF(DAY, Turnkey.O_Move_Out, HC_SCOPE_COMPLETED_DATE) 
	  ELSE NULL END AS "Days_MoveOut_Scope"
	  
,CASE WHEN HC_SCOPE_COMPLETED_DATE IS NOT NULL AND TKT_CREATED_MIN IS NOT NULL THEN DATEDIFF(DAY,  HC_SCOPE_COMPLETED_DATE, TKT_CREATED_MIN) 
	  ELSE NULL END AS "Days_Scope_TKT_Created"
	  	  
,CASE WHEN TKT_CREATED_MIN IS NOT NULL AND TKT_Closed_Max IS NOT NULL THEN DATEDIFF(DAY, TKT_CREATED_MIN, TKT_Closed_Max) 
	  ELSE NULL END AS "Days_TKT_Created_TKT_Closed"
	  
,CASE WHEN Turnkey.O_Move_Out IS NOT NULL AND COALESCE(TKT_Closed_Max, HC_TURN_COMPLETED_DATE) IS NOT NULL THEN DATEDIFF(DAY, Turnkey.O_Move_Out, COALESCE(TKT_Closed_Max, HC_TURN_COMPLETED_DATE))
	  ELSE NULL END AS "Days_MO_TKT_Closed"
	  
,CASE WHEN TKT_Closed_Max IS NOT NULL AND HC_TURN_COMPLETED_DATE IS NOT NULL THEN DATEDIFF(DAY, TKT_Closed_Max, HC_TURN_COMPLETED_DATE) 
	  ELSE NULL END AS "Days_TKT_Closed_QC"
	  
,CASE WHEN d_listing.LISTING_DATE IS NOT NULL AND HC_TURN_COMPLETED_DATE IS NOT NULL THEN DATEDIFF(DAY, HC_TURN_COMPLETED_DATE, d_listing.LISTING_DATE) 
	  ELSE NULL END AS "Days_QC_List"
	  
,CASE WHEN Turnkey.O_Move_Out IS NOT NULL AND HC_TURN_COMPLETED_DATE IS NOT NULL THEN DATEDIFF(DAY, Turnkey.O_Move_Out, HC_TURN_COMPLETED_DATE)
	  ELSE NULL END AS "Days_MoveOut_Closed_QC"
	  
,CASE WHEN Turnkey.O_Move_Out IS NOT NULL AND d_listing.LISTING_DATE IS NOT NULL THEN DATEDIFF(DAY, COALESCE(Turnkey.O_Move_Out,O_AnticipatedMoveOutDate), d_listing.LISTING_DATE) 
	  ELSE NULL END AS "Days_MoveOut_List"
	  
,CASE WHEN Turnkey.O_Move_Out IS NOT NULL AND N_HOLDING_FEE_DATE IS NOT NULL THEN DATEDIFF(DAY, Turnkey.O_Move_Out, N_HOLDING_FEE_DATE) 
	  ELSE NULL END AS "Days_MoveOut_HoldingFee"

,CASE WHEN Turnkey.O_Move_Out IS NOT NULL AND N_MoveIn IS NOT NULL THEN DATEDIFF(DAY, Turnkey.O_Move_Out, N_MoveIn) 
	  ELSE NULL END AS "Days_MoveOut_MoveIn"
	  
,CASE WHEN N_MoveIn IS NULL THEN COALESCE (DATEDIFF(DAY, COALESCE(Turnkey.O_Move_Out,O_AnticipatedMoveOutDate), GETDATE()) , 0)
	  ELSE NULL END  AS "Days_ActiveInTurn"
	  
,CASE WHEN d_listing.LISTING_DATE IS NOT NULL THEN  DATEDIFF(DAY, d_listing.LISTING_DATE, COALESCE (N_MoveIn,GETDATE()) )
	  ELSE NULL END  AS "Days_On_Market"
	  
,CASE WHEN DATEDIFF(DAY, Turnkey.O_Move_Out, GETDATE()) <=30 THEN 'Under 30 Days' ELSE 'Over 30 Days' END AS MOVE_OUT_TIMING	  
	  
,CASE WHEN d_listing.listing_status IN ('Active') AND WO_END_DATE IS NOT NULL AND WO_END_DATE >= Listing_MI_READY_DATE AND  WO_END_DATE >= GETDATE()  THEN 'Push MIRD' ELSE NULL END AS MIRD_FLAG
	  
,DATE_TRUNC('month', d_listing.LISTING_DATE) AS "1_N_List (BOM)"
,DATE_TRUNC('month', N_MoveIn) AS "1_N_Lease_FROM (BOM)"
,d_listing.IS_PUBLISHED AS N_IS_PUBLISHED
,CASE WHEN Turnkey.MOVEOUTCOMPLETE = 'Yes' THEN COALESCE(MOC.MoveOutCharges,0.001) ELSE NULL END AS MoveOutCharges
,RANK () OVER( PARTITION BY Turnkey.Property_key ORDER BY f_listing.RENT_LIST_HIST_ID DESC) AS RECENT_TURN_RANK
,CASE WHEN N_LISTING_DATE IS NOT NULL AND N_MoveIn IS NULL THEN 1 ELSE NULL END AS ON_MARKET_FLAG 

,CASE WHEN Turnkey.MOVEOUTCOMPLETE = 'Yes' THEN COALESCE(MoveOutReceipts_PAID,0.001) + COALESCE(MoveOutReceipts_CONCESSION,0.001) ELSE NULL END AS MoveOutReceipts_Final
,CASE WHEN Turnkey.MOVEOUTCOMPLETE = 'Yes' THEN COALESCE(MOC.MoveOutCharges,0.001) - COALESCE(MoveOutReceipts_PAID,0.001) - COALESCE(MoveOutReceipts_CONCESSION,0.001) ELSE NULL END AS MoveOutReceipts_OUTSTANDING

,MoveOutReceipts_PAID
,MoveOutReceipts_CONCESSION
,MoveOutReceipts_BAD_DEBT
,MoveOutReceipts_TOTAL

,CASE WHEN HSP.PROPERTY_SEPTIC_FEE = '35' THEN 'Yes' ELSE NULL END AS SEPTIC_FLAG
,CONVERT_TIMEZONE('EST', SODA_COMPLETION_DATE::date) AS SODA_COMPLETION_DATE

FROM Turnkey
LEFT JOIN Turn_Listings TL ON TL.O_Turn_ID = Turnkey.O_Turn_ID AND TL.Property_Key = Turnkey.Property_key
left join PROD_ANALYTICS.DBT_RESICAP.FCT_PROP_RENTAL_LISTING_HIST f_listing on TL.rent_list_hist_key = f_listing.RENT_LIST_HIST_ID
left join PROD_ANALYTICS.DBT_RESICAP.DIM_LISTING d_listing on f_listing.LISTING_KEY = d_listing.LISTING_KEY and d_listing.CURRENT_FLAG = 'Y'
LEFT JOIN TURN_WO_SUMMARY TWS ON TWS.O_Turn_ID = Turnkey.O_Turn_ID 
LEFT JOIN MoveOutCharges MOC ON MOC.LeaseID = Turnkey.O_Turn_ID 
LEFT JOIN MoveOutReceipts MOR ON MOR.LeaseID = Turnkey.O_Turn_ID 
LEFT JOIN (
            SELECT
                UPPER(P.PROPERTY_ENTITY_ID) AS PROPERTY_ENTITY_ID
                ,P.PROPERTY_SEPTIC_FEE
                ,RANK () OVER(PARTITION BY UPPER(P.PROPERTY_ENTITY_ID) ORDER BY _FIVETRAN_SYNCED DESC) RANK 
                FROM PROD_REPLICA.HUBSPOT_2.PROPERTIES P
                QUALIFY Rank = 1 ) HSP ON HSP.PROPERTY_ENTITY_ID = Turnkey.EntityId

LEFT JOIN "PROD_ANALYTICS"."DBT_RESICAP"."FCT_TENANT_ACTIVITY" FTA ON FTA.Tenant_KEY = Turnkey.O_Tenant_KEY


WHERE 1=1
--AND Turnkey.EntityID = 'RPTX00219'
--AND Turnkey.O_Turn_ID = 23369