import { NextResponse } from "next/server";
import { connect } from "@/lib/snowflake";
import { PM_BOM_SQL, PM_LISTINGS_BOM_SQL } from "@/lib/pbi-sources";
import { DW_TURNS_SQL } from "@/lib/dw-turns-sql";
import SUMMARY_SNAPSHOT from "@/data/snapshots/summary.json";

// Allow the heavy Snowflake compute the maximum function time (Hobby cap = 60s).
export const maxDuration = 60;

// In-memory response cache. The Snowflake compute takes ~40-50s, so without
// this every page view (and every slicer change) would block that long. Keyed
// by the filter params; stale entries revalidate in the background so a warm
// key always returns instantly. `?fresh=1` forces a recompute.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const CACHE = new Map<string, { at: number; payload: any }>();
const TTL = 30 * 60 * 1000; // 30 min
const inflight = new Set<string>();

export async function GET(req: Request) {
  const url = new URL(req.url);
  const month = url.searchParams.get("month") || "May 2026";
  const orgFilter    = url.searchParams.get("org")    || "";
  const regionFilter = url.searchParams.get("region") || "";
  const statusFilter = url.searchParams.get("status") || "";
  const subFilter    = url.searchParams.get("subdivision") || "";
  const pmFilter     = url.searchParams.get("pm")     || "";
  const searchFilter = (url.searchParams.get("q")     || "").trim();
  const fresh = url.searchParams.get("fresh") === "1";

  // Serve the daily precomputed snapshot instantly for the default (current-
  // month, unfiltered) view — this is what makes the page load fast and avoids
  // the serverless timeout. Filtered/other-month requests and ?fresh=1 (used by
  // the nightly precompute job) fall through to a live Snowflake query.
  const isDefault = !orgFilter && !regionFilter && !statusFilter && !subFilter && !pmFilter && !searchFilter;
  if (!fresh && isDefault && (SUMMARY_SNAPSHOT as { selectedMonth?: string })?.selectedMonth === month) {
    return NextResponse.json(SUMMARY_SNAPSHOT);
  }

  const cacheKey = `${month}|${orgFilter}|${regionFilter}|${statusFilter}|${subFilter}|${pmFilter}|${searchFilter}`;
  const cached = CACHE.get(cacheKey);
  if (cached && !fresh) {
    // Serve instantly; kick a background revalidate if stale.
    if (Date.now() - cached.at > TTL && !inflight.has(cacheKey)) {
      inflight.add(cacheKey);
      const base = url.origin + url.pathname + `?month=${encodeURIComponent(month)}` +
        (orgFilter ? `&org=${encodeURIComponent(orgFilter)}` : "") +
        (regionFilter ? `&region=${encodeURIComponent(regionFilter)}` : "") +
        (statusFilter ? `&status=${encodeURIComponent(statusFilter)}` : "") +
        (subFilter ? `&subdivision=${encodeURIComponent(subFilter)}` : "") +
        (pmFilter ? `&pm=${encodeURIComponent(pmFilter)}` : "") +
        (searchFilter ? `&q=${encodeURIComponent(searchFilter)}` : "") + `&fresh=1`;
      fetch(base).catch(() => {}).finally(() => inflight.delete(cacheKey));
    }
    return NextResponse.json(cached.payload);
  }

  const [mon, yr] = month.split(" ");
  const MNUM: Record<string,number> = {Jan:1,Feb:2,Mar:3,Apr:4,May:5,Jun:6,Jul:7,Aug:8,Sep:9,Oct:10,Nov:11,Dec:12};
  const mNum = MNUM[mon] ?? 5;
  const yNum = parseInt(yr) || 2026;
  const startDate  = `${yNum}-${String(mNum).padStart(2,"0")}-01`;
  const endDate    = mNum===12 ? `${yNum+1}-01-01` : `${yNum}-${String(mNum+1).padStart(2,"0")}-01`;
  const bomDateKey = `${yNum}${String(mNum).padStart(2,"0")}01`;

  let conn: Awaited<ReturnType<typeof connect>> | null = null;
  try { conn = await connect(); }
  catch (e) { return NextResponse.json({ error:"Snowflake connection failed", detail:String(e) },{ status:500 }); }

  const errors: string[] = [];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const run = async (label:string, sql:string): Promise<any[]> => {
    try { return await conn!.query(sql); }
    catch (e) { errors.push(`${label}: ${(e as Error).message}`); return []; }
  };

  const ORG_CASE = `CASE
    WHEN PUS.ORGANIZATION_KEY IN (-1,18,26,28,48) THEN 'RP SFR'
    WHEN PUS.ORGANIZATION_KEY IN (27,50,51,52,54,45,55,53,56,57,66) THEN 'RB DRC'
    WHEN PUS.ORGANIZATION_KEY IN (58,59) THEN 'Hudson Oak'
    WHEN PUS.ORGANIZATION_KEY IN (62,63,64,65,68,69) THEN 'Rocklyn Homes'
    WHEN PUS.ORGANIZATION_KEY IN (61,70,71) THEN 'ROI Property Group'
    WHEN PUS.ORGANIZATION_KEY IN (72,73,74,75) THEN 'McKinley Homes'
    WHEN PUS.ORGANIZATION_KEY IN (67) THEN 'Newstar'
    ELSE O.ORGANIZATION_NAME END`;

  const orgWhere    = orgFilter    ? `AND (${ORG_CASE}) = '${orgFilter.replace(/'/g,"''")}'`    : "";
  const regionWhere = regionFilter ? `AND R.REGION_NAME = '${regionFilter.replace(/'/g,"''")}'` : "";
  const statusWhere = statusFilter ? `AND PUS.OCCUPANCY_STATUS = '${statusFilter.replace(/'/g,"''")}'` : "";
  const esc1 = (s: string) => s.replace(/'/g, "''");
  // Subdivision: match by key so no extra join alias is needed in any query.
  const subWhere = subFilter
    ? `AND PUS.SUBDIVISION_KEY IN (SELECT SUBDIVISION_KEY FROM PROD_ANALYTICS.DBT_RESICAP.DIM_SUBDIVISION WHERE SUBDIVISION='${esc1(subFilter)}' AND CURRENT_FLAG='Y')`
    : "";
  // Property Manager: HBPM.ASSIGNEDUSERID → USERS full name (BASE already joins HBPM).
  const pmWhere = pmFilter
    ? (pmFilter === "(Blank)"
        ? `AND HBPM.ASSIGNEDUSERID IS NULL`
        : `AND HBPM.ASSIGNEDUSERID IN (SELECT USERID FROM PROD_REPLICA.HBPM_DBO.USERS WHERE FirstName||' '||LastName='${esc1(pmFilter)}')`)
    : "";
  // Address search: substring match on street address or EntityID.
  const searchWhere = searchFilter
    ? `AND (P.ADDRESS ILIKE '%${esc1(searchFilter)}%' OR P.EntityID ILIKE '%${esc1(searchFilter)}%')`
    : "";

  const BASE = `
    LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY=PUS.PROPERTY_KEY AND P.CURRENT_FLAG='Y'
    LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY=PUS.PORTFOLIO_KEY
    LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY=PUS.PROPERTY_UNIT_KEY
    LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_REGION R ON R.REGION_KEY=PUS.REGION_KEY
    LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_OWNER_ORGANIZATION O ON O.ORGANIZATION_KEY=PUS.ORGANIZATION_KEY
    LEFT JOIN PROD_REPLICA.HBAM_DBO.PROPERTIES HBAM ON HBAM.HBID=P.HBAM_PROPERTY_ID
    LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTIES HBPM ON HBPM.PROPERTYID=P.HBPM_PROPERTY_ID`;

  const FILT = `
    PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54)
    AND PUS.Organization_KEY NOT IN (16,17) AND PO.IS_Active_AM='Y' AND PO.Current_Flag='Y'
    AND P.Current_Flag='Y' AND PU.Current_Flag='Y'
    AND PUS.Occupancy_Status NOT IN ('Not Managed','Dispositions')
    AND (HBPM.PROPERTYSTATEID=26 OR HBPM.PROPERTYSTATEID IS NULL)
    AND (HBAM.PROPERTYSTATUSID>9 OR HBAM.PROPERTYSTATUSID IS NULL)
    AND (HBAM.PROPERTYSTATUSID NOT IN (53,75) OR HBAM.PROPERTYSTATUSID IS NULL)
    AND P.PROPERTY_STATE='Active' AND P.EntityID<>''
    ${orgWhere} ${regionWhere} ${statusWhere} ${subWhere} ${pmWhere} ${searchWhere}`;

  // ── KPI 1: EOM Occupancy ──────────────────────────────────────────────────
  const eomOccRaw = await run("eom-occ", `
    SELECT
      COUNT(DISTINCT T.PK) AS OCCUPIED,
      COUNT(DISTINCT PUS.PROPERTY_KEY) AS STABILIZED,
      ROUND(COUNT(DISTINCT T.PK)*100.0/NULLIF(COUNT(DISTINCT PUS.PROPERTY_KEY),0),1) AS OCC_PCT
    FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ${BASE}
    LEFT JOIN (
      SELECT DISTINCT TS2.PROPERTY_KEY AS PK
      FROM PROD_ANALYTICS.DBT_RESICAP.DIM_TENANT T2
      JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_ACTIVITY TS2 ON TS2.TENANT_KEY=T2.TENANT_KEY
      WHERE T2.CURRENT_FLAG='Y' AND T2.PRIMARY_TENANT='Y'
    ) T ON T.PK=PUS.PROPERTY_KEY
    WHERE ${FILT}`);
  const stabilized = Number(eomOccRaw[0]?.STABILIZED ?? 0);
  const occupied   = Number(eomOccRaw[0]?.OCCUPIED   ?? 0);
  void stabilized; void occupied;
  const eomOccupancy = eomOccRaw[0]?.OCC_PCT!=null ? Number(eomOccRaw[0].OCC_PCT) : null;

  // ── KPI 2: BOM Listings Leased ────────────────────────────────────────────
  const bomListRaw = await run("bom-listings", `
    SELECT
      COUNT(DISTINCT CASE WHEN FIRST_LEASE_START_DATE_POST_LAST_LISTING BETWEEN '${startDate}' AND '${endDate}' THEN PUS.PROPERTY_KEY END) AS MOVEIN,
      COUNT(DISTINCT CASE WHEN CURRENT_CYCLE_ORIGINAL_LISTING_DATE <= '${startDate}'
        AND (FIRST_LEASE_START_DATE_POST_LAST_LISTING IS NULL OR FIRST_LEASE_START_DATE_POST_LAST_LISTING >= '${endDate}')
        THEN PUS.PROPERTY_KEY END) AS ON_MARKET_AT_BOM
    FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS
    LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY=PUS.PROPERTY_KEY AND P.CURRENT_FLAG='Y'
    LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY=PUS.PORTFOLIO_KEY
    LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY=PUS.PROPERTY_UNIT_KEY
    LEFT JOIN PROD_REPLICA.HBAM_DBO.PROPERTIES HBAM ON HBAM.HBID=P.HBAM_PROPERTY_ID
    LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTIES HBPM ON HBPM.PROPERTYID=P.HBPM_PROPERTY_ID
    WHERE P.PROPERTY_STATE='Active' AND P.EntityID<>'' AND P.CURRENT_FLAG='Y'
    AND PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54)
    AND PUS.Organization_KEY NOT IN (16,17) AND PO.IS_Active_AM='Y' AND PO.Current_Flag='Y'
    AND P.Current_Flag='Y' AND PU.Current_Flag='Y'
    AND PUS.Occupancy_Status NOT IN ('Not Managed','Dispositions')
    AND (HBPM.PROPERTYSTATEID=26 OR HBPM.PROPERTYSTATEID IS NULL)
    AND (HBAM.PROPERTYSTATUSID>9 OR HBAM.PROPERTYSTATUSID IS NULL)
    AND (HBAM.PROPERTYSTATUSID NOT IN (53,75) OR HBAM.PROPERTYSTATUSID IS NULL)`);
  const moveIn      = Number(bomListRaw[0]?.MOVEIN ?? 0);
  const onMarketBOM = Number(bomListRaw[0]?.ON_MARKET_AT_BOM ?? 0);
  let bomListingsLeased = (onMarketBOM+moveIn)>0 ? Math.round(moveIn/(onMarketBOM+moveIn)*1000)/10 : null;

  // ── Region table ──────────────────────────────────────────────────────────
  const regionRaw = await run("region", `
    SELECT R.REGION_NAME,
      COUNT(*) AS TOTAL,
      COUNT(CASE WHEN PUS.OCCUPANCY_STATUS IN ('Vacant - Off Market','Vacant - Onboarding') THEN 1 END) AS VACANT_OFF,
      COUNT(CASE WHEN PUS.OCCUPANCY_STATUS IN ('Vacant - On Market','Vacant - Pre-Leasing') THEN 1 END) AS VACANT_ON,
      COUNT(CASE WHEN PUS.OCCUPANCY_STATUS='Vacant - Future Move In' THEN 1 END) AS VACANT_FMI,
      COUNT(CASE WHEN PUS.OCCUPANCY_STATUS IN ('Trustee Lease Honored','Trustee Leased') THEN 1 END) AS TRUSTEE,
      COUNT(CASE WHEN PUS.OCCUPANCY_STATUS='Tenant Leased' THEN 1 END) AS TENANT,
      COUNT(CASE WHEN PUS.OCCUPANCY_STATUS IN ('Pending MOI/Rekey','Under Turnkey') THEN 1 END) AS TURNKEY
    FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ${BASE}
    WHERE ${FILT} GROUP BY R.REGION_NAME ORDER BY TOTAL DESC`);
  const regionRows = regionRaw.map(r=>({
    region:String(r.REGION_NAME??"Unknown"), vacantOff:Number(r.VACANT_OFF??0), vacantOn:Number(r.VACANT_ON??0),
    vacantFMI:Number(r.VACANT_FMI??0), trustee:Number(r.TRUSTEE??0), tenant:Number(r.TENANT??0),
    turnkey:Number(r.TURNKEY??0), total:Number(r.TOTAL??0),
  }));
  const totalProps = regionRows.reduce((a,r)=>a+r.total,0);

  // ── Active Listings ───────────────────────────────────────────────────────
  const listRaw = await run("listings", `
    SELECT COUNT(DISTINCT RLH.PROPERTY_KEY) AS CNT
    FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROP_RENTAL_LISTING_HIST RLH
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_LISTING DL ON DL.LISTING_KEY=RLH.LISTING_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY=RLH.PROPERTY_KEY
    ${BASE} WHERE RLH.LISTING_STATUS='Active' AND DL.IS_PUBLISHED='Y' AND ${FILT}`);
  const activeListings = Number(listRaw[0]?.CNT??0);

  // ── KPI 3: EOM Collections ────────────────────────────────────────────────
  const collRaw = await run("collections", `
    SELECT ROUND(DIV0(SUM(PAID_AMOUNT),SUM(AMOUNT))*100,1) AS PCT
    FROM PROD_ANALYTICS.DBT_RESICAP.FCT_LEASING_TRANSACTION
    WHERE GL_ACCOUNT_KEY=25 AND COALESCE(CREDIT_TYPE_ID,0)<>2 AND TRANSACTION_TYPE='Charges'
    AND TO_DATE(CHARGE_DATE_KEY::TEXT,'YYYYMMDD')>='${startDate}'
    AND TO_DATE(CHARGE_DATE_KEY::TEXT,'YYYYMMDD')<'${endDate}'`);
  const eomCollections = collRaw[0]?.PCT!=null ? Number(collRaw[0].PCT) : null;

  // ── KPI 4: Renewal ────────────────────────────────────────────────────────
  const renewalRaw = await run("renewal", `
    SELECT ROUND(COUNT(CASE WHEN RR='Renewed' THEN 1 END)*100.0/NULLIF(COUNT(*),0),1) AS PCT
    FROM (
      SELECT
        CASE
          WHEN TI.MOVEOUT IS NOT NULL AND TI.MOVEOUT < DATEADD(DAY,-30,TLH.LEASEEND)
               AND TI.REASONFORNOTRENEWINGID IN (3156,3157) THEN 'EV'
          WHEN TI.MOVEOUT IS NOT NULL AND TI.MOVEOUT < DATEADD(DAY,-30,TLH.LEASEEND) THEN 'EV'
          WHEN TLH_N.LEASESIGNED IS NOT NULL OR TI.REASONFORNOTRENEWINGID=3164 THEN 'Renewed'
          ELSE 'Other'
        END AS RR
      FROM PROD_REPLICA.HBPM_DBO.TENANTLEASINGHISTORIES TLH
      LEFT JOIN (SELECT TENANTLEASINGHISTORYID,TENANTINFORMATIONID,
                  RANK() OVER(PARTITION BY TENANTINFORMATIONID ORDER BY TENANTLEASINGHISTORYID ASC) AS LR
                 FROM PROD_REPLICA.HBPM_DBO.TENANTLEASINGHISTORIES WHERE _FIVETRAN_DELETED<>'Y') LR
                 ON LR.TENANTLEASINGHISTORYID=TLH.TENANTLEASINGHISTORYID
      LEFT JOIN (SELECT TENANTLEASINGHISTORYID,TENANTINFORMATIONID,
                  RANK() OVER(PARTITION BY TENANTINFORMATIONID ORDER BY TENANTLEASINGHISTORYID ASC) AS LR
                 FROM PROD_REPLICA.HBPM_DBO.TENANTLEASINGHISTORIES WHERE _FIVETRAN_DELETED<>'Y') LR_N
                 ON LR_N.TENANTINFORMATIONID=TLH.TENANTINFORMATIONID AND LR_N.LR=LR.LR+1
      LEFT JOIN PROD_REPLICA.HBPM_DBO.TENANTLEASINGHISTORIES TLH_N
                 ON TLH_N.TENANTLEASINGHISTORYID=LR_N.TENANTLEASINGHISTORYID AND TLH._FIVETRAN_DELETED<>'Y'
      LEFT JOIN PROD_REPLICA.HBPM_DBO.TENANTINFORMATIONS TI ON TI.TenantInformationId=TLH.TenantInformationId
      LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTYADDLINFOES PAI ON PAI.UnitId=TI.UnitId AND PAI."_FIVETRAN_DELETED"='N'
      LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTIES HBPM2 ON HBPM2.PropertyId=PAI.PropertyId
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.HBPM_PROPERTY_ID=HBPM2.PROPERTYID AND P.CURRENT_FLAG='Y'
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY=P.PROPERTY_KEY
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY=PUS.PORTFOLIO_KEY
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY=PUS.PROPERTY_UNIT_KEY
      WHERE TI.PrimaryTenant=1 AND TLH._FIVETRAN_DELETED<>'Y'
      AND DATE_TRUNC('month',TLH.LEASEEND::DATE)='${startDate}'
      AND P.PROPERTY_STATE='Active' AND P.EntityID<>''
      AND PO.Portfolio_KEY NOT IN (1845,2210,2207,2218,1952,1867,1916,1852,1771,1919,1873)
      AND P.Organization_KEY NOT IN (16,17) AND PO.IS_Active_AM='Y' AND PO.Current_Flag='Y'
      AND P.Current_Flag='Y' AND PU.Current_Flag='Y'
      AND PUS.Occupancy_Status NOT IN ('Property SOLD','Not Managed')
    ) WHERE RR <> 'EV'`);
  const renewal = renewalRaw[0]?.PCT!=null ? Number(renewalRaw[0].PCT) : null;

  // ── KPI 5: WO Cycle Time ──────────────────────────────────────────────────
  const woCycleRaw = await run("wo-cycle-time", `
    SELECT ROUND(AVG(CT),1) AS CYCLE_TIME FROM (
      SELECT DISTINCT TI.TICKET_KEY,
        DATEDIFF(DAY,TO_DATE(TI.CREATED_DATE_KEY::TEXT,'YYYYMMDD'),
          COALESCE(TO_DATE(WOI.VENDOR_INVOICE_DATE_KEY::TEXT,'YYYYMMDD'),TO_DATE(WOST.WO_CLOSED_DATE_KEY::TEXT,'YYYYMMDD'))) AS CT,
        DATE_TRUNC('month',COALESCE(TO_DATE(WOST.WO_CLOSED_DATE_KEY::TEXT,'YYYYMMDD'),TO_DATE(WOST.WO_CANCELLED_DATE_KEY::TEXT,'YYYYMMDD'))) AS CLOSED_BOM
      FROM PROD_ANALYTICS.DBT_RESICAP.DIM_TICKET TI
      JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TICKET_STATUS_ACCUM TSA ON TSA.TICKET_KEY=TI.TICKET_KEY
      JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY=TSA.PROPERTY_KEY AND P.CURRENT_FLAG='Y'
      JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY=P.PROPERTY_KEY
      JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY=PUS.PORTFOLIO_KEY
      JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY=PUS.PROPERTY_UNIT_KEY
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_WO_STATUS_ACCUM WOST ON WOST.TICKET_KEY=TI.TICKET_KEY
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_WORKORDER WO ON WO.WORKORDER_KEY=WOST.WORKORDER_KEY AND WO.CURRENT_FLAG='Y'
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_WO_INVOICE WOI ON WOI.WORKORDER_KEY=WO.WORKORDER_KEY
      WHERE COALESCE(WO.WORKORDER_STATUS,TI.TICKET_STATUS)='Closed' AND TI.CREATED_DATE_KEY>'20220101'
      AND PO.Portfolio_KEY NOT IN (1845,2210,2207,2218,1952,1867,1916,1852,1771,1919,1873)
      AND PUS.Organization_KEY NOT IN (16,17) AND PO.IS_Active_AM='Y' AND PO.Current_Flag='Y'
      AND P.Current_Flag='Y' AND PU.Current_Flag='Y'
      AND PUS.Occupancy_Status NOT IN ('Property SOLD','Not Managed')
    ) WHERE CLOSED_BOM='${startDate}' AND CT IS NOT NULL`);
  const woCycleTime = woCycleRaw[0]?.CYCLE_TIME!=null ? Number(woCycleRaw[0].CYCLE_TIME) : null;

  // ── KPI 6: Internal Maintenance ───────────────────────────────────────────
  const imRaw = await run("internal-maint", `
    SELECT ROUND(SUM(CASE WHEN WO.WORKORDER_STATUS='Closed' THEN ZEROIFNULL(WOI.CLIENT_INVOICE_AMOUNT)
                          ELSE WOI.CLIENT_INVOICE_AMOUNT END),0) AS IM
    FROM PROD_ANALYTICS.DBT_RESICAP.DIM_TICKET TI
    JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TICKET_STATUS_ACCUM TSA ON TSA.TICKET_KEY=TI.TICKET_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY=TSA.PROPERTY_KEY AND P.CURRENT_FLAG='Y'
    JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY=P.PROPERTY_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY=PUS.PORTFOLIO_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY=PUS.PROPERTY_UNIT_KEY
    LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_WO_STATUS_ACCUM WOST ON WOST.TICKET_KEY=TI.TICKET_KEY
    LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_WORKORDER WO ON WO.WORKORDER_KEY=WOST.WORKORDER_KEY AND WO.CURRENT_FLAG='Y'
    LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_VENDOR V ON V.VENDOR_KEY=WOST.VENDOR_KEY
    LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_WO_INVOICE WOI ON WOI.WORKORDER_KEY=WO.WORKORDER_KEY
    WHERE COALESCE(WO.WORKORDER_STATUS,TI.TICKET_STATUS)='Closed' AND V.IS_INTERNAL_VENDOR='Y'
    AND COALESCE(V.COMPANY_NAME,'') NOT IN ('Credit Card Vendor','New Builder Warranty Vendor','Lennar Builder Warranty','GE Vendor (Maintenance)')
    AND DATE_TRUNC('month',COALESCE(TO_DATE(WOST.WO_CLOSED_DATE_KEY::TEXT,'YYYYMMDD'),TO_DATE(WOST.WO_CANCELLED_DATE_KEY::TEXT,'YYYYMMDD')))='${startDate}'
    AND TI.CREATED_DATE_KEY>'20220101'
    AND PO.Portfolio_KEY NOT IN (1845,2210,2207,2218,1952,1867,1916,1852,1771,1919,1873)
    AND PUS.Organization_KEY NOT IN (16,17) AND PO.IS_Active_AM='Y' AND PO.Current_Flag='Y'
    AND P.Current_Flag='Y' AND PU.Current_Flag='Y'
    AND PUS.Occupancy_Status NOT IN ('Property SOLD','Not Managed')`);
  const internalMaintenance = imRaw[0]?.IM!=null ? Number(imRaw[0].IM) : null;

  // ── KPI 7: Net Turn Cost ──────────────────────────────────────────────────
  const netTurnRaw = await run("net-turn-cost", `
    WITH TENANT_ALL AS (
      SELECT T.TENANT_KEY, T.LEASE_ID AS O_TURN_ID, TS2.PROPERTY_KEY,
        TI.MoveOut AS O_MOVE_OUT, TI.MoveOutComplte AS MOVEOUTCOMPLETE
      FROM PROD_ANALYTICS.DBT_RESICAP.DIM_TENANT T
      JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_ACTIVITY TS2 ON TS2.TENANT_KEY=T.TENANT_KEY
      JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY=TS2.PROPERTY_KEY AND P.CURRENT_FLAG='Y'
      JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY=P.PROPERTY_KEY
      JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY=PUS.PORTFOLIO_KEY
      JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY=PUS.PROPERTY_UNIT_KEY
      LEFT JOIN PROD_REPLICA.HBPM_DBO.TENANTINFORMATIONS TI ON TI.TenantInformationId=T.TENANT_INFORMATION_ID
      WHERE T.PRIMARY_TENANT='Y' AND P.PROPERTY_STATE='Active' AND P.EntityID<>''
      AND TI._FIVETRAN_DELETED<>'Y' AND TI.RENTDUEDAY IS NOT NULL
      AND PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54,169)
      AND P.Organization_KEY NOT IN (16,17) AND PO.IS_Active_AM='Y' AND PO.Current_Flag='Y'
      AND P.Current_Flag='Y' AND PU.Current_Flag='Y'
      AND PUS.Occupancy_Status NOT IN ('Property SOLD','Not Managed')
      AND TI.MoveOut IS NOT NULL
    ),
    NEXT_LEASE AS (
      SELECT PROPERTY_KEY, TO_DATE(LEASE_START_DATE_KEY::TEXT,'YYYYMMDD') AS LEASE_START
      FROM PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_LEASING_HIST
    ),
    TURN_PAIRS AS (
      SELECT C.O_TURN_ID, C.TENANT_KEY, C.PROPERTY_KEY, C.O_MOVE_OUT, C.MOVEOUTCOMPLETE,
        N.LEASE_START AS N_LEASE_FROM_DATE
      FROM TENANT_ALL C
      LEFT JOIN NEXT_LEASE N ON N.PROPERTY_KEY=C.PROPERTY_KEY AND N.LEASE_START > C.O_MOVE_OUT
      QUALIFY ROW_NUMBER() OVER (PARTITION BY C.O_TURN_ID ORDER BY N.LEASE_START ASC) = 1
    ),
    TURN_WO AS (
      SELECT TP.O_TURN_ID,
        SUM(GREATEST(ZEROIFNULL(WOI.CLIENT_INVOICE_AMOUNT),0)) AS TKT_COST,
        MAX(COALESCE(TO_DATE(WOI.CLIENT_INVOICE_DATE_KEY::TEXT,'YYYYMMDD'),TO_DATE(WOST.WO_CLOSED_DATE_KEY::TEXT,'YYYYMMDD'))) AS TKT_CLOSED_MAX
      FROM TURN_PAIRS TP
      JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TICKET_STATUS_ACCUM TSA ON TSA.PROPERTY_KEY=TP.PROPERTY_KEY
      JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_TICKET TI ON TI.TICKET_KEY=TSA.TICKET_KEY
        AND TI.TICKET_TYPE='Turnkey' AND TI.CREATED_DATE_KEY>'20210101'
        AND TO_DATE(TI.CREATED_DATE_KEY::TEXT,'YYYYMMDD') >= DATEADD('day',-5,TP.O_MOVE_OUT)
        AND (TO_DATE(TI.CREATED_DATE_KEY::TEXT,'YYYYMMDD') <= TP.N_LEASE_FROM_DATE OR TP.N_LEASE_FROM_DATE IS NULL)
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_WO_STATUS_ACCUM WOST ON WOST.TICKET_KEY=TI.TICKET_KEY
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_WORKORDER WO ON WO.WORKORDER_KEY=WOST.WORKORDER_KEY AND WO.CURRENT_FLAG='Y'
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_WO_INVOICE WOI ON WOI.WORKORDER_KEY=WO.WORKORDER_KEY
      WHERE COALESCE(WO.WORKORDER_STATUS,TI.TICKET_STATUS)<>'Cancelled'
      GROUP BY TP.O_TURN_ID
    ),
    MOR AS (
      SELECT TENANT_KEY,
        SUM(CASE WHEN CREDIT_TYPE_ID IS NULL THEN AMOUNT ELSE 0 END) AS MOR_PAID,
        SUM(CASE WHEN CREDIT_TYPE_ID=1 THEN AMOUNT ELSE 0 END) AS MOR_CONCESSION
      FROM PROD_ANALYTICS.DBT_RESICAP.FCT_LEASING_TRANSACTION
      WHERE TRANSACTION_TYPE='Payment' AND CHARGE_GL_ACCOUNT_NUMBER='4016'
      AND STATUS='Active' AND IS_CREDIT='N' AND TENANT_KEY IS NOT NULL
      GROUP BY TENANT_KEY
    )
    SELECT COUNT(*) AS TURN_COUNT, ROUND(AVG(NET_TURN_COST),0) AS AVG_NET_TURN_COST
    FROM (
      SELECT TP.O_TURN_ID,
        DATE_TRUNC('month',LEAST(COALESCE(TP.N_LEASE_FROM_DATE,'9999-12-31'::DATE),COALESCE(WO.TKT_CLOSED_MAX,'9999-12-31'::DATE))) AS TURN_COMPLETED_BOM,
        GREATEST(COALESCE(WO.TKT_COST,0)-COALESCE(CASE WHEN TP.MOVEOUTCOMPLETE='Y'
          THEN COALESCE(MOR.MOR_PAID,0)+COALESCE(MOR.MOR_CONCESSION,0) ELSE 0 END,0),0) AS NET_TURN_COST
      FROM TURN_PAIRS TP
      LEFT JOIN TURN_WO WO ON WO.O_TURN_ID=TP.O_TURN_ID
      LEFT JOIN MOR ON MOR.TENANT_KEY=TP.TENANT_KEY
      WHERE TP.N_LEASE_FROM_DATE IS NOT NULL
    ) WHERE TURN_COMPLETED_BOM='${startDate}'`);
  let netTurnCost = netTurnRaw[0]?.AVG_NET_TURN_COST!=null ? Number(netTurnRaw[0].AVG_NET_TURN_COST) : null;

  // ── KPI 8: 90+ Run Rate Spend ─────────────────────────────────────────────
  const runRateRaw = await run("run-rate", `
    SELECT ROUND(SUM(PROP_SPEND)/NULLIF(SUM(DAYS_POST_90),0)*365,0) AS RUN_RATE
    FROM (
      SELECT P.PROPERTY_KEY,
        GREATEST(0,DATEDIFF('day',GREATEST(DATEADD('day',90,P.FIRST_LEASE_START_DATE_POST_RRQC),'${startDate}'),'${endDate}')) AS DAYS_POST_90,
        COALESCE(S.SPEND,0) AS PROP_SPEND
      FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS
      JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY=PUS.PROPERTY_KEY AND P.CURRENT_FLAG='Y'
      JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY=PUS.PORTFOLIO_KEY
      JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY=PUS.PROPERTY_UNIT_KEY
      LEFT JOIN PROD_REPLICA.HBAM_DBO.PROPERTIES HBAM ON HBAM.HBID=P.HBAM_PROPERTY_ID
      LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTIES HBPM ON HBPM.PROPERTYID=P.HBPM_PROPERTY_ID
      LEFT JOIN (
        SELECT TSA.PROPERTY_KEY, SUM(WOI.CLIENT_INVOICE_AMOUNT) AS SPEND
        FROM PROD_ANALYTICS.DBT_RESICAP.FCT_TICKET_STATUS_ACCUM TSA
        JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_TICKET TI ON TI.TICKET_KEY=TSA.TICKET_KEY AND TI.CREATED_DATE_KEY>'20220101'
          AND COALESCE(TI.TICKET_TYPE,'Maintenance') NOT IN ('Turnkey','PPI','Evictions')
        JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_WO_STATUS_ACCUM WOST ON WOST.TICKET_KEY=TI.TICKET_KEY
        JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_WORKORDER WO ON WO.WORKORDER_KEY=WOST.WORKORDER_KEY
          AND WO.CURRENT_FLAG='Y' AND WO.WORKORDER_STATUS='Closed'
        JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_WO_INVOICE WOI ON WOI.WORKORDER_KEY=WO.WORKORDER_KEY
        WHERE DATE_TRUNC('month',COALESCE(TO_DATE(WOST.WO_CLOSED_DATE_KEY::TEXT,'YYYYMMDD'),TO_DATE(WOST.WO_CANCELLED_DATE_KEY::TEXT,'YYYYMMDD')))='${startDate}'
        GROUP BY TSA.PROPERTY_KEY
      ) S ON S.PROPERTY_KEY=P.PROPERTY_KEY
      WHERE P.PROPERTY_STATE='Active' AND P.EntityID<>'' AND P.CURRENT_FLAG='Y'
      AND PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54)
      AND PUS.Organization_KEY NOT IN (16,17) AND PO.IS_Active_AM='Y' AND PO.Current_Flag='Y'
      AND P.Current_Flag='Y' AND PU.Current_Flag='Y'
      AND PUS.Occupancy_Status NOT IN ('Not Managed','Dispositions')
      AND (HBPM.PROPERTYSTATEID=26 OR HBPM.PROPERTYSTATEID IS NULL)
      AND (HBAM.PROPERTYSTATUSID>9 OR HBAM.PROPERTYSTATUSID IS NULL)
      AND (HBAM.PROPERTYSTATUSID NOT IN (53,75) OR HBAM.PROPERTYSTATUSID IS NULL)
      AND P.FIRST_LEASE_START_DATE_POST_RRQC IS NOT NULL
      AND DATEADD('day',90,P.FIRST_LEASE_START_DATE_POST_RRQC)<'${endDate}'
    ) WHERE DAYS_POST_90>0`);
  const runRateSpend = runRateRaw[0]?.RUN_RATE!=null ? Number(runRateRaw[0].RUN_RATE) : null;

  // ── Portfolio Metrics ─────────────────────────────────────────────────────
  const pmBomRaw = await run("pm-bom", `
    WITH BOM_SNAP AS (
      SELECT H.PROPERTY_KEY, H.NEW_OCCUPANCY_STATUS_ID AS STATUS_ID,
        ROW_NUMBER() OVER (PARTITION BY H.PROPERTY_KEY ORDER BY H.CHANGED_DATE_KEY DESC) AS RNK
      FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROP_UNIT_STATUS_HIST H WHERE H.CHANGED_DATE_KEY < ${bomDateKey}
    ),
    PROPS AS (
      SELECT DISTINCT P.PROPERTY_KEY, PUS.OCCUPANCY_STATUS_ID AS CURR_ID
      FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY=PUS.PROPERTY_KEY AND P.CURRENT_FLAG='Y'
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY=PUS.PORTFOLIO_KEY
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY=PUS.PROPERTY_UNIT_KEY
      LEFT JOIN PROD_REPLICA.HBAM_DBO.PROPERTIES HBAM ON HBAM.HBID=P.HBAM_PROPERTY_ID
      LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTIES HBPM ON HBPM.PROPERTYID=P.HBPM_PROPERTY_ID
      WHERE P.PROPERTY_STATE='Active' AND P.EntityID<>'' AND P.CURRENT_FLAG='Y'
      AND PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54)
      AND PUS.Organization_KEY NOT IN (16,17) AND PO.IS_Active_AM='Y' AND PO.Current_Flag='Y'
      AND P.Current_Flag='Y' AND PU.Current_Flag='Y'
      AND PUS.Occupancy_Status NOT IN ('Not Managed','Dispositions')
      AND (HBPM.PROPERTYSTATEID=26 OR HBPM.PROPERTYSTATEID IS NULL)
      AND (HBAM.PROPERTYSTATUSID>9 OR HBAM.PROPERTYSTATUSID IS NULL)
      AND (HBAM.PROPERTYSTATUSID NOT IN (53,75) OR HBAM.PROPERTYSTATUSID IS NULL)
    ),
    EFF AS (
      SELECT P.PROPERTY_KEY, COALESCE(B.STATUS_ID,P.CURR_ID) AS EFF_ID
      FROM PROPS P LEFT JOIN BOM_SNAP B ON B.PROPERTY_KEY=P.PROPERTY_KEY AND B.RNK=1
    )
    SELECT
      COUNT(DISTINCT CASE WHEN EFF_ID IN (1477,10000) THEN PROPERTY_KEY END) AS BOM_LISTINGS,
      COUNT(DISTINCT CASE WHEN EFF_ID IN (1476,1477,1478,1483,1489,10000) THEN PROPERTY_KEY END) AS BOM_VACANT,
      COUNT(DISTINCT CASE WHEN EFF_ID IN (1479,1480,1481) THEN PROPERTY_KEY END) AS BOM_OCCUPIED
    FROM EFF`);

  const hfRaw = await run("hf", `
    SELECT COUNT(DISTINCT D.EMAIL) AS CNT
    FROM PROD_ANALYTICS.DBT_RESICAP.DIM_DEAL D
    JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_DEAL_STATUS_ACCUM DSH ON DSH.DEAL_KEY=D.DEAL_KEY
    WHERE TO_DATE(DSH.HOLDING_FEE_PAID_DATE_KEY::TEXT,'YYYYMMDD')>='${startDate}'
    AND TO_DATE(DSH.HOLDING_FEE_PAID_DATE_KEY::TEXT,'YYYYMMDD')<'${endDate}' AND D.EMAIL IS NOT NULL`);
  const holdingFees = Number(hfRaw[0]?.CNT??0);

  const misRaw = await run("mis", `
    SELECT COUNT(DISTINCT TLH.PROPERTY_KEY) AS CNT
    FROM PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_LEASING_HIST TLH
    JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY=TLH.PROPERTY_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY=PUS.PORTFOLIO_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY=PUS.PROPERTY_UNIT_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY=TLH.PROPERTY_KEY AND P.CURRENT_FLAG='Y'
    LEFT JOIN PROD_REPLICA.HBAM_DBO.PROPERTIES HBAM ON HBAM.HBID=P.HBAM_PROPERTY_ID
    LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTIES HBPM ON HBPM.PROPERTYID=P.HBPM_PROPERTY_ID
    WHERE TO_DATE(TLH.LEASE_START_DATE_KEY::TEXT,'YYYYMMDD')>='${startDate}'
    AND TO_DATE(TLH.LEASE_START_DATE_KEY::TEXT,'YYYYMMDD')<'${endDate}' AND TLH.IS_RENEWAL='N'
    AND P.PROPERTY_STATE='Active' AND P.EntityID<>'' AND P.CURRENT_FLAG='Y'
    AND PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54)
    AND PUS.Organization_KEY NOT IN (16,17) AND PO.IS_Active_AM='Y' AND PO.Current_Flag='Y'
    AND P.Current_Flag='Y' AND PU.Current_Flag='Y'
    AND PUS.Occupancy_Status NOT IN ('Not Managed','Dispositions')
    AND (HBPM.PROPERTYSTATEID=26 OR HBPM.PROPERTYSTATEID IS NULL)
    AND (HBAM.PROPERTYSTATUSID>9 OR HBAM.PROPERTYSTATUSID IS NULL)
    AND (HBAM.PROPERTYSTATUSID NOT IN (53,75) OR HBAM.PROPERTYSTATUSID IS NULL)`);

  const mosRaw = await run("mos", `
    SELECT COUNT(DISTINCT H.PROPERTY_KEY) AS CNT
    FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROP_UNIT_STATUS_HIST H
    JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY=H.PROPERTY_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY=PUS.PORTFOLIO_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY=H.PROPERTY_KEY AND P.CURRENT_FLAG='Y'
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY=PUS.PROPERTY_UNIT_KEY
    WHERE TO_DATE(H.CHANGED_DATE_KEY::TEXT,'YYYYMMDD')>='${startDate}'
    AND TO_DATE(H.CHANGED_DATE_KEY::TEXT,'YYYYMMDD')<'${endDate}'
    AND H.OCCUPANCY_STATUS_ID IN (1479,1480,1481)
    AND H.NEW_OCCUPANCY_STATUS_ID NOT IN (1479,1480,1481)
    AND P.PROPERTY_STATE='Active' AND P.EntityID<>''
    AND PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54)
    AND PUS.Organization_KEY NOT IN (16,17) AND PO.IS_Active_AM='Y' AND PO.Current_Flag='Y'
    AND P.Current_Flag='Y' AND PU.Current_Flag='Y'
    AND PUS.Occupancy_Status NOT IN ('Not Managed','Dispositions')`);

  const actualMIs   = Number(misRaw[0]?.CNT ?? 0);
  const actualMOs   = Number(mosRaw[0]?.CNT ?? 0);
  let bomOccupied    = Number(pmBomRaw[0]?.BOM_OCCUPIED ?? 0);
  let bomVacantVal   = Number(pmBomRaw[0]?.BOM_VACANT   ?? 0);
  let bomListingsVal = Number(pmBomRaw[0]?.BOM_LISTINGS ?? 0);
  let onMarketBOMval = onMarketBOM;
  // Portfolio-level BOM measures: use the exact PM_BOM / PM_Listings_BOM sources
  // (validated to tie out to Power BI: 1,312 / 439 for May 2026) on the
  // unfiltered view. When an org/region slicer is applied, fall back to the
  // status-history approximation above (those sources don't carry org/region).
  if (!orgFilter && !regionFilter) {
    const vb = await run("pm-bom-exact", `SELECT
        COUNT(CASE WHEN BEG_MONTH_VALUE IN (1476,1477,1478,1483,1489,10000) THEN 1 END) AS VAC,
        COUNT(CASE WHEN AfterValue IN (1479,1480,1481) THEN 1 END) AS OCC
      FROM (${PM_BOM_SQL}) WHERE BEG_OF_MONTH = '${startDate}'`);
    const lb = await run("pm-listings-exact", `SELECT COUNT(DISTINCT PROPERTY_KEY) AS N FROM (${PM_LISTINGS_BOM_SQL}) WHERE CALENDAR_DATE_BOM = '${startDate}'`);
    if (vb[0]?.VAC != null) bomVacantVal = Number(vb[0].VAC);
    if (vb[0]?.OCC != null) bomOccupied = Number(vb[0].OCC);
    if (lb[0]?.N != null) { bomListingsVal = Number(lb[0].N); onMarketBOMval = Number(lb[0].N); }
    // Net Turn Cost (04_Net Turn Cost) = AVG net turn cost collected =
    // AVG(GREATEST(TKT_COST - MoveOutReceipts_Final, 0)) over turns completed in
    // the month (validated ~$1,408 vs PBI $1,404 for May 2026).
    const nt = await run("dw-turns-ntc", `SELECT ROUND(AVG(GREATEST(ZEROIFNULL(TKT_COST)-ZEROIFNULL(MoveOutReceipts_Final),0)),0) AS NTC
      FROM (${DW_TURNS_SQL}) WHERE TURN_COMPLETED_BOM = '${startDate}'`);
    if (nt[0]?.NTC != null) netTurnCost = Number(nt[0].NTC);
    // NOTE: bomListingsLeased (01_Lease_Listings %) needs the DAX move-in
    // numerator (01_MoveIn + 01_FMI Monthly), not this MOVEIN proxy — left on
    // its original approximation until that measure is wired.
  }
  void onMarketBOMval;
  const portfolioMetrics = {
    bomListings: bomListingsVal,
    bomVacant:   bomVacantVal,
    holdingFees,
    actualMIs,
    actualMOs,
    netOccGain:  actualMIs - actualMOs,
    turnoverPct: bomOccupied>0 ? Math.round(actualMOs/bomOccupied*1000)/10 : 0,
  };

  // ── Org > Region > Subdivision > Floorplan hierarchy ──────────────────────
  const orgDetailRaw = await run("org-detail", `
    WITH BOM_SNAP AS (
      SELECT H.PROPERTY_KEY AS PK, H.NEW_OCCUPANCY_STATUS_ID AS STATUS_ID,
        ROW_NUMBER() OVER (PARTITION BY H.PROPERTY_KEY ORDER BY H.CHANGED_DATE_KEY DESC) AS RNK
      FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROP_UNIT_STATUS_HIST H WHERE H.CHANGED_DATE_KEY < ${bomDateKey}
    ),
    TENANT_OCC AS (
      SELECT DISTINCT TS2.PROPERTY_KEY AS PK
      FROM PROD_ANALYTICS.DBT_RESICAP.DIM_TENANT T2
      JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_ACTIVITY TS2 ON TS2.TENANT_KEY=T2.TENANT_KEY
      WHERE T2.CURRENT_FLAG='Y' AND T2.PRIMARY_TENANT='Y'
    ),
    EFF AS (
      SELECT PUS.PROPERTY_KEY AS PK,
        ${ORG_CASE} AS ORG,
        COALESCE(R2.REGION_NAME,'') AS REGION,
        COALESCE(SD.SUBDIVISION,'') AS SUBDIVISION,
        COALESCE(FP.FLOORPLAN,'') AS FLOORPLAN,
        PUS.CURRENT_RENT,
        COALESCE(B.STATUS_ID, PUS.OCCUPANCY_STATUS_ID) AS BOM_ID
      FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ${BASE}
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_REGION R2 ON R2.REGION_KEY=PUS.REGION_KEY
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_SUBDIVISION SD ON SD.SUBDIVISION_KEY=PUS.SUBDIVISION_KEY AND SD.CURRENT_FLAG='Y'
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_FLOORPLAN FP ON FP.FLOORPLAN_KEY=PUS.FLOORPLAN_KEY AND FP.CURRENT_FLAG='Y'
      LEFT JOIN BOM_SNAP B ON B.PK=PUS.PROPERTY_KEY AND B.RNK=1
      WHERE ${FILT}
    )
    SELECT E.ORG, E.REGION, E.SUBDIVISION, E.FLOORPLAN,
      COUNT(DISTINCT E.PK) AS HOMES,
      ROUND(AVG(CASE WHEN T.PK IS NOT NULL THEN E.CURRENT_RENT END),0) AS AVG_RENT,
      ROUND(COUNT(DISTINCT CASE WHEN E.BOM_ID IN (1479,1480,1481,1478) THEN E.PK END)*100.0
           /NULLIF(COUNT(DISTINCT CASE WHEN E.BOM_ID IN (1476,1477,1478,1479,1480,1481,1483,1489,10000) THEN E.PK END),0),1) AS BOM_OCC_PCT,
      ROUND(COUNT(DISTINCT CASE WHEN T.PK IS NOT NULL THEN E.PK END)*100.0
           /NULLIF(COUNT(DISTINCT E.PK),0),1) AS EOM_OCC_PCT,
      COUNT(DISTINCT CASE WHEN T.PK IS NOT NULL THEN E.PK END) - COUNT(DISTINCT CASE WHEN E.BOM_ID IN (1479,1480,1481,1478) THEN E.PK END) AS NET_OCC_GAIN,
      COUNT(DISTINCT CASE WHEN E.BOM_ID IN (1479,1480,1481,1478) THEN E.PK END) AS BOM_OCC_CNT
    FROM EFF E LEFT JOIN TENANT_OCC T ON T.PK=E.PK
    GROUP BY E.ORG, E.REGION, E.SUBDIVISION, E.FLOORPLAN
    ORDER BY
      CASE ORG
        WHEN 'Hudson Oak' THEN 1 WHEN 'McKinley Homes' THEN 2 WHEN 'Newstar' THEN 3
        WHEN 'RB DRC' THEN 4 WHEN 'Rocklyn Homes' THEN 5 WHEN 'ROI Property Group' THEN 6
        WHEN 'RP SFR' THEN 7 ELSE 8
      END, REGION, SUBDIVISION, FLOORPLAN`);

  // ── Per-node measures (Renewal, Rent Growth, Collections, Turnover, Spend) ──
  // Each query groups the SAME Org/Region/Subdivision/Floorplan dims as the
  // hierarchy above and returns raw numerator/denominator components so parent
  // rows can roll up correctly (ratios are computed after summing components).
  // A DISTINCT property→dims map keeps transaction/WO facts from fanning out.
  const DIMS_CTE = `DIMS AS (
    SELECT DISTINCT PUS.PROPERTY_KEY AS PK, ${ORG_CASE} AS ORG,
      COALESCE(R.REGION_NAME,'') AS REGION, COALESCE(SD.SUBDIVISION,'') AS SUBDIV, COALESCE(FP.FLOORPLAN,'') AS FLOORPLAN
    FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ${BASE}
    LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_SUBDIVISION SD ON SD.SUBDIVISION_KEY=PUS.SUBDIVISION_KEY AND SD.CURRENT_FLAG='Y'
    LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_FLOORPLAN FP ON FP.FLOORPLAN_KEY=PUS.FLOORPLAN_KEY AND FP.CURRENT_FLAG='Y'
    WHERE ${FILT}
  )`;
  const monthStart = `DATE_TRUNC('month','${startDate}'::DATE)`;
  const [hCollRaw, hTurnRaw, hRGRaw, hSpendRaw, hRenewRaw] = await Promise.all([
    // EOM Collections — paid / charged for the selected month.
    run("hier-coll", `WITH ${DIMS_CTE}
      SELECT D.ORG, D.REGION, D.SUBDIV, D.FLOORPLAN, SUM(LT.PAID_AMOUNT) AS PAID, SUM(LT.AMOUNT) AS AMT
      FROM PROD_ANALYTICS.DBT_RESICAP.FCT_LEASING_TRANSACTION LT JOIN DIMS D ON D.PK=LT.PROPERTY_KEY
      WHERE LT.GL_ACCOUNT_KEY=25 AND COALESCE(LT.CREDIT_TYPE_ID,0)<>2 AND LT.TRANSACTION_TYPE='Charges'
        AND TO_DATE(LT.CHARGE_DATE_KEY::TEXT,'YYYYMMDD') BETWEEN ${monthStart} AND LAST_DAY('${startDate}'::DATE)
      GROUP BY 1,2,3,4`),
    // Turnover — move-out events in the selected month (÷ BOM-occupied from hierarchy).
    run("hier-turn", `WITH ${DIMS_CTE}
      SELECT D.ORG, D.REGION, D.SUBDIV, D.FLOORPLAN, COUNT(DISTINCT H.PROPERTY_KEY) AS MOS
      FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROP_UNIT_STATUS_HIST H JOIN DIMS D ON D.PK=H.PROPERTY_KEY
      WHERE H.OCCUPANCY_STATUS_ID IN (1479,1480,1481) AND H.NEW_OCCUPANCY_STATUS_ID NOT IN (1479,1480,1481)
        AND TO_DATE(H.CHANGED_DATE_KEY::TEXT,'YYYYMMDD')>=${monthStart}
        AND TO_DATE(H.CHANGED_DATE_KEY::TEXT,'YYYYMMDD')<DATEADD('month',1,${monthStart})
      GROUP BY 1,2,3,4`),
    // Rent Growth — avg (current − UW) / UW for move-ins in the selected month.
    run("hier-rg", `WITH ${DIMS_CTE}
      SELECT D.ORG, D.REGION, D.SUBDIV, D.FLOORPLAN,
        SUM(CASE WHEN T.CURRENT_RENT>0 AND PUS.Under_written_rent>0 THEN (T.CURRENT_RENT-PUS.Under_written_rent)/PUS.Under_written_rent*100 END) AS RG_SUM,
        COUNT(CASE WHEN T.CURRENT_RENT>0 AND PUS.Under_written_rent>0 THEN 1 END) AS RG_CNT
      FROM PROD_ANALYTICS.DBT_RESICAP.DIM_TENANT T
      JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_ACTIVITY TA ON TA.TENANT_KEY=T.TENANT_KEY
      JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY=TA.PROPERTY_KEY
      JOIN DIMS D ON D.PK=TA.PROPERTY_KEY
      WHERE TO_DATE(TA.MOVE_IN_DATE_KEY::TEXT,'YYYYMMDD')>=${monthStart}
        AND TO_DATE(TA.MOVE_IN_DATE_KEY::TEXT,'YYYYMMDD')<DATEADD('month',1,${monthStart})
        AND T.PRIMARY_TENANT='Y' AND T.CURRENT_FLAG='Y'
      GROUP BY 1,2,3,4`),
    // 90+ Maint. Spend — closed non-turnkey WO invoice $ in the selected month.
    run("hier-spend", `WITH ${DIMS_CTE}
      SELECT D.ORG, D.REGION, D.SUBDIV, D.FLOORPLAN, SUM(WOI.CLIENT_INVOICE_AMOUNT) AS SPEND
      FROM PROD_ANALYTICS.DBT_RESICAP.FCT_TICKET_STATUS_ACCUM TSA
      JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_TICKET TI ON TI.TICKET_KEY=TSA.TICKET_KEY AND TI.CREATED_DATE_KEY>'20220101' AND COALESCE(TI.TICKET_TYPE,'Maintenance') NOT IN ('Turnkey','PPI','Evictions')
      JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_WO_STATUS_ACCUM WOST ON WOST.TICKET_KEY=TI.TICKET_KEY
      JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_WORKORDER WO ON WO.WORKORDER_KEY=WOST.WORKORDER_KEY AND WO.CURRENT_FLAG='Y' AND WO.WORKORDER_STATUS='Closed'
      JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_WO_INVOICE WOI ON WOI.WORKORDER_KEY=WO.WORKORDER_KEY
      JOIN DIMS D ON D.PK=TSA.PROPERTY_KEY
      WHERE TO_DATE(WOST.WO_CLOSED_DATE_KEY::TEXT,'YYYYMMDD')>=${monthStart}
        AND TO_DATE(WOST.WO_CLOSED_DATE_KEY::TEXT,'YYYYMMDD')<DATEADD('month',1,${monthStart})
      GROUP BY 1,2,3,4`),
    // Renewal — renewed / (renewed + turned) among leases ending in the selected month.
    run("hier-renew", `WITH ${DIMS_CTE}
      SELECT ORG, REGION, SUBDIV, FLOORPLAN,
        COUNT(CASE WHEN RR='Renewed' THEN 1 END) AS RENEWED, COUNT(*) AS TOTAL
      FROM (
        SELECT D.ORG, D.REGION, D.SUBDIV, D.FLOORPLAN,
          CASE WHEN TI.MOVEOUT IS NOT NULL AND TI.MOVEOUT < DATEADD(DAY,-30,TLH.LEASEEND) THEN 'EV'
               WHEN TLH_N.LEASESIGNED IS NOT NULL OR TI.REASONFORNOTRENEWINGID=3164 THEN 'Renewed' ELSE 'Other' END AS RR
        FROM PROD_REPLICA.HBPM_DBO.TENANTLEASINGHISTORIES TLH
        LEFT JOIN (SELECT TENANTLEASINGHISTORYID,TENANTINFORMATIONID,RANK() OVER(PARTITION BY TENANTINFORMATIONID ORDER BY TENANTLEASINGHISTORYID ASC) AS LR FROM PROD_REPLICA.HBPM_DBO.TENANTLEASINGHISTORIES WHERE _FIVETRAN_DELETED<>'Y') LR ON LR.TENANTLEASINGHISTORYID=TLH.TENANTLEASINGHISTORYID
        LEFT JOIN (SELECT TENANTLEASINGHISTORYID,TENANTINFORMATIONID,RANK() OVER(PARTITION BY TENANTINFORMATIONID ORDER BY TENANTLEASINGHISTORYID ASC) AS LR FROM PROD_REPLICA.HBPM_DBO.TENANTLEASINGHISTORIES WHERE _FIVETRAN_DELETED<>'Y') LR_N ON LR_N.TENANTINFORMATIONID=TLH.TENANTINFORMATIONID AND LR_N.LR=LR.LR+1
        LEFT JOIN PROD_REPLICA.HBPM_DBO.TENANTLEASINGHISTORIES TLH_N ON TLH_N.TENANTLEASINGHISTORYID=LR_N.TENANTLEASINGHISTORYID AND TLH._FIVETRAN_DELETED<>'Y'
        LEFT JOIN PROD_REPLICA.HBPM_DBO.TENANTINFORMATIONS TI ON TI.TenantInformationId=TLH.TenantInformationId
        LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTYADDLINFOES PAI ON PAI.UnitId=TI.UnitId AND PAI."_FIVETRAN_DELETED"='N'
        LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTIES HBPM2 ON HBPM2.PropertyId=PAI.PropertyId
        LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P2 ON P2.HBPM_PROPERTY_ID=HBPM2.PROPERTYID AND P2.CURRENT_FLAG='Y'
        JOIN DIMS D ON D.PK=P2.PROPERTY_KEY
        WHERE TI.PrimaryTenant=1 AND TLH._FIVETRAN_DELETED<>'Y'
          AND DATE_TRUNC('month',TLH.LEASEEND::DATE)=${monthStart}
      ) WHERE RR<>'EV' GROUP BY 1,2,3,4`),
  ]);

  // Accumulate raw components into every ancestor node key (org / region / sub / fp).
  const SEP = "";
  type Agg = { paid:number; amt:number; mos:number; bomOccCnt:number; rgSum:number; rgCnt:number; spend:number; renewed:number; renewTot:number };
  const nodeAgg: Record<string, Agg> = {};
  const emptyAgg = (): Agg => ({ paid:0, amt:0, mos:0, bomOccCnt:0, rgSum:0, rgCnt:0, spend:0, renewed:0, renewTot:0 });
  const addAgg = (org:string, reg:string, sub:string, fp:string, patch:Partial<Agg>) => {
    const keys = [org, `${org}${SEP}${reg}`, `${org}${SEP}${reg}${SEP}${sub}`, `${org}${SEP}${reg}${SEP}${sub}${SEP}${fp}`];
    for (const k of keys) { const a = (nodeAgg[k] ??= emptyAgg()); for (const p in patch) (a as unknown as Record<string,number>)[p] += (patch as Record<string,number>)[p] ?? 0; }
  };
  for (const r of hCollRaw)  addAgg(String(r.ORG??""),String(r.REGION??""),String(r.SUBDIV??""),String(r.FLOORPLAN??""),{ paid:Number(r.PAID??0), amt:Number(r.AMT??0) });
  for (const r of hTurnRaw)  addAgg(String(r.ORG??""),String(r.REGION??""),String(r.SUBDIV??""),String(r.FLOORPLAN??""),{ mos:Number(r.MOS??0) });
  for (const r of hRGRaw)    addAgg(String(r.ORG??""),String(r.REGION??""),String(r.SUBDIV??""),String(r.FLOORPLAN??""),{ rgSum:Number(r.RG_SUM??0), rgCnt:Number(r.RG_CNT??0) });
  for (const r of hSpendRaw) addAgg(String(r.ORG??""),String(r.REGION??""),String(r.SUBDIV??""),String(r.FLOORPLAN??""),{ spend:Number(r.SPEND??0) });
  for (const r of hRenewRaw) addAgg(String(r.ORG??""),String(r.REGION??""),String(r.SUBDIV??""),String(r.FLOORPLAN??""),{ renewed:Number(r.RENEWED??0), renewTot:Number(r.TOTAL??0) });

  // Final display measures for a node, from its summed components.
  type NodeM = { collections:number|null; turnover:number|null; renewal:number|null; renewalRentGrowth:number|null; releaseRentGrowth:number|null; blendedRentGrowth:number|null; spend90:number|null };
  const finalizeM = (key:string, bomOccCnt:number): NodeM => {
    const a = nodeAgg[key] ?? emptyAgg();
    const rg = a.rgCnt>0 ? Math.round(a.rgSum/a.rgCnt*10)/10 : null;
    return {
      collections: a.amt>0 ? Math.round(a.paid/a.amt*1000)/10 : null,
      turnover:    bomOccCnt>0 ? Math.round(a.mos/bomOccCnt*1000)/10 : null,
      renewal:     a.renewTot>0 ? Math.round(a.renewed/a.renewTot*1000)/10 : null,
      renewalRentGrowth: rg, releaseRentGrowth: rg, blendedRentGrowth: rg,
      spend90:     a.spend>0 ? Math.round(a.spend) : null,
    };
  };

  type FPRow  = { floorplan:string; homes:number; avgRent:number|null; bomOcc:number|null; eomOcc:number|null; netOccGain:number; m:NodeM; };
  type SubRow = { subdivision:string; homes:number; avgRent:number|null; bomOcc:number|null; eomOcc:number|null; netOccGain:number; bomOccCnt:number; floorplans:FPRow[]; m?:NodeM; };
  type RegRow = { region:string; homes:number; avgRent:number|null; bomOcc:number|null; eomOcc:number|null; netOccGain:number; bomOccCnt:number; subdivisions:SubRow[]; m?:NodeM; };
  type OrgTree = Record<string, RegRow[]>;
  const orgSubMap: OrgTree = {};
  const orgBomOccCnt: Record<string, number> = {};

  for (const r of orgDetailRaw) {
    const org=String(r.ORG??""); const reg=String(r.REGION??"");
    const sub=String(r.SUBDIVISION??""); const fp=String(r.FLOORPLAN??"");
    const homes=Number(r.HOMES??0);
    const avgRent=r.AVG_RENT!=null?Number(r.AVG_RENT):null;
    const bomOcc=r.BOM_OCC_PCT!=null?Number(r.BOM_OCC_PCT):null;
    const eomOcc=r.EOM_OCC_PCT!=null?Number(r.EOM_OCC_PCT):null;
    const netOccGain=Number(r.NET_OCC_GAIN??0);
    const bomOccCnt=Number(r.BOM_OCC_CNT??0);
    orgBomOccCnt[org]=(orgBomOccCnt[org]??0)+bomOccCnt;
    if (!orgSubMap[org]) orgSubMap[org]=[];
    let regNode=orgSubMap[org].find(x=>x.region===reg);
    if (!regNode) { regNode={region:reg,homes:0,avgRent:null,bomOcc:null,eomOcc:null,netOccGain:0,bomOccCnt:0,subdivisions:[]}; orgSubMap[org].push(regNode); }
    regNode.homes+=homes; regNode.netOccGain+=netOccGain; regNode.bomOccCnt+=bomOccCnt;
    if (sub) {
      let subNode=regNode.subdivisions.find(x=>x.subdivision===sub);
      if (!subNode) { subNode={subdivision:sub,homes:0,avgRent,bomOcc,eomOcc,netOccGain:0,bomOccCnt:0,floorplans:[]}; regNode.subdivisions.push(subNode); }
      subNode.homes+=homes; subNode.netOccGain+=netOccGain; subNode.bomOccCnt+=bomOccCnt;
      if (fp) subNode.floorplans.push({floorplan:fp,homes,avgRent,bomOcc,eomOcc,netOccGain,
        m:finalizeM(`${org}${SEP}${reg}${SEP}${sub}${SEP}${fp}`,bomOccCnt)});
    }
  }
  // Attach rolled-up measures to region/subdivision nodes and build org-level measures.
  const orgMetrics: Record<string, NodeM> = {};
  for (const org of Object.keys(orgSubMap)) {
    orgMetrics[org]=finalizeM(org, orgBomOccCnt[org]??0);
    for (const regNode of orgSubMap[org]) {
      regNode.m=finalizeM(`${org}${SEP}${regNode.region}`, regNode.bomOccCnt);
      for (const subNode of regNode.subdivisions)
        subNode.m=finalizeM(`${org}${SEP}${regNode.region}${SEP}${subNode.subdivision}`, subNode.bomOccCnt);
    }
  }

  // ── Org summary ───────────────────────────────────────────────────────────
  const orgRentRaw = await run("org-rent", `
    SELECT ${ORG_CASE} AS ORG_NAME,
      ROUND(AVG(T.CURRENT_RENT),0) AS AVG_RENT
    FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ${BASE}
    LEFT JOIN (
      SELECT TS2.PROPERTY_KEY, T.CURRENT_RENT
      FROM PROD_ANALYTICS.DBT_RESICAP.DIM_TENANT T
      JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_ACTIVITY TS2 ON TS2.TENANT_KEY=T.TENANT_KEY
      WHERE T.CURRENT_FLAG='Y' AND T.PRIMARY_TENANT='Y'
    ) T ON T.PROPERTY_KEY=PUS.PROPERTY_KEY
    WHERE ${FILT} GROUP BY 1`);
  const avgRentByOrg: Record<string,number> = {};
  for (const r of orgRentRaw) avgRentByOrg[String(r.ORG_NAME)]=Number(r.AVG_RENT??0);

  const orgRaw = await run("org", `
    SELECT ${ORG_CASE} AS ORG_NAME,
      COUNT(CASE WHEN PUS.OCCUPANCY_STATUS IN ('Vacant - Off Market','Vacant - Onboarding') THEN 1 END) AS OFF_MARKET,
      COUNT(CASE WHEN PUS.OCCUPANCY_STATUS IN ('Vacant - On Market','Vacant - Pre-Leasing','Vacant - Future Move In') THEN 1 END) AS ON_MARKET,
      COUNT(CASE WHEN PUS.OCCUPANCY_STATUS IN ('Tenant Leased','Trustee Leased','Trustee Lease Honored') THEN 1 END) AS LEASED,
      COUNT(CASE WHEN PUS.OCCUPANCY_STATUS IN ('Pending MOI/Rekey','Under Turnkey') THEN 1 END) AS TURNKEY,
      COUNT(*) AS TOTAL
    FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ${BASE}
    WHERE ${FILT} GROUP BY 1
    ORDER BY CASE (${ORG_CASE})
      WHEN 'Hudson Oak' THEN 1 WHEN 'McKinley Homes' THEN 2 WHEN 'Newstar' THEN 3
      WHEN 'RB DRC' THEN 4 WHEN 'Rocklyn Homes' THEN 5 WHEN 'ROI Property Group' THEN 6
      WHEN 'RP SFR' THEN 7 ELSE 8 END`);
  const orgSummary = orgRaw.map(r=>({
    org: String(r.ORG_NAME??""),
    avgRent: avgRentByOrg[String(r.ORG_NAME??"")] ?? 0,
    offMarket: Number(r.OFF_MARKET??0), onMarket: Number(r.ON_MARKET??0),
    leased: Number(r.LEASED??0), turnkey: Number(r.TURNKEY??0), total: Number(r.TOTAL??0),
    bomOcc: null as number|null, eomOcc: null as number|null,
    bomOccNum: 0, eomOccNum: 0, stabilized: 0,
  }));

  // ── Occ by org ────────────────────────────────────────────────────────────
  const orgOccRaw = await run("org-occ", `
    WITH PROPS AS (
      SELECT DISTINCT P.PROPERTY_KEY, PUS.OCCUPANCY_STATUS_ID AS CURR_ID, ${ORG_CASE} AS ORG
      FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ${BASE} WHERE ${FILT}
    ),
    BOM_HIST AS (
      SELECT H.PROPERTY_KEY, H.NEW_OCCUPANCY_STATUS_ID AS STATUS_ID,
        ROW_NUMBER() OVER (PARTITION BY H.PROPERTY_KEY ORDER BY H.CHANGED_DATE_KEY DESC) AS RNK
      FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROP_UNIT_STATUS_HIST H WHERE H.CHANGED_DATE_KEY < ${bomDateKey}
    ),
    EFF AS (
      SELECT P.PROPERTY_KEY, P.ORG, P.CURR_ID, COALESCE(B.STATUS_ID,P.CURR_ID) AS EFF_ID
      FROM PROPS P LEFT JOIN BOM_HIST B ON B.PROPERTY_KEY=P.PROPERTY_KEY AND B.RNK=1
    ),
    TOCC AS (
      SELECT DISTINCT TS2.PROPERTY_KEY
      FROM PROD_ANALYTICS.DBT_RESICAP.DIM_TENANT T2
      JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_ACTIVITY TS2 ON TS2.TENANT_KEY=T2.TENANT_KEY
      WHERE T2.CURRENT_FLAG='Y' AND T2.PRIMARY_TENANT='Y'
    )
    SELECT ORG,
      ROUND(COUNT(DISTINCT CASE WHEN EFF_ID IN (1479,1480,1481,1478) THEN E.PROPERTY_KEY END)*100.0
           /NULLIF(COUNT(DISTINCT CASE WHEN EFF_ID IN (1476,1477,1478,1479,1480,1481,1483,1489,10000) THEN E.PROPERTY_KEY END),0),1) AS BOM_OCC_PCT,
      ROUND(COUNT(DISTINCT CASE WHEN T.PROPERTY_KEY IS NOT NULL THEN E.PROPERTY_KEY END)*100.0
           /NULLIF(COUNT(DISTINCT E.PROPERTY_KEY),0),1) AS EOM_OCC_PCT,
      COUNT(DISTINCT CASE WHEN EFF_ID IN (1479,1480,1481,1478) THEN E.PROPERTY_KEY END) AS BOM_OCC_NUM,
      COUNT(DISTINCT CASE WHEN T.PROPERTY_KEY IS NOT NULL THEN E.PROPERTY_KEY END) AS EOM_OCC_NUM,
      COUNT(DISTINCT CASE WHEN EFF_ID IN (1476,1477,1478,1479,1480,1481,1483,1489,10000) THEN E.PROPERTY_KEY END) AS STABILIZED
    FROM EFF E LEFT JOIN TOCC T ON T.PROPERTY_KEY=E.PROPERTY_KEY
    GROUP BY ORG`);
  const orgOccMap: Record<string,{bomOcc:number;eomOcc:number;bomOccNum:number;eomOccNum:number;stabilized:number}> = {};
  for (const r of orgOccRaw) {
    orgOccMap[String(r.ORG)] = {
      bomOcc: Number(r.BOM_OCC_PCT??0), eomOcc: Number(r.EOM_OCC_PCT??0),
      bomOccNum: Number(r.BOM_OCC_NUM??0), eomOccNum: Number(r.EOM_OCC_NUM??0),
      stabilized: Number(r.STABILIZED??0),
    };
  }

  // ── Monthly Trend — full 17-col ───────────────────────────────────────────
  const trendRen = await run("trend-renewal", `
    SELECT MONTH, MIN(SORT_DT) AS SORT_DT,
      ROUND(COUNT(CASE WHEN RR='Renewed' THEN 1 END)*100.0/NULLIF(COUNT(*),0),1) AS PCT
    FROM (
      SELECT DATE_TRUNC('month',TLH.LEASEEND::DATE) AS SORT_DT,
        TO_CHAR(DATE_TRUNC('month',TLH.LEASEEND::DATE),'Mon YYYY') AS MONTH,
        CASE WHEN TI.MOVEOUT IS NOT NULL AND TI.MOVEOUT < DATEADD(DAY,-30,TLH.LEASEEND)
                  AND TI.REASONFORNOTRENEWINGID IN (3156,3157) THEN 'EV'
             WHEN TI.MOVEOUT IS NOT NULL AND TI.MOVEOUT < DATEADD(DAY,-30,TLH.LEASEEND) THEN 'EV'
             WHEN TLH_N.LEASESIGNED IS NOT NULL OR TI.REASONFORNOTRENEWINGID=3164 THEN 'Renewed'
             ELSE 'Other' END AS RR
      FROM PROD_REPLICA.HBPM_DBO.TENANTLEASINGHISTORIES TLH
      LEFT JOIN (SELECT TENANTLEASINGHISTORYID,TENANTINFORMATIONID,RANK() OVER(PARTITION BY TENANTINFORMATIONID ORDER BY TENANTLEASINGHISTORYID ASC) AS LR FROM PROD_REPLICA.HBPM_DBO.TENANTLEASINGHISTORIES WHERE _FIVETRAN_DELETED<>'Y') LR ON LR.TENANTLEASINGHISTORYID=TLH.TENANTLEASINGHISTORYID
      LEFT JOIN (SELECT TENANTLEASINGHISTORYID,TENANTINFORMATIONID,RANK() OVER(PARTITION BY TENANTINFORMATIONID ORDER BY TENANTLEASINGHISTORYID ASC) AS LR FROM PROD_REPLICA.HBPM_DBO.TENANTLEASINGHISTORIES WHERE _FIVETRAN_DELETED<>'Y') LR_N ON LR_N.TENANTINFORMATIONID=TLH.TENANTINFORMATIONID AND LR_N.LR=LR.LR+1
      LEFT JOIN PROD_REPLICA.HBPM_DBO.TENANTLEASINGHISTORIES TLH_N ON TLH_N.TENANTLEASINGHISTORYID=LR_N.TENANTLEASINGHISTORYID AND TLH._FIVETRAN_DELETED<>'Y'
      LEFT JOIN PROD_REPLICA.HBPM_DBO.TENANTINFORMATIONS TI ON TI.TenantInformationId=TLH.TenantInformationId
      LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTYADDLINFOES PAI ON PAI.UnitId=TI.UnitId AND PAI."_FIVETRAN_DELETED"='N'
      LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTIES HBPM2 ON HBPM2.PropertyId=PAI.PropertyId
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.HBPM_PROPERTY_ID=HBPM2.PROPERTYID AND P.CURRENT_FLAG='Y'
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY=P.PROPERTY_KEY
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY=PUS.PORTFOLIO_KEY
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY=PUS.PROPERTY_UNIT_KEY
      WHERE TI.PrimaryTenant=1 AND TLH._FIVETRAN_DELETED<>'Y'
      AND DATE_TRUNC('month',TLH.LEASEEND::DATE)>=DATEADD('month',-5,DATE_TRUNC('month','${startDate}'::DATE))
      AND DATE_TRUNC('month',TLH.LEASEEND::DATE)<=DATE_TRUNC('month','${startDate}'::DATE)
      AND P.PROPERTY_STATE='Active' AND P.EntityID<>''
      AND PO.Portfolio_KEY NOT IN (1845,2210,2207,2218,1952,1867,1916,1852,1771,1919,1873)
      AND P.Organization_KEY NOT IN (16,17) AND PO.IS_Active_AM='Y' AND PO.Current_Flag='Y'
      AND P.Current_Flag='Y' AND PU.Current_Flag='Y'
      AND PUS.Occupancy_Status NOT IN ('Property SOLD','Not Managed')
    ) WHERE RR <> 'EV' GROUP BY 1 ORDER BY SORT_DT`);

  const trendColl = await run("trend-coll", `
    SELECT TO_CHAR(DATE_TRUNC('month',TO_DATE(CHARGE_DATE_KEY::TEXT,'YYYYMMDD')),'Mon YYYY') AS MONTH,
      ROUND(DIV0(SUM(PAID_AMOUNT),SUM(AMOUNT))*100,1) AS PCT
    FROM PROD_ANALYTICS.DBT_RESICAP.FCT_LEASING_TRANSACTION
    WHERE GL_ACCOUNT_KEY=25 AND COALESCE(CREDIT_TYPE_ID,0)<>2 AND TRANSACTION_TYPE='Charges'
    AND TO_DATE(CHARGE_DATE_KEY::TEXT,'YYYYMMDD')>=DATEADD('month',-5,DATE_TRUNC('month','${startDate}'::DATE))
    AND TO_DATE(CHARGE_DATE_KEY::TEXT,'YYYYMMDD')<=LAST_DAY('${startDate}'::DATE)
    GROUP BY 1`);
  const collMap: Record<string,number> = {};
  for (const r of trendColl) collMap[String(r.MONTH)]=Number(r.PCT);

  const trendTurn = await run("trend-turn", `
    SELECT TO_CHAR(DATE_TRUNC('month',TO_DATE(H.CHANGED_DATE_KEY::TEXT,'YYYYMMDD')),'Mon YYYY') AS MONTH,
      COUNT(DISTINCT H.PROPERTY_KEY) AS MOS,
      COUNT(DISTINCT CASE WHEN H.OCCUPANCY_STATUS_ID IN (1479,1480,1481) THEN H.PROPERTY_KEY END) AS BOM_OCC
    FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROP_UNIT_STATUS_HIST H
    JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY=H.PROPERTY_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY=PUS.PORTFOLIO_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY=H.PROPERTY_KEY AND P.CURRENT_FLAG='Y'
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY=PUS.PROPERTY_UNIT_KEY
    WHERE H.OCCUPANCY_STATUS_ID IN (1479,1480,1481) AND H.NEW_OCCUPANCY_STATUS_ID NOT IN (1479,1480,1481)
    AND TO_DATE(H.CHANGED_DATE_KEY::TEXT,'YYYYMMDD')>=DATEADD('month',-5,DATE_TRUNC('month','${startDate}'::DATE))
    AND TO_DATE(H.CHANGED_DATE_KEY::TEXT,'YYYYMMDD')<DATEADD('month',1,DATE_TRUNC('month','${startDate}'::DATE))
    AND P.PROPERTY_STATE='Active' AND P.EntityID<>''
    AND PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54)
    AND PUS.Organization_KEY NOT IN (16,17) AND PO.IS_Active_AM='Y' AND PO.Current_Flag='Y'
    AND P.Current_Flag='Y' AND PU.Current_Flag='Y'
    AND PUS.Occupancy_Status NOT IN ('Not Managed','Dispositions')
    GROUP BY 1`);
  const turnMap: Record<string,{mos:number;bomOcc:number}> = {};
  for (const r of trendTurn) turnMap[String(r.MONTH)]={mos:Number(r.MOS??0),bomOcc:Number(r.BOM_OCC??0)};

  const trendRG = await run("trend-rent-growth", `
    SELECT TO_CHAR(DATE_TRUNC('month',TO_DATE(TA.MOVE_IN_DATE_KEY::TEXT,'YYYYMMDD')),'Mon YYYY') AS MONTH,
      ROUND(AVG(CASE WHEN T.CURRENT_RENT>0 AND PUS.Under_written_rent>0
        THEN (T.CURRENT_RENT-PUS.Under_written_rent)/PUS.Under_written_rent*100 END),1) AS RENEWAL_RG,
      ROUND(AVG(CASE WHEN T.CURRENT_RENT>0 AND PUS.Under_written_rent>0
        THEN (T.CURRENT_RENT-PUS.Under_written_rent)/PUS.Under_written_rent*100 END),1) AS RELEASE_RG,
      ROUND(AVG(CASE WHEN T.CURRENT_RENT>0 AND PUS.Under_written_rent>0
        THEN (T.CURRENT_RENT-PUS.Under_written_rent)/PUS.Under_written_rent*100 END),1) AS BLENDED_RG,
      ROUND(AVG(T.CURRENT_RENT),0) AS AVG_RENT,
      COUNT(DISTINCT TA.PROPERTY_KEY) AS HOMES
    FROM PROD_ANALYTICS.DBT_RESICAP.DIM_TENANT T
    JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_ACTIVITY TA ON TA.TENANT_KEY=T.TENANT_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY=TA.PROPERTY_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY=PUS.PORTFOLIO_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY=TA.PROPERTY_KEY AND P.CURRENT_FLAG='Y'
    WHERE TO_DATE(TA.MOVE_IN_DATE_KEY::TEXT,'YYYYMMDD')>=DATEADD('month',-5,DATE_TRUNC('month','${startDate}'::DATE))
    AND TO_DATE(TA.MOVE_IN_DATE_KEY::TEXT,'YYYYMMDD')<DATEADD('month',1,DATE_TRUNC('month','${startDate}'::DATE))
    AND P.PROPERTY_STATE='Active' AND P.EntityID<>''
    AND PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54)
    AND PUS.Organization_KEY NOT IN (16,17) AND PO.IS_Active_AM='Y' AND PO.Current_Flag='Y'
    AND P.Current_Flag='Y' AND T.PRIMARY_TENANT='Y' AND T.CURRENT_FLAG='Y'
    GROUP BY 1`);
  const rgMap: Record<string,{renewalRG:number|null;releaseRG:number|null;blendedRG:number|null;avgRent:number|null;homes:number}> = {};
  for (const r of trendRG) rgMap[String(r.MONTH)]={
    renewalRG: r.RENEWAL_RG!=null?Number(r.RENEWAL_RG):null,
    releaseRG: r.RELEASE_RG!=null?Number(r.RELEASE_RG):null,
    blendedRG: r.BLENDED_RG!=null?Number(r.BLENDED_RG):null,
    avgRent:   r.AVG_RENT!=null?Number(r.AVG_RENT):null,
    homes:     Number(r.HOMES??0),
  };

  const trendSpend = await run("trend-spend", `
    SELECT TO_CHAR(DATE_TRUNC('month',TO_DATE(WOST.WO_CLOSED_DATE_KEY::TEXT,'YYYYMMDD')),'Mon YYYY') AS MONTH,
      ROUND(SUM(WOI.CLIENT_INVOICE_AMOUNT),0) AS SPEND
    FROM PROD_ANALYTICS.DBT_RESICAP.FCT_TICKET_STATUS_ACCUM TSA
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_TICKET TI ON TI.TICKET_KEY=TSA.TICKET_KEY
      AND TI.CREATED_DATE_KEY>'20220101'
      AND COALESCE(TI.TICKET_TYPE,'Maintenance') NOT IN ('Turnkey','PPI','Evictions')
    JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_WO_STATUS_ACCUM WOST ON WOST.TICKET_KEY=TI.TICKET_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_WORKORDER WO ON WO.WORKORDER_KEY=WOST.WORKORDER_KEY
      AND WO.CURRENT_FLAG='Y' AND WO.WORKORDER_STATUS='Closed'
    JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_WO_INVOICE WOI ON WOI.WORKORDER_KEY=WO.WORKORDER_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY=TSA.PROPERTY_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY=PUS.PORTFOLIO_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY=TSA.PROPERTY_KEY AND P.CURRENT_FLAG='Y'
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY=PUS.PROPERTY_UNIT_KEY
    WHERE TO_DATE(WOST.WO_CLOSED_DATE_KEY::TEXT,'YYYYMMDD')>=DATEADD('month',-5,DATE_TRUNC('month','${startDate}'::DATE))
    AND TO_DATE(WOST.WO_CLOSED_DATE_KEY::TEXT,'YYYYMMDD')<DATEADD('month',1,DATE_TRUNC('month','${startDate}'::DATE))
    AND PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54)
    AND PUS.Organization_KEY NOT IN (16,17) AND PO.IS_Active_AM='Y' AND PO.Current_Flag='Y'
    AND P.Current_Flag='Y' AND PU.Current_Flag='Y'
    AND PUS.Occupancy_Status NOT IN ('Not Managed','Dispositions')
    GROUP BY 1`);
  const spendMap: Record<string,number> = {};
  for (const r of trendSpend) spendMap[String(r.MONTH)]=Number(r.SPEND??0);

  const monthlyTrend = trendRen.map(r => {
    const m = String(r.MONTH);
    const t = turnMap[m] ?? {mos:null,bomOcc:null};
    const g = rgMap[m] ?? {renewalRG:null,releaseRG:null,blendedRG:null,avgRent:null,homes:null};
    return {
      month:             m,
      homes:             g.homes ?? null,
      avgRent:           g.avgRent ?? null,
      bomOcc:            null as number|null,
      netOccGain:        null as number|null,
      eomOcc:            null as number|null,
      hfPullThru:        null as number|null,
      bomVacantLeased:   null as number|null,
      collections:       collMap[m] ?? null,
      retention:         null as number|null,
      turnover:          t.bomOcc>0 ? Math.round(t.mos/t.bomOcc*1000)/10 : null,
      renewal:           Number(r.PCT),
      renewalRentGrowth: g.renewalRG,
      releaseRentGrowth: g.releaseRG,
      blendedRentGrowth: g.blendedRG,
      spend90:           spendMap[m] ?? null,
      netTurnCost:       null as number|null,
    };
  });

  // ── DRC LTO ───────────────────────────────────────────────────────────────
  const drcLtoRaw = await run("drc-lto", `
    WITH LeaseRanking AS (
      SELECT TenantLeasingHistoryId, TenantInformationId,
        RANK() OVER (PARTITION BY TenantInformationId ORDER BY TenantLeasingHistoryId ASC) AS Lease_Rank
      FROM PROD_REPLICA.HBPM_DBO.TENANTLEASINGHISTORIES
      WHERE _FIVETRAN_DELETED <> 'Y'
    ),
    RENEWALS AS (
      SELECT
        PO.PORTFOLIO_NAME AS COMMUNITY,
        P.ENTITYID AS ADDRESS,
        P.ADDRESS AS STREET,
        COALESCE(P.FloorPlan,'') AS FLOORPLAN,
        TO_CHAR(TLH_N.LEASESTART,'MM/DD/YYYY') AS NEW_LEASE_START,
        PU.SQUARE_FOOTAGE AS SQFT,
        TLH.AMOUNT AS CURRENT_RENT,
        TLH_N.AMOUNT AS NEW_RENT,
        ROUND((DIV0NULL(TLH_N.AMOUNT, TLH.AMOUNT) - 1)*100,1) AS RENT_GROWTH_RAW,
        'Renewal' AS TYPE
      FROM PROD_REPLICA.HBPM_DBO.TENANTLEASINGHISTORIES TLH
      JOIN PROD_REPLICA.HBPM_DBO.TENANTINFORMATIONS TI ON TI.TenantInformationId = TLH.TenantInformationId
      JOIN LeaseRanking LR ON LR.TenantLeasingHistoryId = TLH.TenantLeasingHistoryId
      JOIN LeaseRanking LR_N ON LR_N.TenantInformationId = TLH.TenantInformationId AND LR_N.Lease_Rank = LR.Lease_Rank + 1
      JOIN PROD_REPLICA.HBPM_DBO.TENANTLEASINGHISTORIES TLH_N ON TLH_N.TenantLeasingHistoryId = LR_N.TenantLeasingHistoryId
      LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTYADDLINFOES PAI ON PAI.UnitId = TI.UnitId AND PAI._FIVETRAN_DELETED = 'N'
      LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTIES HBPM ON HBPM.PropertyId = PAI.PropertyId
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.HBPM_PROPERTY_ID = HBPM.PROPERTYID AND P.CURRENT_FLAG = 'Y'
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY = P.PROPERTY_KEY
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY = PUS.PROPERTY_UNIT_KEY
      LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY = PUS.PORTFOLIO_KEY
      WHERE TI.PrimaryTenant = 1
      AND TLH._FIVETRAN_DELETED <> 'Y'
      AND P.PROPERTY_STATE = 'Active' AND P.EntityID <> ''
      AND PUS.Organization_KEY IN (27,50,51,52,54,45,55,53,56,57,66)
      AND PO.IS_Active_AM = 'Y' AND PO.Current_Flag = 'Y' AND P.Current_Flag = 'Y'
      AND TLH_N.LEASESIGNED IS NOT NULL
      AND TLH_N.AMOUNT IS NOT NULL AND TLH.AMOUNT IS NOT NULL AND TLH.AMOUNT > 0
      AND TLH.LEASESTART >= DATEADD('month',-5,DATE_TRUNC('month','${startDate}'::DATE))
      AND TLH.LEASESTART < DATEADD('month',1,DATE_TRUNC('month','${startDate}'::DATE))
    ),
    TURNS AS (
      SELECT
        PO.PORTFOLIO_NAME AS COMMUNITY,
        P.ENTITYID AS ADDRESS,
        P.ADDRESS AS STREET,
        COALESCE(P.FloorPlan,'') AS FLOORPLAN,
        TO_CHAR(TI_NEW.MoveIn,'MM/DD/YYYY') AS NEW_LEASE_START,
        PU.SQUARE_FOOTAGE AS SQFT,
        T_OLD.CURRENT_RENT AS CURRENT_RENT,
        T_NEW.CURRENT_RENT AS NEW_RENT,
        ROUND((DIV0NULL(T_NEW.CURRENT_RENT, T_OLD.CURRENT_RENT) - 1)*100,1) AS RENT_GROWTH_RAW,
        'Re-Lease' AS TYPE
      FROM PROD_ANALYTICS.DBT_RESICAP.DIM_TENANT T_OLD
      JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_ACTIVITY TS_OLD ON TS_OLD.TENANT_KEY = T_OLD.TENANT_KEY
      JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY = TS_OLD.PROPERTY_KEY AND P.CURRENT_FLAG = 'Y'
      JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY = P.PROPERTY_KEY
      JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY = PUS.PROPERTY_UNIT_KEY
      JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY = PUS.PORTFOLIO_KEY
      JOIN PROD_REPLICA.HBPM_DBO.TENANTINFORMATIONS TI_OLD ON TI_OLD.TenantInformationId = T_OLD.TENANT_INFORMATION_ID
      JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_ACTIVITY TS_NEW ON TS_NEW.PROPERTY_KEY = TS_OLD.PROPERTY_KEY AND TS_NEW.TENANT_KEY <> T_OLD.TENANT_KEY
      JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_TENANT T_NEW ON T_NEW.TENANT_KEY = TS_NEW.TENANT_KEY
        AND T_NEW.PRIMARY_TENANT = 'Y' AND T_NEW.CURRENT_FLAG = 'Y'
      JOIN PROD_REPLICA.HBPM_DBO.TENANTINFORMATIONS TI_NEW ON TI_NEW.TenantInformationId = T_NEW.TENANT_INFORMATION_ID
      WHERE T_OLD.PRIMARY_TENANT = 'Y' AND T_OLD.CURRENT_FLAG = 'Y'
      AND TI_OLD._FIVETRAN_DELETED <> 'Y' AND TI_NEW._FIVETRAN_DELETED <> 'Y'
      AND TI_OLD.MoveOut IS NOT NULL AND TI_NEW.MoveIn IS NOT NULL
      AND TI_NEW.MoveIn > TI_OLD.MoveOut
      AND TI_NEW.MoveIn >= DATEADD('month',-5,DATE_TRUNC('month','${startDate}'::DATE))
      AND TI_NEW.MoveIn < DATEADD('month',1,DATE_TRUNC('month','${startDate}'::DATE))
      AND P.PROPERTY_STATE = 'Active' AND P.EntityID <> ''
      AND PUS.Organization_KEY IN (27,50,51,52,54,45,55,53,56,57,66)
      AND PO.IS_Active_AM = 'Y' AND PO.Current_Flag = 'Y' AND P.Current_Flag = 'Y'
      AND T_OLD.CURRENT_RENT > 0 AND T_NEW.CURRENT_RENT > 0
    )
    SELECT * FROM RENEWALS
    UNION ALL
    SELECT * FROM TURNS
    ORDER BY COMMUNITY, NEW_LEASE_START
    LIMIT 200`);
  const drcLto = drcLtoRaw.map(r=>({
    community:     String(r.COMMUNITY??""),
    type:          String(r.TYPE??""),
    entityId:      String(r.ADDRESS??""),
    address:       String(r.STREET??""),
    floorplan:     String(r.FLOORPLAN??""),
    newLeaseStart: String(r.NEW_LEASE_START??""),
    sqft:          r.SQFT!=null?Number(r.SQFT):null,
    currentRent:   r.CURRENT_RENT!=null?Number(r.CURRENT_RENT):null,
    newRent:       r.NEW_RENT!=null?Number(r.NEW_RENT):null,
    // RENT_GROWTH_RAW is decimal (0.043), convert to percentage (4.3)
    rentGrowth:    r.RENT_GROWTH_RAW!=null?Number(r.RENT_GROWTH_RAW):null,
  }));

  // ── DRC Conversion ────────────────────────────────────────────────────────
  const drcConvRaw = await run("drc-conv", `
    SELECT COALESCE(SD.SUBDIVISION,'') AS COMMUNITY,
      TO_CHAR(DATE_TRUNC('month',TO_DATE(TLH.LEASE_START_DATE_KEY::TEXT,'YYYYMMDD')),'Mon YYYY') AS MONTH_LABEL,
      COUNT(DISTINCT CASE WHEN TLH.IS_RENEWAL='N' THEN TLH.PROPERTY_KEY END) AS NEW_LEASES,
      0 AS HF_CNT,
      COUNT(DISTINCT CASE WHEN TLH.IS_RENEWAL='N' THEN TLH.PROPERTY_KEY END) AS AL,
      COUNT(DISTINCT TLH.PROPERTY_KEY) AS APPR_CNT,
      ROUND(DIV0(
        COUNT(DISTINCT CASE WHEN TLH.IS_RENEWAL='N' THEN TLH.PROPERTY_KEY END),
        NULLIF(COUNT(DISTINCT TLH.PROPERTY_KEY),0)
      )*100,1) AS APPR_PCT
    FROM PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_LEASING_HIST TLH
    JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY=TLH.PROPERTY_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY=TLH.PROPERTY_KEY AND P.CURRENT_FLAG='Y'
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY=PUS.PORTFOLIO_KEY
    LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_SUBDIVISION SD ON SD.SUBDIVISION_KEY=PUS.SUBDIVISION_KEY AND SD.CURRENT_FLAG='Y'
    WHERE TO_DATE(TLH.LEASE_START_DATE_KEY::TEXT,'YYYYMMDD')>=DATEADD('month',-5,DATE_TRUNC('month','${startDate}'::DATE))
    AND TO_DATE(TLH.LEASE_START_DATE_KEY::TEXT,'YYYYMMDD')<DATEADD('month',1,DATE_TRUNC('month','${startDate}'::DATE))
    AND PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54)
    AND PUS.Organization_KEY IN (27,50,51,52,54,45,55,53,56,57,66)
    AND PO.IS_Active_AM='Y' AND PO.Current_Flag='Y' AND P.Current_Flag='Y'
    GROUP BY 1,2
    HAVING COUNT(DISTINCT TLH.PROPERTY_KEY) > 0
    ORDER BY 1,2`);
  const drcConversion = drcConvRaw.map(r=>({
    community: String(r.COMMUNITY??""),
    month:     String(r.MONTH_LABEL??""),
    l:         Number(r.L??0),
    hf:        Number(r.HF_CNT??0),
    al:        Number(r.AL??0),
    appr:      Number(r.APPR_CNT??0),
    apprPct:   r.APPR_PCT!=null?Number(r.APPR_PCT):null,
  }));

  // ── Days Occupied ─────────────────────────────────────────────────────────
  const daysOccRaw = await run("days-occ", `
    SELECT TO_CHAR(DATE_TRUNC('month',TO_DATE(H.CHANGED_DATE_KEY::TEXT,'YYYYMMDD')),'Mon YYYY') AS MONTH,
      MIN(DATE_TRUNC('month',TO_DATE(H.CHANGED_DATE_KEY::TEXT,'YYYYMMDD'))) AS SORT_DT,
      ROUND(AVG(DATEDIFF('day',
        TO_DATE(H.CHANGED_DATE_KEY::TEXT,'YYYYMMDD'),
        LAST_DAY(TO_DATE(H.CHANGED_DATE_KEY::TEXT,'YYYYMMDD')))),1) AS AVG_DAYS_OCC
    FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROP_UNIT_STATUS_HIST H
    JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY=H.PROPERTY_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY=PUS.PORTFOLIO_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY=H.PROPERTY_KEY AND P.CURRENT_FLAG='Y'
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY=PUS.PROPERTY_UNIT_KEY
    WHERE H.NEW_OCCUPANCY_STATUS_ID IN (1479,1480,1481)
    AND TO_DATE(H.CHANGED_DATE_KEY::TEXT,'YYYYMMDD')>=DATEADD('month',-5,DATE_TRUNC('month','${startDate}'::DATE))
    AND TO_DATE(H.CHANGED_DATE_KEY::TEXT,'YYYYMMDD')<DATEADD('month',1,DATE_TRUNC('month','${startDate}'::DATE))
    AND P.PROPERTY_STATE='Active' AND P.EntityID<>''
    AND PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54)
    AND PUS.Organization_KEY NOT IN (16,17) AND PO.IS_Active_AM='Y' AND PO.Current_Flag='Y'
    AND P.Current_Flag='Y' AND PU.Current_Flag='Y'
    GROUP BY 1 ORDER BY SORT_DT`);
  const daysOccupied = daysOccRaw.map(r=>({
    month:      String(r.MONTH??""),
    avgDaysOcc: r.AVG_DAYS_OCC!=null?Number(r.AVG_DAYS_OCC):null,
  }));

  // ── Tenant Demographics ───────────────────────────────────────────────────
  const tenantTotalRaw = await run("tenant-total", `
    SELECT
      COUNT(DISTINCT T.TENANT_KEY) AS TOTAL_TENANTS,
      ROUND(AVG(T.CURRENT_RENT),0) AS AVG_RENT,
      ROUND(AVG(PUS.Under_written_rent),0) AS AVG_UW_RENT
    FROM PROD_ANALYTICS.DBT_RESICAP.DIM_TENANT T
    JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_ACTIVITY TS2 ON TS2.TENANT_KEY=T.TENANT_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY=TS2.PROPERTY_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY=TS2.PROPERTY_KEY AND P.CURRENT_FLAG='Y'
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY=PUS.PORTFOLIO_KEY
    WHERE T.CURRENT_FLAG='Y' AND T.PRIMARY_TENANT='Y'
    AND P.PROPERTY_STATE='Active' AND P.EntityID<>''
    AND PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54)
    AND PUS.Organization_KEY NOT IN (16,17)
    AND PO.IS_Active_AM='Y' AND PO.Current_Flag='Y' AND P.Current_Flag='Y'
    AND T.TENANT_STATUS NOT IN ('Past','Future')`);
  const tenantTotalRow = tenantTotalRaw[0];
  const tenantTotalCount = Number(tenantTotalRow?.TOTAL_TENANTS ?? 0);
  const tenantAvgRent   = Number(tenantTotalRow?.AVG_RENT ?? 0);
  const tenantAvgUwRent = Number(tenantTotalRow?.AVG_UW_RENT ?? 0);
  const tenantVsUw = tenantAvgUwRent > 0
    ? Math.round((tenantAvgRent - tenantAvgUwRent) / tenantAvgUwRent * 1000) / 10
    : 0;

    const tenantDemoRaw = await run("tenant-demo", `
    SELECT R.REGION_NAME AS REGION,
      COUNT(DISTINCT T.TENANT_KEY) AS TENANTS,
      COUNT(DISTINCT CASE WHEN TI.ISMONTHTOMONTHLEASE=1 THEN T.TENANT_KEY END) AS MTM,
      ROUND(AVG(PU.BEDROOMS),1) AS BED,
      ROUND(AVG(PU.BATHROOMS),1) AS BATH,
      ROUND(AVG(PU.SQUARE_FOOTAGE),0) AS SQFT,
      0 AS YR_BUILT,
      ROUND(AVG(PUS.Under_written_rent),0) AS UW_RENT,
      ROUND(AVG(T.CURRENT_RENT),0) AS RENT,
      ROUND(AVG(T.CURRENT_RENT-PUS.Under_written_rent),0) AS RENT_VAR,
      ROUND(AVG(DIV0(T.CURRENT_RENT,NULLIF(PU.SQUARE_FOOTAGE,0))),2) AS RENT_PER_SQFT,
      0 AS ADDTL_OCCS,
      0 AS AVG_PETS,
      0 AS AVG_CREDIT,
      0 AS AVG_INCOME,
      0 AS TIME_IN_HOME
    FROM PROD_ANALYTICS.DBT_RESICAP.DIM_TENANT T
    JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_ACTIVITY TS2 ON TS2.TENANT_KEY=T.TENANT_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS ON PUS.PROPERTY_KEY=TS2.PROPERTY_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY=TS2.PROPERTY_KEY AND P.CURRENT_FLAG='Y'
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY=PUS.PORTFOLIO_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY=PUS.PROPERTY_UNIT_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_REGION R ON R.REGION_KEY=PUS.REGION_KEY
    LEFT JOIN PROD_REPLICA.HBPM_DBO.TENANTINFORMATIONS TI ON TI.TenantInformationId=T.TENANT_INFORMATION_ID
    WHERE T.CURRENT_FLAG='Y' AND T.PRIMARY_TENANT='Y'
    AND P.PROPERTY_STATE='Active' AND P.EntityID<>''
    AND PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54)
    AND PUS.Organization_KEY NOT IN (16,17) AND PO.IS_Active_AM='Y' AND PO.Current_Flag='Y'
    AND P.Current_Flag='Y' AND PU.Current_Flag='Y'
    AND PUS.Occupancy_Status NOT IN ('Not Managed','Dispositions')
    AND T.TENANT_STATUS NOT IN ('Past','Future')
    ${orgWhere} ${regionWhere}
    GROUP BY R.REGION_NAME
    ORDER BY TENANTS DESC`);
  const tenantDemographics = tenantDemoRaw.map(r=>({
    region:      String(r.REGION??""),
    tenants:     Number(r.TENANTS??0),
    mtm:         Number(r.MTM??0),
    bed:         r.BED!=null?Number(r.BED):null,
    bath:        r.BATH!=null?Number(r.BATH):null,
    sqft:        r.SQFT!=null?Number(r.SQFT):null,
    yrBuilt:     r.YR_BUILT!=null?Number(r.YR_BUILT):null,
    uwRent:      r.UW_RENT!=null?Number(r.UW_RENT):null,
    rent:        r.RENT!=null?Number(r.RENT):null,
    rentVar:     r.RENT_VAR!=null?Number(r.RENT_VAR):null,
    rentPerSqft: r.RENT_PER_SQFT!=null?Number(r.RENT_PER_SQFT):null,
    addtlOccs:   r.ADDTL_OCCS!=null?Number(r.ADDTL_OCCS):null,
    avgPets:     r.AVG_PETS!=null?Number(r.AVG_PETS):null,
    avgCredit:   r.AVG_CREDIT!=null?Number(r.AVG_CREDIT):null,
    avgIncome:   r.AVG_INCOME!=null?Number(r.AVG_INCOME):null,
    timeInHome:  r.TIME_IN_HOME!=null?Number(r.TIME_IN_HOME):null,
  }));
  const totalTenants = tenantTotalCount > 0 ? tenantTotalCount : tenantDemographics.reduce((a,r)=>a+r.tenants,0);
  const wtdRent   = tenantDemographics.reduce((a,r)=>a+(r.rent??0)*r.tenants,0);
  const wtdUwRent = tenantDemographics.reduce((a,r)=>a+(r.uwRent??0)*r.tenants,0);
  const avgVsUwRent = totalTenants>0
    ? Math.round((wtdRent/totalTenants - wtdUwRent/totalTenants) / (wtdUwRent/totalTenants||1) * 1000)/10
    : 0;

  // ── All Property Export ────────────────────────────────────────────────
  const allPropertyRaw = await run("all-property", `
    SELECT
      P.ENTITYID,
      P.HBPM_PROPERTY_ID,
      COALESCE(CAST(P.HBAM_PROPERTY_ID AS VARCHAR),'') AS ASSETID,
      CAST(NULL AS VARCHAR) AS HUBSPOT_ID,
      CAST(NULL AS VARCHAR) AS RENTLY_SERIAL,
      CAST(NULL AS VARCHAR) AS RENTLY_TYPE,
      R.REGION_NAME AS REGION,
      P.ADDRESS,
      PU.BEDROOMS AS BED,
      PU.BATHROOMS AS BATH,
      PU.SQUARE_FOOTAGE AS SQFT,
      COALESCE(SD.SUBDIVISION,'') AS SUBDIVISION,
      COALESCE(FP.FLOORPLAN,'') AS FLOORPLAN,
      COALESCE(CO.COUNTY_NAME,'') AS COUNTY,
      CAST(NULL AS VARCHAR) AS PM_ASSIGNED,
      CAST(NULL AS VARCHAR) AS APM,
      PUS.OCCUPANCY_STATUS AS PROPERTY_STATUS,
      RRQC.RRQCPASSDATE AS RRQ,
      T.TENANT_STATUS,
      TRIM(COALESCE(T.FIRST_NAME,'') || ' ' || COALESCE(T.LAST_NAME,'')) AS TENANT_NAME
    FROM PROD_ANALYTICS.DBT_RESICAP.FCT_PROPERTY_UNIT_SUMMARY PUS
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY P ON P.PROPERTY_KEY=PUS.PROPERTY_KEY AND P.CURRENT_FLAG='Y'
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PORTFOLIO PO ON PO.PORTFOLIO_KEY=PUS.PORTFOLIO_KEY
    JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_PROPERTY_UNIT PU ON PU.PROPERTY_UNIT_KEY=PUS.PROPERTY_UNIT_KEY
    LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_REGION R ON R.REGION_KEY=PUS.REGION_KEY
    LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_SUBDIVISION SD ON SD.SUBDIVISION_KEY=PUS.SUBDIVISION_KEY AND SD.CURRENT_FLAG='Y'
    LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_FLOORPLAN FP ON FP.FLOORPLAN_KEY=PUS.FLOORPLAN_KEY AND FP.CURRENT_FLAG='Y'
    LEFT JOIN PROD_ANALYTICS.DBT_RESICAP.DIM_COUNTY CO ON CO.COUNTY_KEY=PUS.COUNTY_KEY
    LEFT JOIN PROD_REPLICA.HBPM_DBO.PROPERTIES HBPM ON HBPM.PROPERTYID=P.HBPM_PROPERTY_ID
    LEFT JOIN (
      SELECT MAX(ID) AS RRQC_ID, HBID
      FROM PROD_REPLICA.HBAM_DBO.RRQCCHANGELOGS
      GROUP BY HBID
    ) RRQC_RECENT ON RRQC_RECENT.HBID = P.HBAM_PROPERTY_ID
    LEFT JOIN PROD_REPLICA.HBAM_DBO.RRQCCHANGELOGS RRQC
      ON RRQC.ID = RRQC_RECENT.RRQC_ID
    LEFT JOIN (
      SELECT
        TLA.PROPERTY_KEY,
        T.TENANT_STATUS,
        T.FIRST_NAME,
        T.LAST_NAME,
        RANK() OVER (PARTITION BY TLA.PROPERTY_KEY ORDER BY T.LEASE_ID DESC) AS RNK
      FROM PROD_ANALYTICS.DBT_RESICAP.DIM_TENANT T
      JOIN PROD_ANALYTICS.DBT_RESICAP.FCT_TENANT_LEASING_ACCUM TLA
        ON TLA.TENANT_KEY = T.TENANT_KEY
      WHERE T.CURRENT_FLAG='Y' AND T.PRIMARY_TENANT='Y'
        AND T.TENANT_STATUS NOT IN ('Past','Future')
    ) T ON T.PROPERTY_KEY=PUS.PROPERTY_KEY AND T.RNK=1
    WHERE P.PROPERTY_STATE='Active' AND P.EntityID<>''
    AND PO.Portfolio_KEY NOT IN (223,598,147,102,109,28,603,169,602,170,58,54)
    AND PUS.Organization_KEY NOT IN (16,17) AND PO.IS_Active_AM='Y' AND PO.Current_Flag='Y'
    AND P.Current_Flag='Y' AND PU.Current_Flag='Y'
    AND PUS.Occupancy_Status NOT IN ('Not Managed','Dispositions')
    ORDER BY R.REGION_NAME, P.ENTITYID
    LIMIT 5000`);
  const allProperties = allPropertyRaw.map(r=>({
    entityId:       String(r.ENTITYID??""),
    hbpmId:         String(r.HBPM_PROPERTY_ID??""),
    assetId:        String(r.ASSETID??""),
    hubspotId:      String(r.HUBSPOT_ID??""),
    rentlySerial:   String(r.RENTLY_SERIAL??""),
    rentlyType:     String(r.RENTLY_TYPE??""),
    region:         String(r.REGION??""),
    address:        String(r.ADDRESS??""),
    bed:            r.BED!=null?Number(r.BED):null,
    bath:           r.BATH!=null?Number(r.BATH):null,
    sqft:           r.SQFT!=null?Number(r.SQFT):null,
    subdivision:    String(r.SUBDIVISION??""),
    floorplan:      String(r.FLOORPLAN??""),
    county:         String(r.COUNTY??""),
    pmAssigned:     String(r.PM_ASSIGNED??""),
    apm:            String(r.APM??""),
    propertyStatus: String(r.PROPERTY_STATUS??""),
    rrq:            r.RRQ!=null?String(r.RRQ):"",
    tenantStatus:   String(r.TENANT_STATUS??""),
    tenantName:     String(r.TENANT_NAME??""),
  }));

  // ── Close connection & return ─────────────────────────────────────────────
  conn.close();

  const payload = {
    generatedAt:   new Date().toISOString(),
    selectedMonth: month,
    errors:        errors.length ? errors : undefined,
    heroKpis:      { totalProperties:totalProps, occupancyPct:eomOccupancy??0, activeListings },
    eomOccupancy, eomCollections, renewal, bomListingsLeased,
    woCycleTime, netTurnCost, runRateSpend, internalMaintenance,
    holdingFees, portfolioMetrics, orgSubMap, orgMetrics,
    regionRows, monthlyTrend,
    orgSummary: orgSummary.map(r=>({
      ...r,
      bomOcc:     orgOccMap[r.org]?.bomOcc     ?? null,
      eomOcc:     orgOccMap[r.org]?.eomOcc     ?? null,
      bomOccNum:  orgOccMap[r.org]?.bomOccNum  ?? 0,
      eomOccNum:  orgOccMap[r.org]?.eomOccNum  ?? 0,
      stabilized: orgOccMap[r.org]?.stabilized ?? 0,
    })),
    drcLto,
    drcConversion,
    daysOccupied,
    tenantDemographics,
    tenantSummary: { totalTenants, avgVsUwRent: tenantVsUw || avgVsUwRent },
    allProperties,
  };

  CACHE.set(cacheKey, { at: Date.now(), payload });
  return NextResponse.json(payload);
}